<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Getting to know your data | CRIM20452 Modelling Criminological Data</title>
  <meta name="description" content="This is a companion workbook for the 2nd year undergraduate module CRIM20452 Modelling Criminological Data at the University of Manchester" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Getting to know your data | CRIM20452 Modelling Criminological Data" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a companion workbook for the 2nd year undergraduate module CRIM20452 Modelling Criminological Data at the University of Manchester" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Getting to know your data | CRIM20452 Modelling Criminological Data" />
  
  <meta name="twitter:description" content="This is a companion workbook for the 2nd year undergraduate module CRIM20452 Modelling Criminological Data at the University of Manchester" />
  

<meta name="author" content="Laura Bui &amp; Reka Solymosi" />


<meta name="date" content="2021-02-06" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="a-first-lesson-about-r.html"/>
<link rel="next" href="data-visualization.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelling Criminological Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html"><i class="fa fa-check"></i><b>1</b> A First Lesson About R</a><ul>
<li class="chapter" data-level="1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#install-r-r-studio"><i class="fa fa-check"></i><b>1.1</b> Install R &amp; R Studio</a><ul>
<li class="chapter" data-level="1.1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#activity-1-identifying-your-operating-system"><i class="fa fa-check"></i><b>1.1.1</b> Activity 1: Identifying your operating system</a></li>
<li class="chapter" data-level="1.1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#activity-2-install-r-r-studio"><i class="fa fa-check"></i><b>1.1.2</b> Activity 2: Install R &amp; R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#getting-to-know-r-studio"><i class="fa fa-check"></i><b>1.2</b> Getting to know R Studio</a><ul>
<li class="chapter" data-level="1.2.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#the-four-panes-of-r-studio"><i class="fa fa-check"></i><b>1.2.1</b> The four panes of R Studio</a></li>
<li class="chapter" data-level="1.2.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#customising-r-studio"><i class="fa fa-check"></i><b>1.2.2</b> Customising R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#todays-3-topics"><i class="fa fa-check"></i><b>1.3</b> Today’s 3 (TOPICS)</a><ul>
<li class="chapter" data-level="1.3.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#operators-and-functions"><i class="fa fa-check"></i><b>1.3.1</b> Operators and Functions</a></li>
<li class="chapter" data-level="1.3.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#objects"><i class="fa fa-check"></i><b>1.3.2</b> Objects</a></li>
<li class="chapter" data-level="1.3.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#packages-1"><i class="fa fa-check"></i><b>1.3.3</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#summary"><i class="fa fa-check"></i><b>1.4</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html"><i class="fa fa-check"></i><b>2</b> Getting to know your data</a><ul>
<li class="chapter" data-level="2.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#r-projects-getting-your-work-files-organised"><i class="fa fa-check"></i><b>2.1</b> R Projects – Getting Your Work Files Organised</a><ul>
<li class="chapter" data-level="2.1.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#activity-1-making-yourself-a-project"><i class="fa fa-check"></i><b>2.1.1</b> Activity 1: Making yourself a project</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#importing-data"><i class="fa fa-check"></i><b>2.2</b> Importing Data</a><ul>
<li class="chapter" data-level="2.2.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#activity-2-importing-and-viewing-data"><i class="fa fa-check"></i><b>2.2.1</b> Activity 2: Importing and Viewing Data</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#todays-3-topics-1"><i class="fa fa-check"></i><b>2.3</b> Today’s 3 (TOPICS)</a><ul>
<li class="chapter" data-level="2.3.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#variables"><i class="fa fa-check"></i><b>2.3.1</b> Variables</a></li>
<li class="chapter" data-level="2.3.2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#labels"><i class="fa fa-check"></i><b>2.3.2</b> Labels</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#summary-1"><i class="fa fa-check"></i><b>2.4</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>3</b> Data Visualization</a><ul>
<li class="chapter" data-level="3.1" data-path="data-visualization.html"><a href="data-visualization.html#grammar-of-graphics"><i class="fa fa-check"></i><b>3.1</b> Grammar of Graphics</a><ul>
<li class="chapter" data-level="3.1.1" data-path="data-visualization.html"><a href="data-visualization.html#activity-1-getting-ready"><i class="fa fa-check"></i><b>3.1.1</b> Activity 1: Getting Ready</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-visualization.html"><a href="data-visualization.html#ggplot2"><i class="fa fa-check"></i><b>3.2</b> ggplot2</a></li>
<li class="chapter" data-level="3.3" data-path="data-visualization.html"><a href="data-visualization.html#todays-3"><i class="fa fa-check"></i><b>3.3</b> Today’s 3</a><ul>
<li class="chapter" data-level="3.3.1" data-path="data-visualization.html"><a href="data-visualization.html#layers"><i class="fa fa-check"></i><b>3.3.1</b> Layers</a></li>
<li class="chapter" data-level="3.3.2" data-path="data-visualization.html"><a href="data-visualization.html#graphs-for-nominal-and-ordinal-data"><i class="fa fa-check"></i><b>3.3.2</b> Graphs for Nominal and Ordinal Data</a></li>
<li class="chapter" data-level="3.3.3" data-path="data-visualization.html"><a href="data-visualization.html#graphs-for-interval-and-ratio-data"><i class="fa fa-check"></i><b>3.3.3</b> Graphs for Interval and Ratio Data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-visualization.html"><a href="data-visualization.html#summary-2"><i class="fa fa-check"></i><b>3.4</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>4</b> Descriptive Statistics</a><ul>
<li class="chapter" data-level="4.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#revisiting-descriptive-statistics"><i class="fa fa-check"></i><b>4.1</b> Revisiting Descriptive Statistics</a></li>
<li class="chapter" data-level="4.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#todays-3-1"><i class="fa fa-check"></i><b>4.2</b> Today’s 3</a><ul>
<li class="chapter" data-level="4.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#central-tendency"><i class="fa fa-check"></i><b>4.2.1</b> Central Tendency</a></li>
<li class="chapter" data-level="4.2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#outliers"><i class="fa fa-check"></i><b>4.2.2</b> Outliers</a></li>
<li class="chapter" data-level="4.2.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#measures-of-dispersion"><i class="fa fa-check"></i><b>4.2.3</b> Measures of Dispersion</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary-3"><i class="fa fa-check"></i><b>4.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="inferential-statistics.html"><a href="inferential-statistics.html"><i class="fa fa-check"></i><b>5</b> Inferential Statistics</a><ul>
<li class="chapter" data-level="5.1" data-path="inferential-statistics.html"><a href="inferential-statistics.html#generalising-about-the-world-from-data"><i class="fa fa-check"></i><b>5.1</b> Generalising About the World from Data</a></li>
<li class="chapter" data-level="5.2" data-path="inferential-statistics.html"><a href="inferential-statistics.html#todays-3-2"><i class="fa fa-check"></i><b>5.2</b> Today’s 3</a><ul>
<li class="chapter" data-level="5.2.1" data-path="inferential-statistics.html"><a href="inferential-statistics.html#samples"><i class="fa fa-check"></i><b>5.2.1</b> Samples</a></li>
<li class="chapter" data-level="5.2.2" data-path="inferential-statistics.html"><a href="inferential-statistics.html#standard-errors"><i class="fa fa-check"></i><b>5.2.2</b> Standard Errors</a></li>
<li class="chapter" data-level="5.2.3" data-path="inferential-statistics.html"><a href="inferential-statistics.html#confidence-intervals"><i class="fa fa-check"></i><b>5.2.3</b> Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="inferential-statistics.html"><a href="inferential-statistics.html#summary-4"><i class="fa fa-check"></i><b>5.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hypotheses.html"><a href="hypotheses.html"><i class="fa fa-check"></i><b>6</b> Hypotheses</a><ul>
<li class="chapter" data-level="6.1" data-path="hypotheses.html"><a href="hypotheses.html#hypothesis-testing"><i class="fa fa-check"></i><b>6.1</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="6.2" data-path="hypotheses.html"><a href="hypotheses.html#todays-3-3"><i class="fa fa-check"></i><b>6.2</b> Today’s 3</a><ul>
<li class="chapter" data-level="6.2.1" data-path="hypotheses.html"><a href="hypotheses.html#statistical-significance"><i class="fa fa-check"></i><b>6.2.1</b> Statistical Significance</a></li>
<li class="chapter" data-level="6.2.2" data-path="hypotheses.html"><a href="hypotheses.html#a-binomial-test"><i class="fa fa-check"></i><b>6.2.2</b> A Binomial Test</a></li>
<li class="chapter" data-level="6.2.3" data-path="hypotheses.html"><a href="hypotheses.html#single-sample-significance-tests"><i class="fa fa-check"></i><b>6.2.3</b> Single-sample significance tests</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="hypotheses.html"><a href="hypotheses.html#summary-5"><i class="fa fa-check"></i><b>6.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html"><i class="fa fa-check"></i><b>7</b> Relationships with Categorical Variables</a><ul>
<li class="chapter" data-level="7.1" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#associating-with-categorical-variables"><i class="fa fa-check"></i><b>7.1</b> Associating with Categorical Variables</a></li>
<li class="chapter" data-level="7.2" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#todays-3-4"><i class="fa fa-check"></i><b>7.2</b> Today’s 3</a><ul>
<li class="chapter" data-level="7.2.1" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#independent-and-dependent-variables"><i class="fa fa-check"></i><b>7.2.1</b> Independent and Dependent Variables</a></li>
<li class="chapter" data-level="7.2.2" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#the-t-test"><i class="fa fa-check"></i><b>7.2.2</b> The T-Test</a></li>
<li class="chapter" data-level="7.2.3" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#chi-square"><i class="fa fa-check"></i><b>7.2.3</b> Chi-square</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#summary-6"><i class="fa fa-check"></i><b>7.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html"><i class="fa fa-check"></i><b>8</b> Strength of Relationships</a><ul>
<li class="chapter" data-level="8.1" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#measures-of-association"><i class="fa fa-check"></i><b>8.1</b> Measures of Association</a></li>
<li class="chapter" data-level="8.2" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#todays-3-5"><i class="fa fa-check"></i><b>8.2</b> Today’s 3</a><ul>
<li class="chapter" data-level="8.2.1" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#between-categorical-nominal-variables"><i class="fa fa-check"></i><b>8.2.1</b> Between Categorical, Nominal Variables</a></li>
<li class="chapter" data-level="8.2.2" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#between-categorical-ordinal-variables"><i class="fa fa-check"></i><b>8.2.2</b> Between Categorical, Ordinal Variables</a></li>
<li class="chapter" data-level="8.2.3" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#between-numeric-variables"><i class="fa fa-check"></i><b>8.2.3</b> Between Numeric Variables</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#summary-7"><i class="fa fa-check"></i><b>8.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>9</b> Regression</a><ul>
<li class="chapter" data-level="9.1" data-path="regression.html"><a href="regression.html#multiple-and-simultaneous-relationships"><i class="fa fa-check"></i><b>9.1</b> Multiple and Simultaneous Relationships</a></li>
<li class="chapter" data-level="9.2" data-path="regression.html"><a href="regression.html#todays-3-6"><i class="fa fa-check"></i><b>9.2</b> Today’s 3</a><ul>
<li class="chapter" data-level="9.2.1" data-path="regression.html"><a href="regression.html#assumptions-of-ols-regression"><i class="fa fa-check"></i><b>9.2.1</b> Assumptions of OLS Regression</a></li>
<li class="chapter" data-level="9.2.2" data-path="regression.html"><a href="regression.html#interpreting-ols-regression"><i class="fa fa-check"></i><b>9.2.2</b> Interpreting OLS Regression</a></li>
<li class="chapter" data-level="9.2.3" data-path="regression.html"><a href="regression.html#logistic-regression"><i class="fa fa-check"></i><b>9.2.3</b> Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="regression.html"><a href="regression.html#summary-8"><i class="fa fa-check"></i><b>9.3</b> SUMMARY</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">CRIM20452 Modelling Criminological Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="getting-to-know-your-data" class="section level1">
<h1><span class="header-section-number">Chapter 2</span> Getting to know your data</h1>
<div id="variables-labels-and-subsetting" class="section level4 unnumbered">
<h4><em>Variables, Labels, and Subsetting</em></h4>
<div id="learning-outcomes-1" class="section level5 unnumbered">
<h5><strong>Learning Outcomes:</strong></h5>
<ul>
<li>Create a project in <code>R</code> to refer back to for each session</li>
<li>Learn what variables are and how to examine them in <code>R</code></li>
<li>Learn how to label variables</li>
<li>Learn how to subset select cases</li>
</ul>
<div style="margin-bottom:30px;">

</div>
</div>
<div id="todays-learning-tools-1" class="section level5 unnumbered">
<h5><strong>Today’s Learning Tools:</strong></h5>
<div style="margin-bottom:15px;">

</div>
</div>
<div id="total-number-of-activities-8-1" class="section level5 unnumbered">
<h5><em>Total number of activities</em>: 8</h5>
<div style="margin-bottom:15px;">

</div>
</div>
<div id="data-1" class="section level5 unnumbered">
<h5><em>Data:</em></h5>
<ul>
<li>National Crime Victimization Survey (NCVS)</li>
</ul>
<div style="margin-bottom:15px;">

</div>
</div>
<div id="packages-2" class="section level5 unnumbered">
<h5><em>Packages:</em></h5>
<ul>
<li><code>dplyr</code></li>
<li><code>here</code></li>
<li><code>haven</code></li>
<li><code>labelled</code></li>
<li><code>sjlabelled</code></li>
<li><code>tibble</code></li>
</ul>
<div style="margin-bottom:15px;">

</div>
</div>
<div id="functions-introduced-and-packages-to-which-they-belong-1" class="section level5 unnumbered">
<h5><em>Functions introduced (and packages to which they belong)</em></h5>
<ul>
<li><code>add_column()</code> : Adds columns to a data frame (<code>tibble</code>)</li>
<li><code>attributes()</code> : Access object attributes, such as value labels (<code>base R</code>)</li>
<li><code>case_when()</code> : Allows users to vectorize multiple if / if else statements (<code>dplyr</code>)</li>
<li><code>count()</code> : Counts the number of occurrences (<code>dplyr</code>)</li>
<li><code>dir.create()</code> : creates a new folder in a project (<code>base R</code>)</li>
<li><code>factor()</code> Creates a factor (<code>base R</code>)</li>
<li><code>filter()</code> : Subsets a data frame to rows when a condition is true (<code>dplyr</code>)</li>
<li><code>get_labels()</code> : Returns value labels of labelled data (<code>sjlabelled</code>)</li>
<li><code>here()</code> : Finds a project’s files based on the current working directory (<code>here</code>)</li>
<li><code>mutate()</code> : Creates new vectors or transforms existing ones (<code>dplyr</code>)</li>
<li><code>read_spss()</code> : Imports SPSS .sav files (<code>haven</code>)</li>
<li><code>remove_labels()</code> : Removes value labels from a variable (<code>sjlabelled</code>)</li>
<li><code>remove_var_label()</code> : Removes a variable’s label (<code>labelled</code>)</li>
<li><code>sapply()</code> : Applies a function over a vector or list (<code>base R</code>)</li>
<li><code>select()</code> : Select columns to retain or drop (<code>dplyr</code>)</li>
<li><code>var_label()</code> : Returns or sets a variable label (<code>labelled</code>)</li>
</ul>
<hr />
<p>Last time, we installed our first package, <code>dplyr</code>. This is one of a number of packages from what is known as <strong>tidyverse</strong>. In this lesson, we use <code>dplyr</code> and other <code>tidyverse</code> packages so that we can get to know our data. Being familiar with our data requires knowing what they comprise and what form they take. ‘Tidying’ our data through labelling, reformatting, recoding, and creating new variables will help with this step in the data analysis process. Today we will learn another three topics related to data tidying: <strong>variables</strong>, <strong>labels</strong>, and <strong>subsetting</strong>. Let us load <code>dplyr</code> if it is not loaded already:</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1"><span class="kw">library</span>(dplyr)</a></code></pre></div>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 3.6.3</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div style="margin-bottom:50px;">

</div>
</div>
</div>
<div id="r-projects-getting-your-work-files-organised" class="section level2">
<h2><span class="header-section-number">2.1</span> R Projects – Getting Your Work Files Organised</h2>
<div style="margin-bottom:30px;">

</div>
<p>Although today is focused on tidying data, it is also helpful if your work is tidy and found in one easily accessible folder. By saving work inside a <strong>project</strong>, you can find files such as data and scripts related to specific work in a single working directory. Let us get into the habit of doing this:</p>
<div style="margin-bottom:70px;">

</div>
<div id="activity-1-making-yourself-a-project" class="section level3">
<h3><span class="header-section-number">2.1.1</span> Activity 1: Making yourself a project</h3>
• Click on the top right tab called <em>Project: (None)</em> - Figure 2.1
<div style="margin-bottom:30px;">

</div>
<div class="figure">
<img src="Images/project.png" alt="Figure 2.1 Click on Project: (None)" style="width:70.0%" />
<p class="caption"><strong>Figure 2.1</strong> Click on <em>Project: (None)</em></p>
</div>
<div style="margin-bottom:30px;">

</div>
<ul>
<li>Click on <em>New Project</em>. A window with different options appears. Create your project in <em>New Directory</em> and then click <em>New Project</em></li>
</ul>
<div style="margin-bottom:15px;">

</div>
<ul>
<li>Choose a name for your project (e.g., r_crim_course) and a location (working directory) where your project will be created</li>
</ul>
<div style="margin-bottom:15px;">

</div>
<ul>
<li>Now click on <em>Create Project</em> and your new project will be launched</li>
</ul>
<div style="margin-bottom:15px;">

</div>
<p>Inside your project, you can organise it by having separate files, one for scripts, one for data, one for outputs, and another for visuals. You can make these with the function <code>dir.create()</code>:</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1"><span class="co"># For example, to make a sub-folder called &#39;Datasets&#39; in your project folder, type this into your console pane:</span></a>
<a class="sourceLine" id="cb51-2" title="2"><span class="kw">dir.create</span>(<span class="st">&quot;Datasets&quot;</span>)</a></code></pre></div>
<div style="margin-bottom:50px;">

</div>
<p>If you noticed in your <em>Files, Plots…</em> pane, the files there tell you what folder you are automatically working in. This is known as your <em>working directory</em>, the default location that appears when you open <code>RStudio</code>. Wherever your <code>R project</code> is saved will be the working directory.</p>
<p>In your group google sheets, type the name of your <code>R</code> project and in which location it is in. Now decide whether this is good location for your <code>R</code> project. For example, is the location name too long? (For example,‘C: xx Desktop  Manchester’ is too long and you might run into problems later.) Or are there other files that are for other classes there too? If doubtful about the location of your project, move it somewhere else you think is more appropriate.</p>
<div style="margin-bottom:50px;">

</div>
Whenever you want to locate certain files within your <code>Project</code>, use the <code>here</code> package:
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1"><span class="kw">library</span>(here)</a></code></pre></div>
<pre><code>## Warning: package &#39;here&#39; was built under R version 3.6.3</code></pre>
<pre><code>## here() starts at C:/Users/buihl/Desktop/Modelling-Crime-Data-2021</code></pre>
<div style="margin-bottom:50px;">

</div>
<p>Doing so is better than typing out the exact location of your file, which can be tedious. The next section shows how to use the <code>here ()</code> function to import data from the National Crime Victimization Survey (NCVS).</p>
<p>You can read on why projects are useful here: <a href="https://www.r-bloggers.com/2020/01/rstudio-projects-and-working-directories-a-beginners-guide/">https://www.r-bloggers.com/2020/01/rstudio-projects-and-working-directories-a-beginners-guide/</a></p>
<hr />
</div>
</div>
<div id="importing-data" class="section level2">
<h2><span class="header-section-number">2.2</span> Importing Data</h2>
<p>Here is another <code>tidyverse</code> package to install:</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1"><span class="kw">library</span>(haven)</a></code></pre></div>
<pre><code>## Warning: package &#39;haven&#39; was built under R version 3.6.3</code></pre>
<div style="margin-bottom:50px;">

</div>
<p><code>Haven</code> enables <code>R</code> to understand various data formats used by other statistical packages such as SPSS and STATA. We will need this package to open data in its diverse forms.</p>
<div style="margin-bottom:70px;">

</div>
<div id="activity-2-importing-and-viewing-data" class="section level3">
<h3><span class="header-section-number">2.2.1</span> Activity 2: Importing and Viewing Data</h3>
<p>You will have saved the NCVS in a relevant file in your project, so now let us load this data using <code>read_spss()</code> from <code>Haven</code>:</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1"><span class="co"># Importing our SPSS dataset and naming it ‘ncvs’ </span></a>
<a class="sourceLine" id="cb57-2" title="2">ncvs &lt;-<span class="st"> </span><span class="kw">read_spss</span>(<span class="kw">here</span>(<span class="st">&quot;Datasets&quot;</span>, <span class="st">&quot;NCVS lone offender assaults 1992 to 2013.sav&quot;</span>))</a></code></pre></div>
<div style="margin-bottom:50px;">

</div>
<p>What you are saying to <code>R</code> is the following:</p>
<blockquote>
<p>My data, <em>NCVS lone offender assaults 1992 to 2013</em>, is a .sav file. Therefore, it is an SPSS dataset and is located in the sub-folder called <em>Datasets</em> in my default working directory. <code>R</code>, please extract it from <em>here</em>, understand it, and place it in an object called <code>ncvs</code>, so I can find it in <code>RStudio</code>.</p>
</blockquote>
<div style="margin-bottom:15px;">

</div>
To view the new data frame, <code>ncvs</code>, type:
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="kw">View</span>(ncvs)</a></code></pre></div>
<div style="margin-bottom:50px;">

</div>
<p>A tab appears labelled ‘ncvs’. In it, you can view all its contents. In your group google sheets, type how many ‘entries’ and ‘columns’ there are in our dataframe, <code>ncvs</code>.</p>
<!-- # 1431 entries and 46 columns -->
<hr />
</div>
</div>
<div id="todays-3-topics-1" class="section level2">
<h2><span class="header-section-number">2.3</span> Today’s 3 (TOPICS)</h2>
<div style="margin-bottom:30px;">

</div>
<p>We now have data to tidy in <code>R</code>, so onto our three main topics for this week: <strong>variables</strong>, <strong>labels</strong>, and <strong>subsetting</strong>.</p>
<div style="margin-bottom:30px;">

</div>
<hr />
<div id="variables" class="section level3">
<h3><span class="header-section-number">2.3.1</span> Variables</h3>
<p>Variables can be persons, places, things, or ideas that we are interested in studying. For example, height and favourite football team. Different variable types refer to different levels of measurement: nominal, ordinal, and interval/ ratio. Variables appear as vectors and as columns of data frames.</p>
<p>In <code>R</code>, nominal and ordinal variables are encoded as a <strong>factor</strong> class because they are categorical characteristics, so take on a limited number of values; factors are like the integer vector introduced last week but each integer is a label.</p>
<p>Likewise, interval and ratio variables are encoded as <strong>numeric</strong> class because they are continuous characteristics, so take on a wide range of values.</p>
<div style="margin-bottom:70px;">

</div>
<div id="activity-3-identifying-a-variables-class" class="section level4">
<h4><span class="header-section-number">2.3.1.1</span> Activity 3: Identifying a variable’s class</h4>
<p>How do you know what your variable is classed as? There are two ways of knowing using our <code>ncvs</code> data:</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1"><span class="co"># To see the class of all the variables (columns) in our data frame, ncvs, we use:</span></a>
<a class="sourceLine" id="cb59-2" title="2"><span class="kw">sapply</span>(ncvs, class)</a>
<a class="sourceLine" id="cb59-3" title="3"></a>
<a class="sourceLine" id="cb59-4" title="4"><span class="co"># To see the class of a specific variable, such as the variable ‘injured’, we use:</span></a>
<a class="sourceLine" id="cb59-5" title="5"><span class="kw">class</span>(ncvs<span class="op">$</span>injured)</a>
<a class="sourceLine" id="cb59-6" title="6"></a>
<a class="sourceLine" id="cb59-7" title="7"><span class="co"># The $ symbol allows us to access specific variables in a data frame object</span></a>
<a class="sourceLine" id="cb59-8" title="8"></a>
<a class="sourceLine" id="cb59-9" title="9"><span class="co"># The $ symbol must be accompanied by the name of the data frame!</span></a></code></pre></div>
<div style="margin-bottom:50px;">

</div>
<p>Now, may you find out what is the class of the variable <code>weaponpresent</code>? In your googledoc, type out the answer and the code you used to get that answer.</p>
<!-- # numeric and class(ncvs$weaponpresent) -->
<hr />
<div style="margin-bottom:50px;">

</div>
<p>You may have noticed that many of the variables in our data frame were classed as <code>haven_labelled</code>. What is this, you ask? When we use the <code>haven()</code> function to import data, <code>R</code> keeps the information associated with that file type – the SPSS variable information and value labels that were in the dataset. In practice, therefore, you can find categorical data in <code>R</code> embedded in very different types of vectors (e.g., character, factor, or haven labelled) depending on decisions taken by whomever created the data frame.</p>
<div style="margin-bottom:30px;">

</div>
<hr />
</div>
<div id="formatting-classes-and-value-labels" class="section level4">
<h4><span class="header-section-number">2.3.1.2</span> <strong>Formatting Classes and Value Labels</strong></h4>
<div style="margin-bottom:30px;">

</div>
<p>In some cases, you may want to make changes to how variables are classed. We can change our variable to specifically be classed as ‘factor’:</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1"><span class="co"># Name the newly created factor &#39;injured_r&#39;</span></a>
<a class="sourceLine" id="cb60-2" title="2"><span class="co">#Specify the order we want our variable labels</span></a>
<a class="sourceLine" id="cb60-3" title="3">ncvs<span class="op">$</span>injured_r &lt;-<span class="st"> </span><span class="kw">factor</span>(ncvs<span class="op">$</span>injured, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Uninjured&quot;</span>, <span class="st">&quot;Injured&quot;</span>))</a>
<a class="sourceLine" id="cb60-4" title="4"><span class="kw">table</span>(ncvs<span class="op">$</span>injured_r)</a></code></pre></div>
<pre><code>## 
## Uninjured   Injured 
##       967       464</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1"><span class="kw">attributes</span>(ncvs<span class="op">$</span>injured_r)</a></code></pre></div>
<pre><code>## $levels
## [1] &quot;Uninjured&quot; &quot;Injured&quot;  
## 
## $class
## [1] &quot;factor&quot;</code></pre>
<div style="margin-bottom:50px;">

</div>
<hr />
</div>
<div id="recoding-and-creating-new-variables" class="section level4">
<h4><span class="header-section-number">2.3.1.3</span> <strong>Recoding and Creating New Variables</strong></h4>
<div style="margin-bottom:30px;">

</div>
<p>In some circumstances, we would like to recode variables. Recoding could entail collapsing multiple values of your variable into a single category or making some values of your variable become missing. In other circumstances, we may want to create a brand new variable that combines data from two others. First, time to install another package to learn the <code>add_column()</code> function: <code>tibble</code>. Now let us learn!</p>
<div style="margin-bottom:70px;">

</div>
</div>
<div id="activity-4-creating-a-new-variable-from-1-existing-variable-3-examples" class="section level4">
<h4><span class="header-section-number">2.3.1.4</span> Activity 4: Creating a new variable from 1 existing variable: 3 examples</h4>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1"><span class="co"># Load the &#39;tibble&#39; package</span></a>
<a class="sourceLine" id="cb64-2" title="2"><span class="kw">library</span>(tibble)</a>
<a class="sourceLine" id="cb64-3" title="3"></a>
<a class="sourceLine" id="cb64-4" title="4"><span class="co"># 1. Create the new variable ‘InjuredNew’ from ‘injured’ </span></a>
<a class="sourceLine" id="cb64-5" title="5">ncvs<span class="op">$</span>InjuredNew &lt;-ncvs<span class="op">$</span>injured </a>
<a class="sourceLine" id="cb64-6" title="6"></a>
<a class="sourceLine" id="cb64-7" title="7"><span class="co"># 2. Give value labels to the values of the previously created variable, &#39;injured_r&#39;</span></a>
<a class="sourceLine" id="cb64-8" title="8">ncvs<span class="op">$</span>injured_r &lt;-<span class="st"> </span><span class="kw">factor</span>(ncvs<span class="op">$</span>injured, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Uninjured&quot;</span>, <span class="st">&quot;Injured&quot;</span>), <span class="dt">ordered =</span> <span class="ot">TRUE</span>) </a>
<a class="sourceLine" id="cb64-9" title="9"></a>
<a class="sourceLine" id="cb64-10" title="10"><span class="kw">attributes</span>(ncvs<span class="op">$</span>injured_r)</a></code></pre></div>
<pre><code>## $levels
## [1] &quot;Uninjured&quot; &quot;Injured&quot;  
## 
## $class
## [1] &quot;ordered&quot; &quot;factor&quot;</code></pre>
<div style="margin-bottom:50px;">

</div>
<p>The first example uses the package <code>tibble</code> to make an additional variable. This new variable, <code>InjuredNew</code>, has the same exact information as the variable <code>injured</code>.</p>
<p>In the second example, we changed our <code>injured_r</code> variable so that its values would have value labels.</p>
<p>In your group googledoc, type out the value for each value label of <code>injured_r</code>. If you are not sure how to figure this out, identify what the values were and run the <code>attributes</code> function on <code>injured_r</code> again. The order in which the value label appears from left to right will correspond to the order of values from lowest to highest.</p>
<p>Now we learn how to create a new variable that gives an ID number for each of our cases (rows):</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb66-1" title="1"><span class="co"># 3. Create a new column (aka variable) that has a row ID </span></a>
<a class="sourceLine" id="cb66-2" title="2"><span class="kw">add_column</span>(ncvs, <span class="dt">newid =</span> <span class="dv">1</span><span class="op">:</span><span class="kw">nrow</span>(ncvs))</a></code></pre></div>
<pre><code>## # A tibble: 1,431 x 49
##     YEAR  V2119   V2129 V3014   V3016   V3018   V3021   V3023 V3023A  V3024
##    &lt;dbl&gt; &lt;dbl+&gt; &lt;dbl+l&gt; &lt;dbl&gt; &lt;dbl+l&gt; &lt;dbl+l&gt; &lt;dbl+l&gt; &lt;dbl+l&gt; &lt;dbl+&gt; &lt;dbl+&gt;
##  1  2000 2 [No] 2 [(S)~    34 6 [Not~ 1 [Mal~ 1 [Yes] 1 [Whi~     NA 2 [No]
##  2  2000 2 [No] 2 [(S)~    22 6 [Not~ 2 [Fem~ 1 [Yes] 1 [Whi~     NA 2 [No]
##  3  2000 2 [No] 3 [Not~    21 5 [Nev~ 1 [Mal~ 1 [Yes] 1 [Whi~     NA 2 [No]
##  4  2000 2 [No] 3 [Not~    18 6 [Not~ 2 [Fem~ 2 [No]  1 [Whi~     NA 2 [No]
##  5  2000 2 [No] 2 [(S)~    16 6 [Not~ 2 [Fem~ 2 [No]  1 [Whi~     NA 2 [No]
##  6  2000 2 [No] 1 [Cit~    13 6 [Not~ 2 [Fem~ 2 [No]  1 [Whi~     NA 2 [No]
##  7  2000 2 [No] 2 [(S)~    16 6 [Not~ 1 [Mal~ 2 [No]  1 [Whi~     NA 2 [No]
##  8  2000 2 [No] 2 [(S)~    48 6 [Not~ 1 [Mal~ 1 [Yes] 1 [Whi~     NA 2 [No]
##  9  2000 2 [No] 2 [(S)~    12 5 [Nev~ 1 [Mal~ 1 [Yes] 1 [Whi~     NA 2 [No]
## 10  2000 2 [No] 2 [(S)~    42 6 [Not~ 1 [Mal~ 1 [Yes] 1 [Whi~     NA 2 [No]
## # ... with 1,421 more rows, and 39 more variables: V2026 &lt;dbl+lbl&gt;,
## #   V4049 &lt;dbl+lbl&gt;, V4234 &lt;dbl+lbl&gt;, V4235 &lt;dbl+lbl&gt;, V4236 &lt;dbl+lbl&gt;,
## #   V4237 &lt;dbl+lbl&gt;, V4237A &lt;dbl+lbl&gt;, V4238 &lt;dbl+lbl&gt;, V4239 &lt;dbl+lbl&gt;,
## #   V4240 &lt;dbl+lbl&gt;, V4241 &lt;dbl+lbl&gt;, V4242 &lt;dbl+lbl&gt;, V4243 &lt;dbl+lbl&gt;,
## #   V4244 &lt;dbl+lbl&gt;, V4245 &lt;dbl+lbl&gt;, V4246 &lt;dbl+lbl&gt;, V4246A &lt;dbl+lbl&gt;,
## #   V4246B &lt;dbl+lbl&gt;, V4246C &lt;dbl+lbl&gt;, V4246E &lt;dbl+lbl&gt;, V4246F &lt;dbl+lbl&gt;,
## #   V4246G &lt;dbl+lbl&gt;, V4247 &lt;dbl+lbl&gt;, V4528 &lt;dbl+lbl&gt;, injured &lt;dbl+lbl&gt;,
## #   privatelocation &lt;dbl&gt;, reportedtopolice &lt;dbl+lbl&gt;, weaponpresent &lt;dbl&gt;,
## #   medicalcarereceived &lt;dbl&gt;, `filter_$` &lt;dbl+lbl&gt;, relationship &lt;dbl+lbl&gt;,
## #   Policereported &lt;dbl+lbl&gt;, victimreported &lt;dbl+lbl&gt;,
## #   thirdpartyreport &lt;dbl+lbl&gt;, maleoff &lt;dbl+lbl&gt;, age_r &lt;dbl&gt;,
## #   injured_r &lt;ord&gt;, InjuredNew &lt;dbl+lbl&gt;, newid &lt;int&gt;</code></pre>
<div style="margin-bottom:70px;">

</div>
<hr />
</div>
<div id="activity-5-creating-a-new-variable-from-more-than-1-existing-variables" class="section level4">
<h4><span class="header-section-number">2.3.1.5</span> Activity 5: Creating a new variable from more than 1 existing variables</h4>
<p>Now we want to create a new variable in our NCVS data that tells us about the severity of the victimization experienced by the respondent. That severity will be measured by two variables: (1) whether the offender had a weapon and (2) whether the victim sustained an injury during their victimization. These are not necessarily the best variables to use in measuring victimization severity; this example, however, should illustrate how you might combine variables to create a new one.</p>
<p>Before we decide to do this, we need to know if we can do so by first understanding those variables of interest. By using the function <code>count ()</code>, we get a good sense of the values and the number of respondents in each of those values for both variables.</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1"><span class="co"># Is the appropriate package, &#39;dplyr&#39;, loaded? </span></a>
<a class="sourceLine" id="cb68-2" title="2"><span class="co"># You can check what package each function we learn today belongs to by referring to the top of each online lesson, under &#39;Functions Introduced&#39;</span></a>
<a class="sourceLine" id="cb68-3" title="3"></a>
<a class="sourceLine" id="cb68-4" title="4"><span class="co"># Using count ( ) for ‘injured’ and ‘weaponpresent’</span></a>
<a class="sourceLine" id="cb68-5" title="5"><span class="kw">count</span>(ncvs, injured)</a></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##         injured     n
##       &lt;dbl+lbl&gt; &lt;int&gt;
## 1 0 [uninjured]   967
## 2 1 [injured]     464</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1"><span class="kw">count</span>(ncvs, weaponpresent)</a></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   weaponpresent     n
##           &lt;dbl&gt; &lt;int&gt;
## 1             0   950
## 2             1   406
## 3            NA    75</code></pre>
<div style="margin-bottom:50px;">

</div>
<p>This function tells us that <code>injured</code>, a nominal-level variable, is stored as an integer, where the 0 value means the victim was uninjured and the 1 value means they were injured. Often in data, ‘0’ represents the absence of the feature being measured and ‘1’ means the presence of such feature. Also, the <code>weaponpresent</code> variable is also a nominal variable stored as an integer. Here, more victims report that the offender did not use a weapon during the offence (n= 950) as opposed to using one (n= 406). In addition, there are a number of missing values for this question (n= 75).</p>
<p>There is a particular function from the <code>dplyr</code> package that is very handy for creating a new variable from more than 1 variable. It is called <code>mutate</code>. The <code>mutate()</code> function will create a new column that comprises the sum of both of these variables, keeping the old variables too.</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1"><span class="co"># Create the new variable with mutate </span></a>
<a class="sourceLine" id="cb72-2" title="2">ncvs &lt;-<span class="st"> </span><span class="kw">mutate</span>(ncvs, <span class="dt">severity =</span> injured <span class="op">+</span><span class="st"> </span>weaponpresent)</a>
<a class="sourceLine" id="cb72-3" title="3"></a>
<a class="sourceLine" id="cb72-4" title="4"><span class="co"># Now let’s check the new variable ‘severity’ against the old ones</span></a>
<a class="sourceLine" id="cb72-5" title="5">ncvs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(injured, weaponpresent, severity) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">sample_n</span>(<span class="dv">10</span>)</a></code></pre></div>
<pre><code>## # A tibble: 10 x 3
##          injured weaponpresent severity
##        &lt;dbl+lbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;
##  1 0 [uninjured]             1        1
##  2 0 [uninjured]             1        1
##  3 0 [uninjured]             0        0
##  4 0 [uninjured]             1        1
##  5 0 [uninjured]             0        0
##  6 0 [uninjured]             0        0
##  7 1 [injured]               0        1
##  8 0 [uninjured]             1        1
##  9 0 [uninjured]             0        0
## 10 0 [uninjured]             0        0</code></pre>
<div style="margin-bottom:50px;">

</div>
<p>Notice that <code>%&gt;%</code> . This is known as the <strong>pipe operator</strong>, which is a nifty shortcut in <code>R</code> coding. It means that we only need to specify the data frame object once at the beginning as opposed to typing out the name of the data frame repeatedly. In all subsequent functions, notice that the object is ‘piped’ through.</p>
<p>The <code>severity</code> variable is ordinal-level, where 0 is the least severe (neither a weapon was used nor the victim injured), 1 is more severe (either the offender wielded a weapon or the victim reported being injured), and 2 is the most severe (the respondent reported being injured and the offender had a weapon). You can then add value labels to reflect this understanding. Try it out and type the code you used to add those value labels to <code>severity</code> in your group googledoc:</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1"><span class="co"># Clueless as to how to add value labels? Refer to Activity 4</span></a>
<a class="sourceLine" id="cb74-2" title="2"><span class="co"># Here is some help to add value labels to the &#39;severity&#39; variable:</span></a>
<a class="sourceLine" id="cb74-3" title="3"></a>
<a class="sourceLine" id="cb74-4" title="4"><span class="co"># ncvs$severity &lt;- (ncvs$severity, labels = ??? )</span></a></code></pre></div>
<div style="margin-bottom:70px;">

</div>
<!-- # ncvs$severity<- factor(ncvs$severity, labels = c("nothing", "victim or weapon", "both"), ordered = TRUE) -->
<p>The above example was simple, but often, we will want to make more complex combinations of variables. This is known as <strong>recoding</strong>. For example, we want to turn the variable in the NCVS dataset, called <code>relationship</code>, into a dichotomous variable called <code>notstranger</code> whereby the offender was a stranger (0) or was known to the victim (1).</p>
<p>Before doing this, we again use the <code>count ()</code> function to understand the variable of interest, <code>relationship</code>, and it has four categories. We then use <code>mutate ()</code> and <code>case_when ()</code>. Think of <code>case_when()</code> like an ‘if’ logical statement. It allows us to make changes to a variable that are conditional on some requirement. Note below that this turns our new categories into character values.</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1"><span class="co"># Making the ‘notstrange’ variable by collapsing the values of the variable ‘relationship’ into only two values</span></a>
<a class="sourceLine" id="cb75-2" title="2">ncvs &lt;-<span class="st"> </span>ncvs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">notstranger =</span> <span class="kw">case_when</span>(relationship <span class="op">%in%</span><span class="st"> </span><span class="dv">0</span> <span class="op">~</span><span class="st"> &quot;Stranger&quot;</span>, relationship <span class="op">%in%</span><span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">3</span> <span class="op">~</span><span class="st"> &quot;Not a stranger&quot;</span>))</a>
<a class="sourceLine" id="cb75-3" title="3"></a>
<a class="sourceLine" id="cb75-4" title="4"><span class="co"># We could also run the following code to make the character values numeric rather than string (e.g., stranger vs not a stranger) </span></a>
<a class="sourceLine" id="cb75-5" title="5">ncvs &lt;-<span class="st"> </span>ncvs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">notstranger =</span> <span class="kw">case_when</span>(relationship <span class="op">==</span><span class="st"> </span><span class="dv">0</span> <span class="op">~</span><span class="st"> </span><span class="dv">0</span>, relationship <span class="op">&lt;=</span><span class="st"> </span><span class="dv">3</span> <span class="op">~</span><span class="st"> </span><span class="dv">1</span>))</a></code></pre></div>
<div style="margin-bottom:50px;">

</div>
<hr />
</div>
</div>
<div id="labels" class="section level3">
<h3><span class="header-section-number">2.3.2</span> Labels</h3>
<div style="margin-bottom:30px;">

</div>
<p>Variables sometimes come with labels – these are very brief descriptions of the variable itself and what its values are. We are familiar with these because of our previous activities. Value labels are very useful when we have a nominal or ordinal level variable in our dataset that has been assigned numeric values. To have a look at what are your variable and value labels, use the function <code>attributes()</code>:</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1"><span class="kw">attributes</span>(ncvs<span class="op">$</span>injured)</a></code></pre></div>
<pre><code>## $label
## [1] &quot;Victim Sustained Injuries During Vicitmization&quot;
## 
## $format.spss
## [1] &quot;F8.2&quot;
## 
## $display_width
## [1] 10
## 
## $class
## [1] &quot;haven_labelled&quot; &quot;vctrs_vctr&quot;     &quot;double&quot;        
## 
## $labels
## uninjured   injured 
##         0         1</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb78-1" title="1"><span class="co"># You can also use var_label() and get_labels() too, but attributes() shows both types of labels</span></a></code></pre></div>
<div style="margin-bottom:50px;">

</div>
<p>The output in the console show that uninjured is labelled ‘0’ and injured is labelled ‘1’. Maybe, though, you do not like the labels that are attached to the variable values. Perhaps they do not make sense or they do not help you to understand better what this variable measures. If so, we can remove and change the labels.</p>
<div style="margin-bottom:70px;">

</div>
<hr />
<div id="activity-6-removing-labels" class="section level4">
<h4><span class="header-section-number">2.3.2.1</span> Activity 6: Removing labels</h4>
<p>Let us return to the <code>injured</code> variable from the <code>ncvs</code> dataframe. We, again, are going to make a duplicate variable of <code>injured</code> to learn how to remove and add labels. We do this because it is good practice to leave your original variables alone in case you need to go back to them.</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1"><span class="co"># Make a new variable that is a duplicate of the original one, but naming it ‘injured_no_labels’</span></a>
<a class="sourceLine" id="cb79-2" title="2">ncvs<span class="op">$</span>injured_no_labels &lt;-<span class="st"> </span>ncvs<span class="op">$</span>injured</a>
<a class="sourceLine" id="cb79-3" title="3"></a>
<a class="sourceLine" id="cb79-4" title="4"><span class="kw">attributes</span>(ncvs<span class="op">$</span>injured_no_labels)</a></code></pre></div>
<pre><code>## $label
## [1] &quot;Victim Sustained Injuries During Vicitmization&quot;
## 
## $format.spss
## [1] &quot;F8.2&quot;
## 
## $display_width
## [1] 10
## 
## $class
## [1] &quot;haven_labelled&quot; &quot;vctrs_vctr&quot;     &quot;double&quot;        
## 
## $labels
## uninjured   injured 
##         0         1</code></pre>
<div style="margin-bottom:50px;">

</div>
<p>To remove labels, we will need to load two new packages: <code>labelled</code> and <code>sjlabelled</code>. Can you do that?</p>
<div style="margin-bottom:35px;">

</div>
<div style="margin-bottom:50px;">

</div>
<p>After loading the two new packages, we remove variable and value labels:</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb81-1" title="1"><span class="co"># Remove variable labels </span></a>
<a class="sourceLine" id="cb81-2" title="2">ncvs<span class="op">$</span>injured_no_labels &lt;-<span class="st"> </span><span class="kw">remove_var_label</span>(ncvs<span class="op">$</span>injured_no_labels) </a>
<a class="sourceLine" id="cb81-3" title="3"></a>
<a class="sourceLine" id="cb81-4" title="4"><span class="co"># Check that they were removed </span></a>
<a class="sourceLine" id="cb81-5" title="5"><span class="kw">var_label</span>(ncvs<span class="op">$</span>injured_no_labels)</a></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb83-1" title="1"><span class="co"># Remove value labels </span></a>
<a class="sourceLine" id="cb83-2" title="2">ncvs<span class="op">$</span>injured_no_labels &lt;-<span class="st"> </span><span class="kw">remove_labels</span>(ncvs<span class="op">$</span>injured_no_labels, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>))  </a>
<a class="sourceLine" id="cb83-3" title="3"></a>
<a class="sourceLine" id="cb83-4" title="4"><span class="co"># Check that they were removed </span></a>
<a class="sourceLine" id="cb83-5" title="5"><span class="kw">get_labels</span>(ncvs<span class="op">$</span>injured_no_labels)</a></code></pre></div>
<pre><code>## NULL</code></pre>
<div style="margin-bottom:50px;">

</div>
Now to add a label:
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" title="1"><span class="co"># Add variable label </span></a>
<a class="sourceLine" id="cb85-2" title="2"><span class="kw">var_label</span>(ncvs<span class="op">$</span>injured_no_labels) &lt;-<span class="st"> &quot;Whether Victim Sustained Injured&quot;</span> </a>
<a class="sourceLine" id="cb85-3" title="3"></a>
<a class="sourceLine" id="cb85-4" title="4"><span class="co"># Check that they were added </span></a>
<a class="sourceLine" id="cb85-5" title="5"><span class="kw">var_label</span>(ncvs<span class="op">$</span>injured_no_labels)</a></code></pre></div>
<pre><code>## [1] &quot;Whether Victim Sustained Injured&quot;</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" title="1"><span class="co"># Add variable label </span></a>
<a class="sourceLine" id="cb87-2" title="2">ncvs<span class="op">$</span>injured_no_labels &lt;-<span class="kw">add_labels</span>(ncvs<span class="op">$</span>injured_no_labels, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">`</span><span class="dt">uninjured</span><span class="st">`</span> =<span class="st"> </span><span class="dv">0</span>, <span class="st">`</span><span class="dt">injured</span><span class="st">`</span> =<span class="st"> </span><span class="dv">1</span>)) </a>
<a class="sourceLine" id="cb87-3" title="3"></a>
<a class="sourceLine" id="cb87-4" title="4"><span class="co"># Check that they were added </span></a>
<a class="sourceLine" id="cb87-5" title="5"><span class="kw">get_labels</span>(ncvs<span class="op">$</span>injured_no_labels)</a></code></pre></div>
<pre><code>## [1] &quot;uninjured&quot; &quot;injured&quot;</code></pre>
<div style="margin-bottom:50px;">

</div>
<p>Nothing to add in the googledoc this time, so onto the next activity.</p>
<div style="margin-bottom:70px;">

</div>
<hr />
</div>
<div id="activity-7-subsetting" class="section level4">
<h4><span class="header-section-number">2.3.2.2</span> Activity 7: Subsetting</h4>
<p>Through <code>tidyverse</code> functions, we can subset our data frames or vectors based on some criteria. Using the function <code>select()</code>, we can subset variables by number or name:</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb89-1" title="1"><span class="co"># Using select () to subset by two variables</span></a>
<a class="sourceLine" id="cb89-2" title="2">ncvs_Df &lt;-<span class="st"> </span>ncvs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>) </a></code></pre></div>
<div style="margin-bottom:50px;">

</div>
<p>Using the function <code>slice()</code>, we can subset rows by number, and combine it with <code>select()</code>. For example:</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb90-1" title="1"><span class="co"># Get the first two rows </span></a>
<a class="sourceLine" id="cb90-2" title="2">firstTwoRowsOfncvs &lt;-<span class="st"> </span>ncvs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>) </a>
<a class="sourceLine" id="cb90-3" title="3"></a>
<a class="sourceLine" id="cb90-4" title="4"><span class="co"># Combine with above function to get the first two variables, and first two rows </span></a>
<a class="sourceLine" id="cb90-5" title="5">firstTwoRowsCols &lt;-<span class="st"> </span>ncvs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">select</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">slice</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>)</a></code></pre></div>
<div style="margin-bottom:50px;">

</div>
<p>Use the <code>filter()</code> function to subset observations (i.e., rows) based on conditions. For example, we only want those for which the <code>injured</code> variable was equal to 1, so we run:</p>
<div style="margin-bottom:35px;">

</div>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb91-1" title="1">OnlyInjured &lt;-<span class="st"> </span>ncvs <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">filter</span>(injured <span class="op">==</span><span class="st"> </span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb91-2" title="2"></a>
<a class="sourceLine" id="cb91-3" title="3"><span class="co">#These filters can be combined using conditions ‘&amp;’ and ‘|’ to produce data similar to the one from the variable &#39;notstranger&#39; except we call this subset of the dataframe &#39;KnewOfandInjured&#39;:</span></a>
<a class="sourceLine" id="cb91-4" title="4">KnewOfandInjured &lt;-<span class="st"> </span>ncvs <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb91-5" title="5"><span class="kw">filter</span>(relationship <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span> <span class="op">&amp;</span><span class="st"> </span>injured <span class="op">==</span><span class="st"> </span><span class="dv">1</span>)</a></code></pre></div>
<div style="margin-bottom:50px;">

</div>
<p>Say if we wanted the first five rows of <code>KnewOfandInjured</code>. How would we do that? In your group googledoc, type out the code you think will help you create a (sub-)subset <code>KnewOfandInjured</code> of its first five rows. Call this new subset ‘injuredfiveknew’.</p>
<!-- injuredfiveknew <- KnewOfandInjured %>% slice(1:5) -->
<hr />
<div style="margin-bottom:70px;">

</div>
</div>
<div id="activity-8-subsetting-the-sequel" class="section level4">
<h4><span class="header-section-number">2.3.2.3</span> Activity 8: Subsetting, the Sequel</h4>
<p>We now have a subset called <code>injuredfiveknew</code>. Say we only want to keep the variables <code>V3014</code> (age) and <code>V3018</code> (sex). How would you make an object that only contains these two variables from <code>injuredfiveknew</code>?
Recall that you would need to use the function <code>select()</code>to select variables. But in this example, instead of inserting ‘:’ like in the previous code, you would need to insert a ‘,’. Understanding what ‘:’ means and viewing the order of the variables in <code>injuredfiveknew</code> will give you insight into why.</p>
<p>In your group googledoc sheet, write out the code that you would use to do so. Name this new object that contains the two variables <code>five_ageandincome</code></p>
<!-- five_ageandincome <- injuredfiveknew %>% select(4,6)-->
<hr />
<div style="margin-bottom:50px;">

</div>
</div>
</div>
</div>
<div id="summary-1" class="section level2">
<h2><span class="header-section-number">2.4</span> SUMMARY</h2>
<div style="margin-bottom:30px;">

</div>
<p>Today you were further introduced to <strong>tidyverse</strong> packages that helped you to tidy your data. First, we learned to put our work into a <strong>project</strong> and then how to import data using a package called <code>haven</code>. Whenever we specify a data frame, we learned a nifty short-cut: the <strong>pipe operator</strong> - <code>%&gt;%</code> - which allows us to specify the data frame only once when we code.</p>
<p>Our three main topics today had to do with helping us tidy. One were the variables themselves where we learned about the <strong>factor</strong> and <strong>numeric</strong> classes, and how to make and <strong>recode</strong> new variables. Two, we learned how to remove and add variable and value labels so that we can understand what our variables are measuring. Three, we then learned to subset our data, whereby we make new dataframes that include only the columns – variables – or rows – cases – we want. We tidied our data using the TIDYVERSE WAY!</p>
<div style="margin-bottom:50px;">

</div>
<p>And of course: don’t forget to do your homework!</p>
<div style="margin-bottom:500px;">

</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="a-first-lesson-about-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-visualization.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/02-know-your-data.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Modelling-Crime-Data-2021.pdf", "Modelling-Crime-Data-2021.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
