<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Regression | CRIM20452 Modelling Criminological Data</title>
  <meta name="description" content="This is a companion workbook for the 2nd year undergraduate module CRIM20452 Modelling Criminological Data at the University of Manchester" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Regression | CRIM20452 Modelling Criminological Data" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a companion workbook for the 2nd year undergraduate module CRIM20452 Modelling Criminological Data at the University of Manchester" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Regression | CRIM20452 Modelling Criminological Data" />
  
  <meta name="twitter:description" content="This is a companion workbook for the 2nd year undergraduate module CRIM20452 Modelling Criminological Data at the University of Manchester" />
  

<meta name="author" content="Laura Bui &amp; Reka Solymosi" />


<meta name="date" content="2021-02-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="strength-of-relationships.html"/>

<script src="libs/header-attrs-2.7.2/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelling Criminological Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html"><i class="fa fa-check"></i><b>1</b> A First Lesson About R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#install-r-r-studio"><i class="fa fa-check"></i><b>1.1</b> Install R &amp; R Studio</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#activity-1-identifying-your-operating-system"><i class="fa fa-check"></i><b>1.1.1</b> Activity 1: Identifying your operating system</a></li>
<li class="chapter" data-level="1.1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#activity-2-install-r-r-studio"><i class="fa fa-check"></i><b>1.1.2</b> Activity 2: Install R &amp; R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#getting-to-know-r-studio"><i class="fa fa-check"></i><b>1.2</b> Getting to know R Studio</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#the-four-panes-of-r-studio"><i class="fa fa-check"></i><b>1.2.1</b> The four panes of R Studio</a></li>
<li class="chapter" data-level="1.2.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#customising-r-studio"><i class="fa fa-check"></i><b>1.2.2</b> Customising R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#todays-3-topics"><i class="fa fa-check"></i><b>1.3</b> Today’s 3 (TOPICS)</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#operators-and-functions"><i class="fa fa-check"></i><b>1.3.1</b> Operators and Functions</a></li>
<li class="chapter" data-level="1.3.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#objects"><i class="fa fa-check"></i><b>1.3.2</b> Objects</a></li>
<li class="chapter" data-level="1.3.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#packages-1"><i class="fa fa-check"></i><b>1.3.3</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#summary"><i class="fa fa-check"></i><b>1.4</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html"><i class="fa fa-check"></i><b>2</b> Getting to know your data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#the-tidyverse"><i class="fa fa-check"></i><b>2.1</b> The Tidyverse</a></li>
<li class="chapter" data-level="2.2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#r-projects-getting-your-work-files-organised"><i class="fa fa-check"></i><b>2.2</b> R Projects – Getting Your Work Files Organised</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#activity-1-making-yourself-a-project"><i class="fa fa-check"></i><b>2.2.1</b> Activity 1: Making yourself a project</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#importing-data"><i class="fa fa-check"></i><b>2.3</b> Importing Data</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#activity-2-importing-and-viewing-data"><i class="fa fa-check"></i><b>2.3.1</b> Activity 2: Importing and Viewing Data</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#todays-3-topics-1"><i class="fa fa-check"></i><b>2.4</b> Today’s 3 (TOPICS)</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#variables"><i class="fa fa-check"></i><b>2.4.1</b> Variables</a></li>
<li class="chapter" data-level="2.4.2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#labels"><i class="fa fa-check"></i><b>2.4.2</b> Labels</a></li>
<li class="chapter" data-level="2.4.3" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#subsetting"><i class="fa fa-check"></i><b>2.4.3</b> Subsetting</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#summary-1"><i class="fa fa-check"></i><b>2.5</b> SUMMARY</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#answers-to-activities-if-applicable"><i class="fa fa-check"></i><b>2.5.1</b> Answers to activities (if applicable)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>3</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-visualization.html"><a href="data-visualization.html#grammar-of-graphics"><i class="fa fa-check"></i><b>3.1</b> Grammar of Graphics</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-visualization.html"><a href="data-visualization.html#activity-1-getting-ready"><i class="fa fa-check"></i><b>3.1.1</b> Activity 1: Getting Ready</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-visualization.html"><a href="data-visualization.html#ggplot2"><i class="fa fa-check"></i><b>3.2</b> ggplot2</a></li>
<li class="chapter" data-level="3.3" data-path="data-visualization.html"><a href="data-visualization.html#todays-3"><i class="fa fa-check"></i><b>3.3</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-visualization.html"><a href="data-visualization.html#layers"><i class="fa fa-check"></i><b>3.3.1</b> Layers</a></li>
<li class="chapter" data-level="3.3.2" data-path="data-visualization.html"><a href="data-visualization.html#graphs-for-categorical-data"><i class="fa fa-check"></i><b>3.3.2</b> Graphs for Categorical Data</a></li>
<li class="chapter" data-level="3.3.3" data-path="data-visualization.html"><a href="data-visualization.html#graphs-for-numeric-data"><i class="fa fa-check"></i><b>3.3.3</b> Graphs for Numeric Data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-visualization.html"><a href="data-visualization.html#summary-2"><i class="fa fa-check"></i><b>3.4</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>4</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="4.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#revisiting-descriptive-statistics"><i class="fa fa-check"></i><b>4.1</b> Revisiting Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#activity-1-our-preparation-routine"><i class="fa fa-check"></i><b>4.1.1</b> Activity 1: Our preparation routine</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#todays-3-1"><i class="fa fa-check"></i><b>4.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#central-tendency"><i class="fa fa-check"></i><b>4.2.1</b> Central Tendency</a></li>
<li class="chapter" data-level="4.2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#outliers"><i class="fa fa-check"></i><b>4.2.2</b> Outliers</a></li>
<li class="chapter" data-level="4.2.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#measures-of-dispersion"><i class="fa fa-check"></i><b>4.2.3</b> Measures of Dispersion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="yes-it-does-match.html"><a href="yes-it-does-match.html"><i class="fa fa-check"></i><b>5</b> Yes, it does match!</a>
<ul>
<li class="chapter" data-level="5.1" data-path="yes-it-does-match.html"><a href="yes-it-does-match.html#summary-3"><i class="fa fa-check"></i><b>5.1</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="inferential-statistics.html"><a href="inferential-statistics.html"><i class="fa fa-check"></i><b>6</b> Inferential Statistics</a>
<ul>
<li class="chapter" data-level="6.1" data-path="inferential-statistics.html"><a href="inferential-statistics.html#generalising-about-the-world-from-data"><i class="fa fa-check"></i><b>6.1</b> Generalising About the World from Data</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="inferential-statistics.html"><a href="inferential-statistics.html#activity-1-our-preparation-routine-1"><i class="fa fa-check"></i><b>6.1.1</b> Activity 1: Our preparation routine</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="inferential-statistics.html"><a href="inferential-statistics.html#todays-3-2"><i class="fa fa-check"></i><b>6.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="inferential-statistics.html"><a href="inferential-statistics.html#samples"><i class="fa fa-check"></i><b>6.2.1</b> Samples</a></li>
<li class="chapter" data-level="6.2.2" data-path="inferential-statistics.html"><a href="inferential-statistics.html#standard-errors"><i class="fa fa-check"></i><b>6.2.2</b> Standard Errors</a></li>
<li class="chapter" data-level="6.2.3" data-path="inferential-statistics.html"><a href="inferential-statistics.html#confidence-intervals"><i class="fa fa-check"></i><b>6.2.3</b> Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="inferential-statistics.html"><a href="inferential-statistics.html#summary-4"><i class="fa fa-check"></i><b>6.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="hypotheses.html"><a href="hypotheses.html"><i class="fa fa-check"></i><b>7</b> Hypotheses</a>
<ul>
<li class="chapter" data-level="7.1" data-path="hypotheses.html"><a href="hypotheses.html#hypothesis-testing"><i class="fa fa-check"></i><b>7.1</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="7.2" data-path="hypotheses.html"><a href="hypotheses.html#todays-3-3"><i class="fa fa-check"></i><b>7.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="hypotheses.html"><a href="hypotheses.html#statistical-significance"><i class="fa fa-check"></i><b>7.2.1</b> Statistical Significance</a></li>
<li class="chapter" data-level="7.2.2" data-path="hypotheses.html"><a href="hypotheses.html#a-binomial-test"><i class="fa fa-check"></i><b>7.2.2</b> A Binomial Test</a></li>
<li class="chapter" data-level="7.2.3" data-path="hypotheses.html"><a href="hypotheses.html#single-sample-significance-tests"><i class="fa fa-check"></i><b>7.2.3</b> Single-sample significance tests</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="hypotheses.html"><a href="hypotheses.html#summary-5"><i class="fa fa-check"></i><b>7.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html"><i class="fa fa-check"></i><b>8</b> Relationships with Categorical Variables</a>
<ul>
<li class="chapter" data-level="8.1" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#associating-with-categorical-variables"><i class="fa fa-check"></i><b>8.1</b> Associating with Categorical Variables</a></li>
<li class="chapter" data-level="8.2" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#todays-3-4"><i class="fa fa-check"></i><b>8.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#independent-and-dependent-variables"><i class="fa fa-check"></i><b>8.2.1</b> Independent and Dependent Variables</a></li>
<li class="chapter" data-level="8.2.2" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#the-t-test"><i class="fa fa-check"></i><b>8.2.2</b> The T-Test</a></li>
<li class="chapter" data-level="8.2.3" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#chi-square"><i class="fa fa-check"></i><b>8.2.3</b> Chi-square</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#summary-6"><i class="fa fa-check"></i><b>8.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html"><i class="fa fa-check"></i><b>9</b> Strength of Relationships</a>
<ul>
<li class="chapter" data-level="9.1" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#measures-of-association"><i class="fa fa-check"></i><b>9.1</b> Measures of Association</a></li>
<li class="chapter" data-level="9.2" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#todays-3-5"><i class="fa fa-check"></i><b>9.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#between-categorical-nominal-variables"><i class="fa fa-check"></i><b>9.2.1</b> Between Categorical, Nominal Variables</a></li>
<li class="chapter" data-level="9.2.2" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#between-categorical-ordinal-variables"><i class="fa fa-check"></i><b>9.2.2</b> Between Categorical, Ordinal Variables</a></li>
<li class="chapter" data-level="9.2.3" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#between-numeric-variables"><i class="fa fa-check"></i><b>9.2.3</b> Between Numeric Variables</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#summary-7"><i class="fa fa-check"></i><b>9.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>10</b> Regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="regression.html"><a href="regression.html#multiple-and-simultaneous-relationships"><i class="fa fa-check"></i><b>10.1</b> Multiple and Simultaneous Relationships</a></li>
<li class="chapter" data-level="10.2" data-path="regression.html"><a href="regression.html#todays-3-6"><i class="fa fa-check"></i><b>10.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="regression.html"><a href="regression.html#assumptions-of-ols-regression"><i class="fa fa-check"></i><b>10.2.1</b> Assumptions of OLS Regression</a></li>
<li class="chapter" data-level="10.2.2" data-path="regression.html"><a href="regression.html#interpreting-ols-regression"><i class="fa fa-check"></i><b>10.2.2</b> Interpreting OLS Regression</a></li>
<li class="chapter" data-level="10.2.3" data-path="regression.html"><a href="regression.html#logistic-regression"><i class="fa fa-check"></i><b>10.2.3</b> Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="regression.html"><a href="regression.html#summary-8"><i class="fa fa-check"></i><b>10.3</b> SUMMARY</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">CRIM20452 Modelling Criminological Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression" class="section level1" number="10">
<h1><span class="header-section-number">Chapter 10</span> Regression</h1>
<div id="ols-logistic-regressions" class="section level4 unnumbered">
<h4><em>OLS &amp; Logistic Regressions</em></h4>
</div>
<div id="learning-outcomes-8" class="section level4 unnumbered">
<h4>Learning Outcomes:</h4>
<ul>
<li>Learn how and when to use ordinary least squares and logistic regressions</li>
<li>Understand what their outputs mean</li>
</ul>
</div>
<div id="todays-learning-tools-8" class="section level4 unnumbered">
<h4>Today’s Learning Tools:</h4>
<div id="data-8" class="section level5 unnumbered">
<h5><em>Data:</em></h5>
<ul>
<li>Crime Survey for England and Wales (CSEW) from 2013 to 2014 sweep teaching dataset</li>
<li><code>Arrests</code> from the <code>effects</code> package</li>
</ul>
</div>
<div id="packages-9" class="section level5 unnumbered">
<h5><em>Packages:</em></h5>
<ul>
<li><code>arm</code></li>
<li><code>car</code></li>
<li><code>effects</code></li>
<li><code>ggplot2</code></li>
<li><code>here</code></li>
<li><code>lessR</code></li>
<li><code>sjplot</code></li>
<li><code>tidyverse</code></li>
</ul>
</div>
<div id="functions-introduced-and-packages-to-which-they-belong-8" class="section level5 unnumbered">
<h5><em>Functions introduced (and packages to which they belong)</em></h5>
<ul>
<li><code>complete.cases()</code> : Returns only complete cases that do not have NAs (<code>base R</code>)</li>
<li><code>display()</code> : Gives a clean printout of lm, glm, and other such objects (<code>arm</code>)</li>
<li><code>lm()</code> : Fit linear models (<code>base R</code>)</li>
<li><code>Logit()</code> : Fit logistic regression models with less typing (<code>lessR</code>)</li>
<li><code>qplot()</code> : Creates a variety of plots/graphs (<code>base R</code>)</li>
<li><code>relevel()</code> : Reorders the levels of a factor (<code>base R</code>)</li>
<li><code>tab_model()</code> : Creates HTML tables summarising regression models (<code>sjplot</code>)</li>
<li><code>vif()</code> : Calculate the variance inflation for OLS or other linear models (<code>car</code>)</li>
</ul>
<hr />
</div>
</div>
<div id="multiple-and-simultaneous-relationships" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> Multiple and Simultaneous Relationships</h2>
<p>Our learning on inferential statistics, so far, has been on single relationships between two variables. One of the major drawbacks of previous analyses of single relationships is that, even though you are able to test for statistical significance, you cannot ascertain prediction very well. In other words, you were unable to say for certain that one variable predicted another variable; we merely could say ‘there was a relationship’ or ‘there was no relationship.’</p>
<p>Although we got into the habit of arranging our variables as independent and dependent variables, these terms are more relevant to regression. The reason is, not only can we establish significant relationships, we also can say with relatively more clarity, how that relationship looks like – which variable is impacting on what other variable.</p>
<p>Another major drawback of previous analyses on bivariate relationships is that you are less certain about whether the relationship and its effect size would still hold in the face of other variables. For example, would a significant relationship between peer group and violence still exist when the relationship between unemployment and violence is considered? This last lesson is on analyses that establish predictive relationships and test multiple relationships between two variables at the same time.</p>
<hr />
</div>
<div id="todays-3-6" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> Today’s 3</h2>
<p>Our main topic of the day is <strong>regression</strong> and we learn two forms: ordinary least squares (OLS) and logistic. The former is applied to dependent variables that are measured at interval or numeric level, while the latter is applied to dependent variables that are binary and measured at the nominal level. The three topics are: assumptions of OLS regression; interpreting OLS regression; and logistic regression.</p>
<hr />
<div id="assumptions-of-ols-regression" class="section level3" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Assumptions of OLS Regression</h3>
<p><strong>Ordinary least squares (OLS)</strong> regression is a popular technique used to explore whether one or multiple independent variables (X) can predict or explain the variation in the dependent variable (Y). When multiple independent variables are included simultaneously, they are called <strong>covariates</strong>; when only one independent variable is used, the OLS regression is called <strong>bivariate regression</strong>. OLS regression has been the mainstay analysis in the social sciences.</p>
<p>To begin, we do the following:</p>
<ol style="list-style-type: decimal">
<li><p>Open up your existing <code>R</code> project</p></li>
<li><p>Install and load the required packages shown above</p></li>
<li><p>Import the dataset ‘csew1314_teaching.csv’, using the <code>read_csv()</code> function</p></li>
<li><p>Name the data frame <code>df</code></p></li>
</ol>
<p>For our example, we are interested in the bivariate relationship between age (X) and perception of antisocial behaviour (Y). Our research question is: ‘Does age predict perceived level of antisocial behaviour in one’s neighbourhood?’ Our null and alternative hypotheses are as follows:</p>
<p><span class="math inline">\(H_0\)</span>: Age does not predict perceived level of antisocial behaviour in one’s neighbourhood.</p>
<p><span class="math inline">\(H_A\)</span>: Age predicts perceived level of antisocial behaviour in one’s neighbourhood.</p>
<p>Our initial step is to get to know our data:</p>
<div class="sourceCode" id="cb420"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb420-1"><a href="regression.html#cb420-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Age variable</span></span>
<span id="cb420-2"><a href="regression.html#cb420-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>age)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   16.00   36.00   51.00   51.19   66.00   99.00     118</code></pre>
<div class="sourceCode" id="cb422"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb422-1"><a href="regression.html#cb422-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Antisocial variable</span></span>
<span id="cb422-2"><a href="regression.html#cb422-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>antisocx)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##  -4.015  -0.559   0.177   0.000   0.788   1.215   26695</code></pre>
<p>Both variables have missing data. You could ignore the ‘NAs’, but when we run regression, it will conduct a <em>listwise deletion</em>, which is when cases are dropped from your analysis if they have missing data on either the independent variable (IV) or the dependent variable (DV). As we now want descriptive statistics of cases we will be using, we will delete the cases that will be dropped anyway. We use the <code>complete.cases ()</code> function to keep cases that have valid responses in both the IV and DV:</p>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="regression.html#cb424-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Start with 35,371 cases</span></span>
<span id="cb424-2"><a href="regression.html#cb424-2" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df) </span></code></pre></div>
<pre><code>## [1] 35371</code></pre>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="regression.html#cb426-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retain only complete cases</span></span>
<span id="cb426-2"><a href="regression.html#cb426-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df[(<span class="fu">complete.cases</span>(df<span class="sc">$</span>age) <span class="sc">&amp;</span> <span class="fu">complete.cases</span>(df<span class="sc">$</span>antisocx)), ]</span>
<span id="cb426-3"><a href="regression.html#cb426-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb426-4"><a href="regression.html#cb426-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Left with 8,650 cases after dropping NAs</span></span>
<span id="cb426-5"><a href="regression.html#cb426-5" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(df) </span></code></pre></div>
<pre><code>## [1] 8650</code></pre>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="regression.html#cb428-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summaries of just the 8,650 cases </span></span>
<span id="cb428-2"><a href="regression.html#cb428-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>age)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   16.00   36.00   50.00   50.82   66.00   98.00</code></pre>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="regression.html#cb430-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df<span class="sc">$</span>antisocx)</span></code></pre></div>
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
## -4.014557 -0.552077  0.178767  0.001823  0.788219  1.215267</code></pre>
<p>To conduct OLS regression, or linear regression for short, a number of assumptions must be met, so you will need to test for them. Failure to do so will result in a possibly incorrect model and drawing conclusions from it would be silly. We only, however, briefly go through the first four assumptions because going into detail is beyond the scope of this class.</p>
<p>The purpose of today is more to introduce you to regression and learn how to use it and interpret the output. For this class, we find that the assumption of linearity is important to go into detail. Going through this assumption in detail will give you a better understanding of OLS regression itself and how it operates. We now go through each of the five assumptions of OLS regression before using the technique.</p>
<hr />
<div id="independence-of-errors" class="section level4" number="10.2.1.1">
<h4><span class="header-section-number">10.2.1.1</span> Independence of errors</h4>
<p>Errors of the prediction, which make up the regression line, are assumed to be independent of each other. The term <em>heteroscedasticity</em> is used to describe this violation of independence of errors. When we violate this assumption, our points in the scatterplot resemble the shape of a funnel. If there is dependency between the observations, you would need to use other models that are not covered in this course.</p>
</div>
<div id="equal-variances-of-errors" class="section level4" number="10.2.1.2">
<h4><span class="header-section-number">10.2.1.2</span> Equal Variances of errors</h4>
<p>If the variance of our residuals is unequal, we will need different estimation methods, but this issue is minor. The reason it is a minor issue is that regression is considered a <em>robust</em> estimation, meaning that it is not too sensitive to changes in the variance.</p>
</div>
<div id="normality-of-errors" class="section level4" number="10.2.1.3">
<h4><span class="header-section-number">10.2.1.3</span> Normality of errors</h4>
<p>Residuals are assumed to be normally distributed. Gelman and Hill (2007) believe this to be the least important of the assumptions because regression inferences tend to be robust regarding non-normality of the errors. Your results, however, may be sensitive to large outliers so you will need to drop them if appropriate.</p>
</div>
<div id="multicollinearity" class="section level4" number="10.2.1.4">
<h4><span class="header-section-number">10.2.1.4</span> Multicollinearity</h4>
<p>When you are including more than one IV, <strong>multicollinearity</strong> may be a concern. Independent variables that are highly correlated with each other mean that they are tapping into the same construct. For example, if you include two IVs, parental attachment and parental discipline, you may find that they are highly related to each other because both measure a similar idea.</p>
<p>One indication is that if you run a Pearson’s correlation for the two IVs and get a value of 0.6 or 0.7, you should start investigating further. Another way to check for multicollinearity is through the <em>variance inflation factor</em> (VIF). How high the VIF should be before multicollinearity is a concern is debatable: here, anything above 5 should be a matter of concern. With this analysis, IVs should be numeric. We include an additional covariate, confidence in the police (<code>confx</code>), to illustrate. The VIF for our variables is conducted with the <code>vif ()</code> function in the <code>car</code> package:</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="regression.html#cb432-1" aria-hidden="true" tabindex="-1"></a>cal_vif <span class="ot">&lt;-</span> <span class="fu">lm</span>(antisocx <span class="sc">~</span> age <span class="sc">+</span> confx, <span class="at">data =</span> df) </span>
<span id="cb432-2"><a href="regression.html#cb432-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb432-3"><a href="regression.html#cb432-3" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(cal_vif)</span></code></pre></div>
<pre><code>##      age    confx 
## 1.003988 1.003988</code></pre>
<p>The VIF values are below 5 and indicate that including both variables, <code>age</code> and <code>confx</code>, in the same model does not pose any multicollinearity concerns.</p>
</div>
<div id="linearity" class="section level4" number="10.2.1.5">
<h4><span class="header-section-number">10.2.1.5</span> Linearity</h4>
<p>Similar to Pearson’s correlation, a linear relationship must be established before conducting the analysis. If the relationship is non-linear, your predicted values will be wrong, and it will systematically miss the true pattern of the mean of Y.</p>
<p>Say, for example, you randomly drew a case from the dataset. What would be your best guess on the value of that case’s perceived antisocial behaviour in the neighbourhood (<code>antisocx</code>)? Likely, you say a value near the mean (M = 0.001823) of the sample. Next, we visualise our variable distributions:</p>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="regression.html#cb434-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(<span class="at">x =</span> age, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="09-regression_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="regression.html#cb436-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qplot</span>(<span class="at">x =</span> antisocx, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="09-regression_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="regression.html#cb438-1" aria-hidden="true" tabindex="-1"></a><span class="co"># antisocx is negatively skewed</span></span>
<span id="cb438-2"><a href="regression.html#cb438-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb438-3"><a href="regression.html#cb438-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking out how the variables covary together</span></span>
<span id="cb438-4"><a href="regression.html#cb438-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> antisocx)) <span class="sc">+</span> </span>
<span id="cb438-5"><a href="regression.html#cb438-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span>.<span class="dv">2</span>, <span class="at">position=</span><span class="st">&quot;jitter&quot;</span>)</span></code></pre></div>
<p><img src="09-regression_files/figure-html/unnamed-chunk-6-3.png" width="672" /></p>
<p>If you were to guess that case’s perceived level of antisocial behaviour in the neighbourhood, but now based it on the scatterplot, and learned they were aged 30, what would your answer now be? Before, we based our guess on descriptive measures of central tendency and dispersion, which included all ages. Now, we are asked to guess knowing that the person is aged 30. If we were to now guess the level of perceived antisocial behaviour, we would try and guess the mean of those who are also aged 30. This is what is known as the <em>conditional mean</em> – the mean of Y for each value of X.</p>
<p>We create a trend line through the scatterplot, which represents the mean of the variable on the y-axis, <code>antisocx</code>, and we want the means computed for each age:</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="regression.html#cb439-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb439-2"><a href="regression.html#cb439-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>df, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> antisocx), <span class="at">alpha=</span>.<span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb439-3"><a href="regression.html#cb439-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data=</span>df, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> antisocx), <span class="at">stat=</span><span class="st">&#39;summary&#39;</span>, <span class="at">fun.y=</span>mean,</span>
<span id="cb439-4"><a href="regression.html#cb439-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">color=</span><span class="st">&quot;blue&quot;</span>, <span class="at">size=</span><span class="dv">1</span>)  </span></code></pre></div>
<pre><code>## No summary function supplied, defaulting to `mean_se()`</code></pre>
<p><img src="09-regression_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Plotting the conditional means shows us that the mean of perceived antisocial behaviour for those respondents around the age of 30 is around −0.3. This would be a better guess than the mean for all ages, 0.0018. The trend line gives us a better idea of what is going on in our scatterplot, but the line looks a bit rough. We can make it smoother:</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="regression.html#cb441-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make smoother by calculating average perceived antisocial behaviour for age in increments of 5 years</span></span>
<span id="cb441-2"><a href="regression.html#cb441-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb441-3"><a href="regression.html#cb441-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data=</span>df, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> antisocx), <span class="at">alpha=</span>.<span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb441-4"><a href="regression.html#cb441-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data=</span>df, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">round</span>(age<span class="sc">/</span><span class="dv">5</span>)<span class="sc">*</span><span class="dv">5</span>, <span class="at">y =</span> antisocx), <span class="at">stat=</span><span class="st">&#39;summary&#39;</span>, <span class="at">fun.y=</span>mean,</span>
<span id="cb441-5"><a href="regression.html#cb441-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">color=</span><span class="st">&quot;blue&quot;</span>, <span class="at">size=</span><span class="dv">1</span>)</span></code></pre></div>
<pre><code>## No summary function supplied, defaulting to `mean_se()`</code></pre>
<p><img src="09-regression_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The blue trend line shows us that there is an upward trend, meaning that as age increases, so do perceptions of antisocial behaviour in the neighbourhood. Like what we did above, OLS regression tries to capture the trend or pattern of the data by drawing a straight line of predicted values as the model of the data:</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="regression.html#cb443-1" aria-hidden="true" tabindex="-1"></a><span class="co"># method=lm asks for the linear regression line </span></span>
<span id="cb443-2"><a href="regression.html#cb443-2" aria-hidden="true" tabindex="-1"></a><span class="co"># se=FALSE asks not to print confidence interval </span></span>
<span id="cb443-3"><a href="regression.html#cb443-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Other arguments specify the colour, thickness of the line </span></span>
<span id="cb443-4"><a href="regression.html#cb443-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> df, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> antisocx)) <span class="sc">+</span> </span>
<span id="cb443-5"><a href="regression.html#cb443-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> .<span class="dv">2</span>, <span class="at">position =</span> <span class="st">&quot;jitter&quot;</span>) <span class="sc">+</span> </span>
<span id="cb443-6"><a href="regression.html#cb443-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="09-regression_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The red <strong>regression line</strong> gives you guesses or predictions for the value of perceived level of antisocial behaviour based on information that we have about age. The line can also be seen as one that tries to summarise the pattern of what is going on among points. The line is, of course, linear. It does not go through all the points, however.
As Bock et al. (2012) highlight:</p>
<blockquote>
<p>‘Like all models of the real world, the line will be wrong – wrong in the sense that it can’t match reality exactly. But it can help us understand how the variables are associated’ (p. 179).</p>
</blockquote>
<p>A map is never a perfect representation of the world; the same happens with statistical models. Yet, as with maps, models can be helpful.</p>
<hr />
</div>
</div>
<div id="interpreting-ols-regression" class="section level3" number="10.2.2">
<h3><span class="header-section-number">10.2.2</span> Interpreting OLS Regression</h3>
<p>In this section, we learn how to interpret bivariate and multiple regression output. Now that we know what the regression line is, how do we draw one? Two points are needed to do so:</p>
<ol style="list-style-type: decimal">
<li><p>We need to know where the line begins. The <strong>intercept</strong> is where it begins, which is the value of Y, our DV, when X (our IV) is 0.</p></li>
<li><p>We also need to know the angle of that line. This is referred to as the <strong>slope</strong>.</p></li>
</ol>
<p>This translates into the equation:</p>
<p><span class="math display">\[y = b_0 + b_1x_i\]</span></p>
<p>Where <span class="math inline">\(b_0\)</span> is the y-intercept and <span class="math inline">\(b_1x_i\)</span> is the slope of the line. Linear regression models try to minimise the distance from every point in the scatterplot to the regression line. This is called <em>least squares estimation</em>. The farther these points are from the regression line, the more error your regression model will have.</p>
<p>It is not unusual to observe that some points will fall above the line (a positive error value), while other points will fall below it (a negative error value). If we wanted to sum these error values, the problem is that the positive values would cancel out the negative values, underreporting our overall error. This would then incorrectly suggest that our regression line was perfect.</p>
<p>To resolve this issue, the error values are squared before they are summed. This is called the <em>error sum of squares</em>. Our regression model is trying to find a line fit that has the least (squared) error. Hence, least squared estimation.</p>
<hr />
<div id="bivariate-regression" class="section level4" number="10.2.2.1">
<h4><span class="header-section-number">10.2.2.1</span> Bivariate Regression</h4>
<p>To fit the model, we use the <code>lm()</code> function using the formula specification <code>(Y ~ X)</code>:</p>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="regression.html#cb445-1" aria-hidden="true" tabindex="-1"></a>fit_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(antisocx <span class="sc">~</span> age, <span class="at">data =</span> df)</span>
<span id="cb445-2"><a href="regression.html#cb445-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb445-3"><a href="regression.html#cb445-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Get to know the data</span></span>
<span id="cb445-4"><a href="regression.html#cb445-4" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(fit_1)</span></code></pre></div>
<pre><code>## [1] &quot;lm&quot;</code></pre>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="regression.html#cb447-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(fit_1)</span></code></pre></div>
<pre><code>## $names
##  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;       &quot;rank&quot;         
##  [5] &quot;fitted.values&quot; &quot;assign&quot;        &quot;qr&quot;            &quot;df.residual&quot;  
##  [9] &quot;xlevels&quot;       &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;        
## 
## $class
## [1] &quot;lm&quot;</code></pre>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="regression.html#cb449-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = antisocx ~ age, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.8481 -0.5752  0.1297  0.7691  1.6581 
## 
## Coefficients:
##              Estimate Std. Error t value            Pr(&gt;|t|)
## (Intercept) -0.647232   0.030455  -21.25 &lt;0.0000000000000002
## age          0.012773   0.000563   22.68 &lt;0.0000000000000002
## 
## Residual standard error: 0.9705 on 8648 degrees of freedom
## Multiple R-squared:  0.05616,    Adjusted R-squared:  0.05606 
## F-statistic: 514.6 on 1 and 8648 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<div class="sourceCode" id="cb451"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb451-1"><a href="regression.html#cb451-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A more concise display of results is using ‘display ()’ from arm package:</span></span>
<span id="cb451-2"><a href="regression.html#cb451-2" aria-hidden="true" tabindex="-1"></a><span class="fu">display</span>(fit_1)</span></code></pre></div>
<pre><code>## lm(formula = antisocx ~ age, data = df)
##             coef.est coef.se
## (Intercept) -0.65     0.03  
## age          0.01     0.00  
## ---
## n = 8650, k = 2
## residual sd = 0.97, R-Squared = 0.06</code></pre>
<p>Now let us interpret the regression output. There are several points to focus on when communicating your results:</p>
<ol style="list-style-type: decimal">
<li><p>Beta (or regression) coefficient: this is the value that measures the impact of the independent variable on the dependent variable. It is the <span class="math inline">\(b_1\)</span> regression coefficient from the previous equation, the value that will shape the slope for this model. From our output, this value is 0.012773. When the value is positive, it tells us that for every 1 unit increase in X, there is a <span class="math inline">\(b_1\)</span> increase on Y; if, however, the coefficient is negative, then it represents a decrease on Y. Here, we interpret the result as: ‘For every 1 year older, there is a 0.01 unit increase in level of perceived antisocial behaviour in the neighbourhood.’ The coefficient can be interpreted as a measure of the effect size of this relationship. In addition, with very large sample sizes, you should place less of an emphasis on p-values and more emphasis on the size of the beta coefficients because p-values are sensitive to sample size. For example, you may have all statistically significant covariates, even though the variables have small coefficients. This means that they do not have much of an effect on the DV.</p></li>
<li><p>P-value: The p-value for each beta coefficient tests the null hypothesis that the coefficient is equal to zero. A low p-value ( &lt; 0.05) means you can reject the null hypothesis and that the changes in the predictor’s value are significantly related to changes in the DV value. For statistically non-significant coefficients, it is not recommended that you interpret them; you can, however, make statements about their general trend (positive or negative). In our output, the p-value is very small ( p &lt; .001). We conclude that age significantly predicts level of perceived antisocial behaviour and that we can reject the null hypothesis.</p></li>
<li><p>F-statistic: There is another p-value at the bottom of your regression output and belongs to the F-statistic. This assesses whether our overall model can predict the DV with high confidence, especially if we have multiple predictors. This, too, is statistically significant, meaning that at least one of our inputs must be related to our DV.</p></li>
<li><p><span class="math inline">\(R^2\)</span>: This is known as the percent of variance explained, and it is a measure of the strength of our model. This value ranges from 0 to 1. Towards 1, the better we are able to account for variation in our outcome Y with our IV(s). In other words, the stronger the relationship is between Y and X. Weisburd and Britt (2009: 437) suggest that, in criminal justice research, values greater than .40 are rare, but if we obtain such a value, it is considered a powerful model. If the value is lower than .20, the model is considered relatively weak. The output shows that <span class="math inline">\(R^2\)</span> for our model was about .06 (the multiple r-squared value). We interpret this as our model explains 6% of the variance in the level of perceived antisocial behaviour.</p></li>
</ol>
<div class="figure">
<img src="Images/residual.jpg" alt="" />
<p class="caption"><strong>Figure 9.1</strong> Residuals visualized</p>
</div>
<p>To understand <span class="math inline">\(R^2\)</span>, we refer to <strong>residuals</strong> (<em>e</em>). These are the distance between each point in the dataset and the regression line. The distance represents the amount of error. Previously, this was mentioned in the context of least squares estimation. Residuals matter because it tells us how much variation is still unexplained and considers the fact that we cannot perfectly predict perceived antisocial behaviour each time by using the information on age. In actuality, our regression equation should be:</p>
<p><span class="math display">\[y = b_0 + b_1x_i + e\]</span></p>
<hr />
</div>
<div id="multiple-regression" class="section level4" number="10.2.2.2">
<h4><span class="header-section-number">10.2.2.2</span> Multiple Regression</h4>
<p>At the start of the session, there was mention of one of the major drawbacks of looking at only bivariate relationships. One was that these analyses did not consider other possible explanations. It could be that you have a statistically significant relationship, but without considering other variables that may explain this relationship, your significant result could, in fact, be <em>spurious</em> – an association that should not be taken very seriously. For some ridiculous examples, click <a href="http://tylervigen.com/spurious-correlations">here</a>.</p>
<p>Multiple regression is a way for assessing the relevance of competing explanations. For example, we think there is a relationship between age and perceived antisocial behaviour levels, but we have not considered whether other reasons may provide a better explanation for these perceptions. Maybe previous victimisation or fear of crime may be better contenders.</p>
<p>The equation for multiple regression is similar to bivariate regression except it includes more coefficients:</p>
<p><span class="math display">\[y = b_0 + b_1x_i + b_2x_{ii} +... b_nx_n + e\]</span></p>
<p>For this example, we include additional variables to our model: sex (<code>sex</code>), previous victimisation in past 12 months (<code>bcsvictim</code>), and confidence in the police (<code>confx</code>). First, we check out these variables and tidy them as necessary. Then we will run our regression:</p>
<div class="sourceCode" id="cb453"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb453-1"><a href="regression.html#cb453-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking out what type of class</span></span>
<span id="cb453-2"><a href="regression.html#cb453-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb453-3"><a href="regression.html#cb453-3" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(df<span class="sc">$</span>confx) </span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb455"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb455-1"><a href="regression.html#cb455-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(df<span class="sc">$</span>bcsvictim)</span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="regression.html#cb457-1" aria-hidden="true" tabindex="-1"></a><span class="co"># attach labels to bcsvictim and make ordering false </span></span>
<span id="cb457-2"><a href="regression.html#cb457-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>bcsvictim <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>bcsvictim, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;not victim&quot;</span>, <span class="st">&quot;Yes victim&quot;</span>), <span class="at">ordered =</span> <span class="cn">FALSE</span>) </span>
<span id="cb457-3"><a href="regression.html#cb457-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb457-4"><a href="regression.html#cb457-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sex</span></span>
<span id="cb457-5"><a href="regression.html#cb457-5" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span> (df<span class="sc">$</span>sex)</span></code></pre></div>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<div class="sourceCode" id="cb459"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb459-1"><a href="regression.html#cb459-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>sex)</span></code></pre></div>
<pre><code>## 
##    1    2 
## 4064 4586</code></pre>
<div class="sourceCode" id="cb461"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb461-1"><a href="regression.html#cb461-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode sex as dummy variable (0 and 1) where female is 0 and ordered is false</span></span>
<span id="cb461-2"><a href="regression.html#cb461-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>gender <span class="ot">&lt;-</span> df<span class="sc">$</span>sex</span>
<span id="cb461-3"><a href="regression.html#cb461-3" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>gender[df<span class="sc">$</span>gender<span class="sc">==</span><span class="st">&quot;2&quot;</span>] <span class="ot">&lt;-</span> <span class="st">&quot;0&quot;</span></span>
<span id="cb461-4"><a href="regression.html#cb461-4" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>gender <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>gender, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;female&quot;</span>, <span class="st">&quot;male&quot;</span>), <span class="at">ordered =</span> <span class="cn">FALSE</span>) </span>
<span id="cb461-5"><a href="regression.html#cb461-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Double check values match original variable</span></span>
<span id="cb461-6"><a href="regression.html#cb461-6" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>gender)</span></code></pre></div>
<pre><code>## 
## female   male 
##   4586   4064</code></pre>
<div class="sourceCode" id="cb463"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb463-1"><a href="regression.html#cb463-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now let us run the multiple regression</span></span>
<span id="cb463-2"><a href="regression.html#cb463-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb463-3"><a href="regression.html#cb463-3" aria-hidden="true" tabindex="-1"></a>fit_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(antisocx <span class="sc">~</span> age <span class="sc">+</span> gender <span class="sc">+</span> bcsvictim <span class="sc">+</span> confx, <span class="at">data =</span> df)</span>
<span id="cb463-4"><a href="regression.html#cb463-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = antisocx ~ age + gender + bcsvictim + confx, data = df)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.8854 -0.5684  0.1142  0.7195  2.5249 
## 
## Coefficients:
##                       Estimate Std. Error t value             Pr(&gt;|t|)
## (Intercept)         -0.5136682  0.0328072 -15.657 &lt; 0.0000000000000002
## age                  0.0104148  0.0005699  18.276 &lt; 0.0000000000000002
## gendermale           0.1003834  0.0207701   4.833           0.00000137
## bcsvictimYes victim -0.4310943  0.0290209 -14.855 &lt; 0.0000000000000002
## confx                0.2038268  0.0106002  19.229 &lt; 0.0000000000000002
## 
## Residual standard error: 0.9361 on 8151 degrees of freedom
##   (494 observations deleted due to missingness)
## Multiple R-squared:  0.1247, Adjusted R-squared:  0.1243 
## F-statistic: 290.3 on 4 and 8151 DF,  p-value: &lt; 0.00000000000000022</code></pre>
<p>We return to those four points to focus on when confronted with a regression output:</p>
<ol style="list-style-type: decimal">
<li><p>Regression coefficients: The usual interpretation is to state that Y changes for every one-unit increase in X <em>when the other variables in the model are held constant</em> (or are ‘controlled for’). Therefore, a 0.01 increase in level of perceived antisocial behaviour in the neighbourhood is associated with a one-year increase in age, for example. This is similar to the bivariate regression. For categorical variables, however, the interpretation is different; notice how these variables have an additional label attached to them in the output. For example, <code>gender</code> includes ‘male’ and <code>bcsvictim</code> includes ‘yes victim’. Labels that do not appear next to the name of the categorical variable in the model are called the <em>reference category</em>. This category is the lowest value. You can select your reference category based on the modal category or if it is a category in which you are least interested. We interpret them as the following: males have a perceived antisocial behaviour level that averages 0.10 units higher than that of females; victims have a perceived antisocial behaviour level that averages .43 units lower than that of non-victims. A one-point score increase for confidence in neighbourhood police is related to .20 increase in level of perceived antisocial behaviour. For each interpretation, covariates in the model are controlled for.</p></li>
<li><p>P-value: All coefficients are statistically significant, meaning that we can reject the null hypothesis that no differences exist on perceived antisocial behaviour.</p></li>
<li><p>F-statistic: Now that we have more than one IV in our model, we evaluate whether all of the regression coefficients are zero. The F-statistic is below the conventional significance level of α = 0.05, so at least one of our IVs is related to our DV. You will also notice t-values for each IV. These are testing whether each of the IVs is associated with the DV when controlling for covariates in the model.</p></li>
<li><p><span class="math inline">\(R^2\)</span>: The <span class="math inline">\(R^2\)</span> is higher than that of our previous bivariate regression model. It will, however, inevitably increase whenever new variables are added to the model, regardless if they are only weakly related to the DV. Having said this, the new <span class="math inline">\(R^2\)</span> value suggests that the addition of the three new variables improves our previous model.</p></li>
</ol>
<p>If you would like to professionally present your results, you can use the function <code>tab_model ()</code> from the <code>sjplot</code> package:</p>
<div class="sourceCode" id="cb465"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb465-1"><a href="regression.html#cb465-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(fit_2)</span></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
antisocx
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.51
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.58 – -0.45
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
age
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01 – 0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
gender [male]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.10
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.06 – 0.14
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
bcsvictim [Yes victim]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.43
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.49 – -0.37
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
confx
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.18 – 0.22
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
8156
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.125 / 0.124
</td>
</tr>
</table>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="regression.html#cb466-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change name of DV</span></span>
<span id="cb466-2"><a href="regression.html#cb466-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(fit_2, <span class="at">dv.labels =</span> <span class="st">&quot;Perceived Antisocial Behaviour&quot;</span>)</span></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Perceived Antisocial Behaviour
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.51
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.58 – -0.45
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
age
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01 – 0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
gender [male]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.10
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.06 – 0.14
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
bcsvictim [Yes victim]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.43
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.49 – -0.37
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
confx
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.18 – 0.22
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
8156
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.125 / 0.124
</td>
</tr>
</table>
<div class="sourceCode" id="cb467"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb467-1"><a href="regression.html#cb467-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Change name of IVs</span></span>
<span id="cb467-2"><a href="regression.html#cb467-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tab_model</span>(fit_2, <span class="at">pred.labels =</span> <span class="fu">c</span>(<span class="st">&quot;(Intercept)&quot;</span>, <span class="st">&quot;Age&quot;</span>, <span class="st">&quot;Sex&quot;</span>, <span class="st">&quot;Victimisation&quot;</span>, <span class="st">&quot;Confidence in Police&quot;</span>), <span class="at">dv.labels =</span> <span class="st">&quot;Perceived Antisocial Behaviour&quot;</span>)</span></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
Perceived Antisocial Behaviour
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.51
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.58 – -0.45
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Age
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.01 – 0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Sex
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.10
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.06 – 0.14
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Victimisation
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.43
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.49 – -0.37
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
Confidence in Police
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.20
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.18 – 0.22
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
8156
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.125 / 0.124
</td>
</tr>
</table>
<hr />
</div>
</div>
<div id="logistic-regression" class="section level3" number="10.2.3">
<h3><span class="header-section-number">10.2.3</span> Logistic Regression</h3>
<p>Now, what if our dependent variable is categorical and binary? This is where <strong>logistic regression</strong>, a technique belonging to a family of techniques called <strong>generalized linear models</strong>, is appropriate. Those assumptions of linearity and normality are not issues because this technique, itself, is not based on the normal distribution.</p>
<p>In criminology, it is often the case that our DV has only two categories. For example, victim or not a victim; arrested or not arrested. This form of regression models the probability of belonging to one of the levels of the binary outcome.</p>
<p>For this example, we are interested in the relationship between race and receiving harsher treatment for possession of marijuana. We use the dataset <code>Arrests</code> from the <code>effects</code> package. This data includes information on police treatment of individuals arrested for possession of marijuana in Toronto, Canada. Our DV is whether the arrestee was released with summons; if they were not, they received harsh treatment such as being brought to the police station or held for bail:</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="regression.html#cb468-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effects)</span>
<span id="cb468-2"><a href="regression.html#cb468-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Arrests, <span class="at">package=</span><span class="st">&quot;effects&quot;</span>) <span class="co"># It will tell you that the dataset are not found, but it is there</span></span>
<span id="cb468-3"><a href="regression.html#cb468-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb468-4"><a href="regression.html#cb468-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking out our DV</span></span>
<span id="cb468-5"><a href="regression.html#cb468-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Arrests<span class="sc">$</span>released)</span></code></pre></div>
<pre><code>## 
##   No  Yes 
##  892 4334</code></pre>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb470-1"><a href="regression.html#cb470-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking out the order of the levels in the DV</span></span>
<span id="cb470-2"><a href="regression.html#cb470-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(Arrests<span class="sc">$</span>released)</span></code></pre></div>
<pre><code>## $levels
## [1] &quot;No&quot;  &quot;Yes&quot;
## 
## $class
## [1] &quot;factor&quot;</code></pre>
<p>Logistic regression will predict probabilities associated with the level whose first letter is further in the alphabet — this would be ‘yes’, the respondent was released with a summons. But this is not our level of interest. We will need to reorder the levels in the DV using the <code>relevel</code> function:</p>
<div class="sourceCode" id="cb472"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb472-1"><a href="regression.html#cb472-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reverse the order</span></span>
<span id="cb472-2"><a href="regression.html#cb472-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Rename the levels so that it is clear we now mean &#39;yes&#39; to harsh treatment</span></span>
<span id="cb472-3"><a href="regression.html#cb472-3" aria-hidden="true" tabindex="-1"></a>Arrests<span class="sc">$</span>harsher <span class="ot">&lt;-</span> <span class="fu">relevel</span>(Arrests<span class="sc">$</span>released, <span class="st">&quot;Yes&quot;</span>)</span>
<span id="cb472-4"><a href="regression.html#cb472-4" aria-hidden="true" tabindex="-1"></a>Arrests<span class="sc">$</span>harsher <span class="ot">&lt;-</span> <span class="fu">factor</span>(Arrests<span class="sc">$</span>harsher, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Yes&quot;</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>) </span>
<span id="cb472-5"><a href="regression.html#cb472-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb472-6"><a href="regression.html#cb472-6" aria-hidden="true" tabindex="-1"></a><span class="co">#  Check that it matches the original variable ‘released’ but in reverse order</span></span>
<span id="cb472-7"><a href="regression.html#cb472-7" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Arrests<span class="sc">$</span>harsher)</span></code></pre></div>
<pre><code>## 
##   No  Yes 
## 4334  892</code></pre>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb474-1"><a href="regression.html#cb474-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Arrests<span class="sc">$</span>released)</span></code></pre></div>
<pre><code>## 
##   No  Yes 
##  892 4334</code></pre>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb476-1"><a href="regression.html#cb476-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We will also reverse the levels in our race variable so that ‘white’ is ‘0’</span></span>
<span id="cb476-2"><a href="regression.html#cb476-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Arrests<span class="sc">$</span>colour)</span></code></pre></div>
<pre><code>## 
## Black White 
##  1288  3938</code></pre>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb478-1"><a href="regression.html#cb478-1" aria-hidden="true" tabindex="-1"></a>Arrests<span class="sc">$</span>race <span class="ot">&lt;-</span> Arrests<span class="sc">$</span>colour</span>
<span id="cb478-2"><a href="regression.html#cb478-2" aria-hidden="true" tabindex="-1"></a>Arrests<span class="sc">$</span>race <span class="ot">&lt;-</span> <span class="fu">relevel</span>(Arrests<span class="sc">$</span>race, <span class="st">&quot;White&quot;</span>)</span>
<span id="cb478-3"><a href="regression.html#cb478-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb478-4"><a href="regression.html#cb478-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check to see coding has changed</span></span>
<span id="cb478-5"><a href="regression.html#cb478-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Arrests<span class="sc">$</span>race)</span></code></pre></div>
<pre><code>## 
## White Black 
##  3938  1288</code></pre>
<p>Now that we have arranged the codes of our variables of interest, we fit the logistic regression model using the <code>glm ()</code> function and specify a logit model (<code>family=”binomial”</code>). We include three other variables in the model to see to what extent race seems to matter in harsher police treatment even when we adjust or consider sex, employment, and previous police contacts:</p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="regression.html#cb480-1" aria-hidden="true" tabindex="-1"></a>fit_3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(harsher <span class="sc">~</span> race <span class="sc">+</span> checks <span class="sc">+</span> sex <span class="sc">+</span> employed, <span class="at">data=</span>Arrests, <span class="at">family =</span> <span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb480-2"><a href="regression.html#cb480-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_3)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = harsher ~ race + checks + sex + employed, family = &quot;binomial&quot;, 
##     data = Arrests)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.5226  -0.6156  -0.4407  -0.3711   2.3449  
## 
## Coefficients:
##             Estimate Std. Error z value             Pr(&gt;|z|)
## (Intercept) -1.90346    0.15999 -11.898 &lt; 0.0000000000000002
## raceBlack    0.49608    0.08264   6.003        0.00000000194
## checks       0.35796    0.02580  13.875 &lt; 0.0000000000000002
## sexMale      0.04215    0.14965   0.282                0.778
## employedYes -0.77973    0.08386  -9.298 &lt; 0.0000000000000002
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4776.3  on 5225  degrees of freedom
## Residual deviance: 4330.7  on 5221  degrees of freedom
## AIC: 4340.7
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The output is similar to the one produced for linear regression, although there are some differences such as the Akaike information criterion (AIC) and the z-statistic, which is a similar idea to the t-test in linear regression. The z-statistic is a test of statistical significance and assesses whether each variable in the model is associated with the DV.</p>
<p>All IVs are significantly associated with harsher police treatment except for sex. We see that every one unit increase in the number of previous police contacts, the log odds of receiving harsher treatment (versus being released on summons) increases by 0.36 adjusting for the other variables in the model.</p>
<p>Observe that variables that are categorical have a label next to them in the output. For example, sex has ‘male’ next to it; race has ‘black’ next to it; employed has ‘yes’ next to it. These are the categories you are comparing to the reference category (whichever category is coded ‘0’). So, being black increases the log odds of receiving harsh treatment by 0.49 compared to being white, while being employed decreases the log odds of harsh treatment by 0.77 compared to being unemployed.</p>
<p>This is good, but most people find interpreting log odds, well, odd – it is not very intuitive. It is common to use the <strong>odds ratio</strong> (OR) to interpret logistic regression. We convert these values into ORs:</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="regression.html#cb482-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(fit_3))</span></code></pre></div>
<pre><code>## (Intercept)   raceBlack      checks     sexMale employedYes 
##   0.1490516   1.6422658   1.4304108   1.0430528   0.4585312</code></pre>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="regression.html#cb484-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can add confidence intervals</span></span>
<span id="cb484-2"><a href="regression.html#cb484-2" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(fit_3), <span class="fu">confint</span>(fit_3)))</span></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                    OR     2.5 %    97.5 %
## (Intercept) 0.1490516 0.1081600 0.2026495
## raceBlack   1.6422658 1.3957633 1.9298763
## checks      1.4304108 1.3601419 1.5049266
## sexMale     1.0430528 0.7830594 1.4090622
## employedYes 0.4585312 0.3892103 0.5407210</code></pre>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="regression.html#cb487-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Another way of getting the results, which uses less typing, is to use the Logit() function from the lessr package</span></span>
<span id="cb487-2"><a href="regression.html#cb487-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb487-3"><a href="regression.html#cb487-3" aria-hidden="true" tabindex="-1"></a><span class="fu">Logit</span>(harsher <span class="sc">~</span> checks <span class="sc">+</span> colour <span class="sc">+</span> sex <span class="sc">+</span> employed, <span class="at">data=</span>Arrests, <span class="at">brief=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Response Variable:   harsher
## Predictor Variable 1:  checks
## Predictor Variable 2:  colour
## Predictor Variable 3:  sex
## Predictor Variable 4:  employed
## 
## Number of cases (rows) of data:  5226 
## Number of cases retained for analysis:  5226 
## 
## 
## 
##    BASIC ANALYSIS 
## 
## Model Coefficients
## 
##              Estimate    Std Err  z-value  p-value   Lower 95%   Upper 95%
## (Intercept)   -1.4074     0.1724   -8.162    0.000     -1.7453     -1.0694 
##      checks    0.3580     0.0258   13.875    0.000      0.3074      0.4085 
## colourWhite   -0.4961     0.0826   -6.003    0.000     -0.6580     -0.3341 
##     sexMale    0.0422     0.1496    0.282    0.778     -0.2511      0.3355 
## employedYes   -0.7797     0.0839   -9.298    0.000     -0.9441     -0.6154 
## 
## 
## Odds ratios and confidence intervals
## 
##              Odds Ratio   Lower 95%   Upper 95%
## (Intercept)      0.2448      0.1746      0.3432 
##      checks      1.4304      1.3599      1.5046 
## colourWhite      0.6089      0.5179      0.7160 
##     sexMale      1.0431      0.7779      1.3986 
## employedYes      0.4585      0.3890      0.5404 
## 
## 
## Model Fit
## 
##     Null deviance: 4776.258 on 5225 degrees of freedom
## Residual deviance: 4330.699 on 5221 degrees of freedom
## 
## AIC: 4340.699 
## 
## Number of iterations to convergence: 5 
## 
## 
## 
## 
## &gt;&gt;&gt; Note:  colour is not a numeric variable.
## 
## 
## 
## &gt;&gt;&gt; Note:  sex is not a numeric variable.
## 
## 
## 
## &gt;&gt;&gt; Note:  employed is not a numeric variable.
## 
## Collinearity
## 
## 
## &gt;&gt;&gt; No collinearity analysis because not all variables are numeric.</code></pre>
<p>If the odds ratio is greater than 1, it indicates that the odds of receiving harsh treatment increases when the independent variable, too, increases. Previous police contacts increase the odds of harsher treatment by 43% and being black increases the odds of harsher treatment by 64% (all the while adjusting for the other variables in the model). Employment, however, has an odds ratio of 0.45. If the OR is between 0 and 1, it is considered a negative relationship. Referring to the confidence intervals is also helpful: if 0 is within the interval, the result is statistically non-significant. Take the 95% CI of sex, for example.</p>
<p>For both types of regression, it is inappropriate to make comparisons between IVs. You cannot directly compare the coefficients of one IV to the other, unless they use the same metric. For more ways to interpret ORs in logistic regression, refer to the <a href="https://stats.idre.ucla.edu/other/mult-pkg/faq/general/faq-how-do-i-interpret-odds-ratios-in-logistic-regression/">UCLA Institute for Digital Research and Education</a></p>
<div id="model-fit" class="section level4" number="10.2.3.1">
<h4><span class="header-section-number">10.2.3.1</span> <strong>Model Fit</strong></h4>
<p>Now, how well is the fit of our logistic regression model? In order words, how well does our IVs collectively predict the DV? Recall from OLS regression, we assessed how well our overall model predicts the DV by observing the <em>F-statistic</em> and <em><span class="math inline">\(R^2\)</span></em>. This is not the case for logistic regression. The reason is, in our familiar linear regression, we understand residual variation (related to that regression line) through the error sum of squares. In logistic regression, there is not one way to understand residual variation, but several, because of its binary outcome. This results in different ways of understanding model fit: (1) quantitative prediction, focused on how close the prediction is to being correct; (2) qualitative prediction, focused on whether the prediction is correct or incorrect; or (3) both. We go through the first one.</p>
</div>
<div id="quantitative-prediction" class="section level4" number="10.2.3.2">
<h4><span class="header-section-number">10.2.3.2</span> <em>Quantitative Prediction</em></h4>
<p>A common measure for evaluating model fit is the <strong>deviance</strong>, also known as -2LL. It measures how accurate the prediction is by multiplying the log likelihood statistic by -2. This <em>log-likelihood statistic</em> measures how much unexplained variance remains after the model is fitted, whereby larger values reflect poorer fit. Larger values of -2LL, similarly, indicate worse prediction.</p>
<p>The logistic regression model can be estimated using an approach of probability called <em>maximum likelihood estimation</em>, which calculates the probability of obtaining a certain result given the IVs in the model. It does so by minimising that -2LL. This is like what OLS regression does with the error sum of squares – tries to minimise it. Thus, -2LL is to logistic regression as the error sum of squares is to OLS regression.</p>
<p>When we re-run our model, we find that -2LL is in the form of <em>null</em> and <em>residual</em> deviances towards the bottom of the output:</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="regression.html#cb489-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Logit</span>(harsher <span class="sc">~</span> checks <span class="sc">+</span> colour <span class="sc">+</span> sex <span class="sc">+</span> employed, <span class="at">data=</span>Arrests, <span class="at">brief=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Response Variable:   harsher
## Predictor Variable 1:  checks
## Predictor Variable 2:  colour
## Predictor Variable 3:  sex
## Predictor Variable 4:  employed
## 
## Number of cases (rows) of data:  5226 
## Number of cases retained for analysis:  5226 
## 
## 
## 
##    BASIC ANALYSIS 
## 
## Model Coefficients
## 
##              Estimate    Std Err  z-value  p-value   Lower 95%   Upper 95%
## (Intercept)   -1.4074     0.1724   -8.162    0.000     -1.7453     -1.0694 
##      checks    0.3580     0.0258   13.875    0.000      0.3074      0.4085 
## colourWhite   -0.4961     0.0826   -6.003    0.000     -0.6580     -0.3341 
##     sexMale    0.0422     0.1496    0.282    0.778     -0.2511      0.3355 
## employedYes   -0.7797     0.0839   -9.298    0.000     -0.9441     -0.6154 
## 
## 
## Odds ratios and confidence intervals
## 
##              Odds Ratio   Lower 95%   Upper 95%
## (Intercept)      0.2448      0.1746      0.3432 
##      checks      1.4304      1.3599      1.5046 
## colourWhite      0.6089      0.5179      0.7160 
##     sexMale      1.0431      0.7779      1.3986 
## employedYes      0.4585      0.3890      0.5404 
## 
## 
## Model Fit
## 
##     Null deviance: 4776.258 on 5225 degrees of freedom
## Residual deviance: 4330.699 on 5221 degrees of freedom
## 
## AIC: 4340.699 
## 
## Number of iterations to convergence: 5 
## 
## 
## 
## 
## &gt;&gt;&gt; Note:  colour is not a numeric variable.
## 
## 
## 
## &gt;&gt;&gt; Note:  sex is not a numeric variable.
## 
## 
## 
## &gt;&gt;&gt; Note:  employed is not a numeric variable.
## 
## Collinearity
## 
## 
## &gt;&gt;&gt; No collinearity analysis because not all variables are numeric.</code></pre>
<p>The null deviance is the value of -2LL for a model without any IVs, whereas the residual deviance is the value of -2LL for our present model. We test to see if the null hypothesis, that the regression coefficients (IVs) equal zero, is true. We do so by calculating the <em>model chi-squared</em>. This is the difference between both deviances:</p>
<div class="sourceCode" id="cb491"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb491-1"><a href="regression.html#cb491-1" aria-hidden="true" tabindex="-1"></a><span class="co"># All the information we need to calculate the model chi-squared is already in our model object</span></span>
<span id="cb491-2"><a href="regression.html#cb491-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(fit_3)</span></code></pre></div>
<pre><code>##  [1] &quot;coefficients&quot;      &quot;residuals&quot;         &quot;fitted.values&quot;    
##  [4] &quot;effects&quot;           &quot;R&quot;                 &quot;rank&quot;             
##  [7] &quot;qr&quot;                &quot;family&quot;            &quot;linear.predictors&quot;
## [10] &quot;deviance&quot;          &quot;aic&quot;               &quot;null.deviance&quot;    
## [13] &quot;iter&quot;              &quot;weights&quot;           &quot;prior.weights&quot;    
## [16] &quot;df.residual&quot;       &quot;df.null&quot;           &quot;y&quot;                
## [19] &quot;converged&quot;         &quot;boundary&quot;          &quot;model&quot;            
## [22] &quot;call&quot;              &quot;formula&quot;           &quot;terms&quot;            
## [25] &quot;data&quot;              &quot;offset&quot;            &quot;control&quot;          
## [28] &quot;method&quot;            &quot;contrasts&quot;         &quot;xlevels&quot;</code></pre>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb493-1"><a href="regression.html#cb493-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We now calculate said chi-squared by taking the difference of the deviances </span></span>
<span id="cb493-2"><a href="regression.html#cb493-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(fit_3, null.deviance <span class="sc">-</span> deviance)</span></code></pre></div>
<pre><code>## [1] 445.5594</code></pre>
<p>Our obtained value is: 445.56. We do not know, though, how big or small this value is to determine how predictive our model is. We will need a test of statistical significance:</p>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="regression.html#cb495-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtaining the p-value</span></span>
<span id="cb495-2"><a href="regression.html#cb495-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(fit_3, <span class="fu">pchisq</span>(null.deviance <span class="sc">-</span> deviance, df.null <span class="sc">-</span> df.residual, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>))</span></code></pre></div>
<pre><code>## [1] 3.961177e-95</code></pre>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="regression.html#cb497-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Incorporating previous calculation of difference between deviances</span></span>
<span id="cb497-2"><a href="regression.html#cb497-2" aria-hidden="true" tabindex="-1"></a><span class="co"># df.null - df.residual: calculating the degrees of freedom (should equal the number of IVs in the model)</span></span></code></pre></div>
<p>The p-value is smaller than α = 0.05, so we conclude that our model is a better fit than a model with no IVs (or predictors).</p>
<p>In addition, <a href="https://methods.sagepub.com/book/logistic-regression-from-introductory-to-advanced-concepts-and-applications">Professor Scott Menard (2010)</a> suggests calculating the <em>likelihood ratio <span class="math inline">\(R^2\)</span></em>, also known as the Hosmer/Lemeshow <span class="math inline">\(R^2\)</span>, by taking the difference of the previous deviances and dividing it by the null deviance. The likelihood ratio <span class="math inline">\(R^2\)</span> tells you the extent to which including your IVs in your model reduces the variation, or error, as measured by the null deviance. The value can range from 0 to 1, where higher values mean better predictive accuracy:</p>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="regression.html#cb498-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Likelihood ratio R2</span></span>
<span id="cb498-2"><a href="regression.html#cb498-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(fit_3, (null.deviance <span class="sc">-</span> deviance)<span class="sc">/</span>null.deviance)</span></code></pre></div>
<pre><code>## [1] 0.09328629</code></pre>
<p>This particular <span class="math inline">\(R^2\)</span> is considered a ‘pseudo- <span class="math inline">\(R^2\)</span>’ as it is not the same as the one obtained in OLS/ linear regression. There are many kinds of pseudo ones but Menard recommended the likelihood ratio one because (1) of its conceptual similarity to the <span class="math inline">\(R^2\)</span> in OLS regression; (2) it is not easily swayed by the base rate (the number of cases that have the charateristic of interest); (3) it is easy to interpret; and (4) it can also be used in other generalised linear models, such as ones with categorical DVs with more than two levels.</p>
<hr />
</div>
</div>
</div>
<div id="summary-8" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> SUMMARY</h2>
<p>Regression allows us to look at relationships between variables while including other variables, called <strong>covariates</strong>, in the model. For OLS regression, assumptions must be met before embarking on fitting this model, and has to do with building the <strong>regression line</strong> whereby the line starts at the <strong>intercept</strong> and its angle is determined by the <strong>slope</strong>. <strong>Residuals</strong> form the equation to determine the <span class="math inline">\(R^2\)</span> and is the error of the model. When the DV is binary, logistic regression is appropriate. The <strong>odds ratio</strong> is an easier way to interpret logistic regression. We assess model fit through quantitative prediction measures of deviance, and it is recommended to use the likelihood ratio <span class="math inline">\(R^2\)</span> instead of other pseudo <span class="math inline">\(R^2s\)</span></p>
<p>Homework time!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="strength-of-relationships.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/09-regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Modelling-Crime-Data-2021.pdf", "Modelling-Crime-Data-2021.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
