<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Relationships with Categorical Variables | CRIM20452 Modelling Criminological Data</title>
  <meta name="description" content="This is a companion workbook for the 2nd year undergraduate module CRIM20452 Modelling Criminological Data at the University of Manchester" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Relationships with Categorical Variables | CRIM20452 Modelling Criminological Data" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a companion workbook for the 2nd year undergraduate module CRIM20452 Modelling Criminological Data at the University of Manchester" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Relationships with Categorical Variables | CRIM20452 Modelling Criminological Data" />
  
  <meta name="twitter:description" content="This is a companion workbook for the 2nd year undergraduate module CRIM20452 Modelling Criminological Data at the University of Manchester" />
  

<meta name="author" content="Laura Bui &amp; Reka Solymosi" />


<meta name="date" content="2021-04-07" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="hypotheses.html"/>
<link rel="next" href="strength-of-relationships.html"/>
<script src="libs/header-attrs-2.7.2/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Modelling Criminological Data</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html"><i class="fa fa-check"></i><b>1</b> A First Lesson About R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#install-r-r-studio"><i class="fa fa-check"></i><b>1.1</b> Install R &amp; R Studio</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#activity-1-identifying-your-operating-system"><i class="fa fa-check"></i><b>1.1.1</b> Activity 1: Identifying your operating system</a></li>
<li class="chapter" data-level="1.1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#activity-2-install-r-r-studio"><i class="fa fa-check"></i><b>1.1.2</b> Activity 2: Install R &amp; R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#getting-to-know-rstudio"><i class="fa fa-check"></i><b>1.2</b> Getting to know <code>RStudio</code></a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#the-four-panes-of-r-studio"><i class="fa fa-check"></i><b>1.2.1</b> The four panes of R Studio</a></li>
<li class="chapter" data-level="1.2.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#customising-r-studio"><i class="fa fa-check"></i><b>1.2.2</b> Customising R Studio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#todays-3-topics"><i class="fa fa-check"></i><b>1.3</b> Today’s 3 (TOPICS)</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#operators-and-functions"><i class="fa fa-check"></i><b>1.3.1</b> Operators and Functions</a></li>
<li class="chapter" data-level="1.3.2" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#objects"><i class="fa fa-check"></i><b>1.3.2</b> Objects</a></li>
<li class="chapter" data-level="1.3.3" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#packages-1"><i class="fa fa-check"></i><b>1.3.3</b> Packages</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="a-first-lesson-about-r.html"><a href="a-first-lesson-about-r.html#summary"><i class="fa fa-check"></i><b>1.4</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html"><i class="fa fa-check"></i><b>2</b> Getting to know your data</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#the-tidyverse"><i class="fa fa-check"></i><b>2.1</b> The Tidyverse</a></li>
<li class="chapter" data-level="2.2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#r-projects-getting-your-work-files-organised"><i class="fa fa-check"></i><b>2.2</b> R Projects – Getting Your Work Files Organised</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#activity-1-making-yourself-a-project"><i class="fa fa-check"></i><b>2.2.1</b> Activity 1: Making yourself a project</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#importing-data"><i class="fa fa-check"></i><b>2.3</b> Importing Data</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#activity-2-importing-and-viewing-data"><i class="fa fa-check"></i><b>2.3.1</b> Activity 2: Importing and Viewing Data</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#todays-3-topics-1"><i class="fa fa-check"></i><b>2.4</b> Today’s 3 (TOPICS)</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#variables"><i class="fa fa-check"></i><b>2.4.1</b> Variables</a></li>
<li class="chapter" data-level="2.4.2" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#labels"><i class="fa fa-check"></i><b>2.4.2</b> Labels</a></li>
<li class="chapter" data-level="2.4.3" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#subsetting"><i class="fa fa-check"></i><b>2.4.3</b> Subsetting</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#summary-1"><i class="fa fa-check"></i><b>2.5</b> SUMMARY</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="getting-to-know-your-data.html"><a href="getting-to-know-your-data.html#answers-to-activities-if-applicable"><i class="fa fa-check"></i><b>2.5.1</b> Answers to activities (if applicable)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>3</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-visualization.html"><a href="data-visualization.html#grammar-of-graphics"><i class="fa fa-check"></i><b>3.1</b> Grammar of Graphics</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-visualization.html"><a href="data-visualization.html#activity-1-getting-ready"><i class="fa fa-check"></i><b>3.1.1</b> Activity 1: Getting Ready</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-visualization.html"><a href="data-visualization.html#ggplot2"><i class="fa fa-check"></i><b>3.2</b> ggplot2</a></li>
<li class="chapter" data-level="3.3" data-path="data-visualization.html"><a href="data-visualization.html#todays-3"><i class="fa fa-check"></i><b>3.3</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="data-visualization.html"><a href="data-visualization.html#layers"><i class="fa fa-check"></i><b>3.3.1</b> Layers</a></li>
<li class="chapter" data-level="3.3.2" data-path="data-visualization.html"><a href="data-visualization.html#graphs-for-categorical-data"><i class="fa fa-check"></i><b>3.3.2</b> Graphs for Categorical Data</a></li>
<li class="chapter" data-level="3.3.3" data-path="data-visualization.html"><a href="data-visualization.html#graphs-for-numeric-data"><i class="fa fa-check"></i><b>3.3.3</b> Graphs for Numeric Data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-visualization.html"><a href="data-visualization.html#summary-2"><i class="fa fa-check"></i><b>3.4</b> SUMMARY</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="data-visualization.html"><a href="data-visualization.html#answers-to-activities"><i class="fa fa-check"></i><b>3.4.1</b> ANSWERS TO ACTIVITIES:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html"><i class="fa fa-check"></i><b>4</b> Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="4.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#revisiting-descriptive-statistics"><i class="fa fa-check"></i><b>4.1</b> Revisiting Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#activity-1-our-preparation-routine"><i class="fa fa-check"></i><b>4.1.1</b> Activity 1: Our preparation routine</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#todays-3-1"><i class="fa fa-check"></i><b>4.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#central-tendency"><i class="fa fa-check"></i><b>4.2.1</b> Central Tendency</a></li>
<li class="chapter" data-level="4.2.2" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#outliers"><i class="fa fa-check"></i><b>4.2.2</b> Outliers</a></li>
<li class="chapter" data-level="4.2.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#measures-of-dispersion"><i class="fa fa-check"></i><b>4.2.3</b> Measures of Dispersion</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#summary-3"><i class="fa fa-check"></i><b>4.3</b> SUMMARY</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="descriptive-statistics.html"><a href="descriptive-statistics.html#answers-to-activities-where-applicable"><i class="fa fa-check"></i><b>4.3.1</b> Answers to Activities (where applicable)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="inferential-statistics.html"><a href="inferential-statistics.html"><i class="fa fa-check"></i><b>5</b> Inferential Statistics</a>
<ul>
<li class="chapter" data-level="5.1" data-path="inferential-statistics.html"><a href="inferential-statistics.html#generalising-about-the-world-from-data"><i class="fa fa-check"></i><b>5.1</b> Generalising About the World from Data</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="inferential-statistics.html"><a href="inferential-statistics.html#activity-1-our-preparation-routine-1"><i class="fa fa-check"></i><b>5.1.1</b> Activity 1: Our preparation routine</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="inferential-statistics.html"><a href="inferential-statistics.html#todays-3-2"><i class="fa fa-check"></i><b>5.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="inferential-statistics.html"><a href="inferential-statistics.html#samples"><i class="fa fa-check"></i><b>5.2.1</b> Samples</a></li>
<li class="chapter" data-level="5.2.2" data-path="inferential-statistics.html"><a href="inferential-statistics.html#the-standard-error"><i class="fa fa-check"></i><b>5.2.2</b> The Standard Error</a></li>
<li class="chapter" data-level="5.2.3" data-path="inferential-statistics.html"><a href="inferential-statistics.html#confidence-intervals"><i class="fa fa-check"></i><b>5.2.3</b> Confidence Intervals</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="inferential-statistics.html"><a href="inferential-statistics.html#summary-4"><i class="fa fa-check"></i><b>5.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="hypotheses.html"><a href="hypotheses.html"><i class="fa fa-check"></i><b>6</b> Hypotheses</a>
<ul>
<li class="chapter" data-level="6.1" data-path="hypotheses.html"><a href="hypotheses.html#hypothesis-testing"><i class="fa fa-check"></i><b>6.1</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="hypotheses.html"><a href="hypotheses.html#the-null-hypothesis"><i class="fa fa-check"></i><b>6.1.1</b> The null hypothesis</a></li>
<li class="chapter" data-level="6.1.2" data-path="hypotheses.html"><a href="hypotheses.html#directional-hypotheses"><i class="fa fa-check"></i><b>6.1.2</b> Directional hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="hypotheses.html"><a href="hypotheses.html#todays-3-3"><i class="fa fa-check"></i><b>6.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="hypotheses.html"><a href="hypotheses.html#statistical-significance"><i class="fa fa-check"></i><b>6.2.1</b> Statistical Significance</a></li>
<li class="chapter" data-level="6.2.2" data-path="hypotheses.html"><a href="hypotheses.html#hypothesis-tests-for-the-binomial-distribution"><i class="fa fa-check"></i><b>6.2.2</b> Hypothesis Tests for the Binomial Distribution</a></li>
<li class="chapter" data-level="6.2.3" data-path="hypotheses.html"><a href="hypotheses.html#hypothesis-tests-for-the-normal-distribution"><i class="fa fa-check"></i><b>6.2.3</b> Hypothesis Tests for the Normal Distribution</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="hypotheses.html"><a href="hypotheses.html#summary-5"><i class="fa fa-check"></i><b>6.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html"><i class="fa fa-check"></i><b>7</b> Relationships with Categorical Variables</a>
<ul>
<li class="chapter" data-level="7.1" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#associating-with-categorical-variables"><i class="fa fa-check"></i><b>7.1</b> Associating with Categorical Variables</a></li>
<li class="chapter" data-level="7.2" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#todays-3-4"><i class="fa fa-check"></i><b>7.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#independent-and-dependent-variables"><i class="fa fa-check"></i><b>7.2.1</b> Independent and Dependent Variables</a></li>
<li class="chapter" data-level="7.2.2" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#comparing-means-the-t-test"><i class="fa fa-check"></i><b>7.2.2</b> Comparing means: the t-test</a></li>
<li class="chapter" data-level="7.2.3" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#chi-square"><i class="fa fa-check"></i><b>7.2.3</b> Chi-square</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="relationships-with-categorical-variables.html"><a href="relationships-with-categorical-variables.html#summary-6"><i class="fa fa-check"></i><b>7.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html"><i class="fa fa-check"></i><b>8</b> Strength of Relationships</a>
<ul>
<li class="chapter" data-level="8.1" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#measures-of-association"><i class="fa fa-check"></i><b>8.1</b> Measures of Association</a></li>
<li class="chapter" data-level="8.2" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#todays-3-5"><i class="fa fa-check"></i><b>8.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#between-categorical-nominal-variables"><i class="fa fa-check"></i><b>8.2.1</b> Between Categorical, Nominal Variables</a></li>
<li class="chapter" data-level="8.2.2" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#between-categorical-ordinal-variables"><i class="fa fa-check"></i><b>8.2.2</b> Between Categorical, Ordinal Variables</a></li>
<li class="chapter" data-level="8.2.3" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#between-numeric-variables"><i class="fa fa-check"></i><b>8.2.3</b> Between Numeric Variables</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="strength-of-relationships.html"><a href="strength-of-relationships.html#summary-7"><i class="fa fa-check"></i><b>8.3</b> SUMMARY</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>9</b> Regression</a>
<ul>
<li class="chapter" data-level="9.1" data-path="regression.html"><a href="regression.html#multiple-and-simultaneous-relationships"><i class="fa fa-check"></i><b>9.1</b> Multiple and Simultaneous Relationships</a></li>
<li class="chapter" data-level="9.2" data-path="regression.html"><a href="regression.html#todays-3-6"><i class="fa fa-check"></i><b>9.2</b> Today’s 3</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="regression.html"><a href="regression.html#assumptions-of-ols-regression"><i class="fa fa-check"></i><b>9.2.1</b> Assumptions of OLS Regression</a></li>
<li class="chapter" data-level="9.2.2" data-path="regression.html"><a href="regression.html#interpreting-ols-regression"><i class="fa fa-check"></i><b>9.2.2</b> Interpreting OLS Regression</a></li>
<li class="chapter" data-level="9.2.3" data-path="regression.html"><a href="regression.html#logistic-regression"><i class="fa fa-check"></i><b>9.2.3</b> Logistic Regression</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="regression.html"><a href="regression.html#summary-8"><i class="fa fa-check"></i><b>9.3</b> SUMMARY</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">CRIM20452 Modelling Criminological Data</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="relationships-with-categorical-variables" class="section level1" number="7">
<h1><span class="header-section-number">Chapter 7</span> Relationships with Categorical Variables</h1>
<div id="independent-and-dependent-variables-t-test-chi-square" class="section level4 unnumbered">
<h4><em>Independent and Dependent Variables, T-test, Chi-square</em></h4>
</div>
<div id="learning-outcomes-6" class="section level4 unnumbered">
<h4>Learning Outcomes:</h4>
<ul>
<li>Learn to arrange variables as independent and dependent variables</li>
<li>Learn to test for statistical significance in relationships between two variables variables when:</li>
<li>they are both categorical</li>
<li>one is binary categorical and one is numeric</li>
<li>Understand how to interpret outputs from t-tests and the chi-square test</li>
</ul>
</div>
<div id="todays-learning-tools-6" class="section level4 unnumbered">
<h4>Today’s Learning Tools:</h4>
<div id="data-6" class="section level5 unnumbered">
<h5><em>Data:</em></h5>
<ul>
<li>National Youth Survey (NYS)</li>
<li>British Crime Survey (BCS)</li>
</ul>
</div>
<div id="packages-7" class="section level5 unnumbered">
<h5><em>Packages:</em></h5>
<ul>
<li><code>dplyr</code></li>
<li><code>effsize</code></li>
<li><code>forcats</code></li>
<li><code>gmodels</code></li>
<li><code>haven</code></li>
<li><code>here</code></li>
<li><code>labelled</code></li>
<li><code>skimr</code></li>
<li><code>vcdExtra</code></li>
</ul>
</div>
<div id="functions-introduced-and-packages-to-which-they-belong-6" class="section level5 unnumbered">
<h5><em>Functions introduced (and packages to which they belong)</em></h5>
<ul>
<li><code>chisq.test()</code> : Produces the chi-square test (<code>base R</code>)</li>
<li><code>CrossTable()</code> : Produces contingency tables (<code>gmodels</code>)</li>
<li><code>fct_explicit_na()</code> : Provides missing values an explicit factor level (<code>forcats</code>)</li>
<li><code>fisher.test()</code> : Produces Fisher’s exact test (<code>base R</code>)</li>
<li><code>merge()</code> : Merge datasets by common row or column names (<code>base R</code>)</li>
<li><code>n()</code> : Count observations within <code>summarize()</code>, <code>mutate()</code>, <code>filter()</code> (<code>dplyr</code>)</li>
<li><code>read_dta()</code> : Imports a .dta Stata file (<code>haven</code>)</li>
<li><code>t.test()</code>: Performs one and two sample t-tests on vectors of data (<code>base R</code>)</li>
<li><code>var.test()</code> : Performs an F-test to compare the variances of two samples from normal populations (<code>base R</code>)</li>
<li><code>with()</code> : Evaluates an expression, often to specify data you want to use (<code>base R</code>)</li>
</ul>
<hr />
</div>
</div>
<div id="associating-with-categorical-variables" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Associating with Categorical Variables</h2>
<p>We are familiar with categorical variables, which take the forms of nominal and ordinal level characteristics, can be binary (have only two possible values). In <code>R</code>, these variables are encoded as a factor class, and for shorthand, are referred to as <strong>factors</strong>.</p>
<p>In inferential statistics, sometimes we want to make predictions about relationships with factors. For example, we want to understand the relationship between sex and alcohol consumption. Perhaps we think males will have higher alcohol consumption than females. The variable, sex, in this example, is a binary factor with the two categories, male and female, whereas alcohol consumption is a numeric variable.</p>
<p>Today, we learn how to conduct more inferential statistical analyses, with categorical variables.</p>
<div id="activity-1-our-r-prep-routine" class="section level5" number="7.1.0.0.1">
<h5><span class="header-section-number">7.1.0.0.1</span> Activity 1: Our R prep routine</h5>
<p>Before we start, we do the following:</p>
<ol style="list-style-type: decimal">
<li><p>Open up our existing <code>R</code> project</p></li>
<li><p>Install and load the required packages listed above</p></li>
<li><p>Download from Blackboard and load into R the British Crime Survey (BCS) dataset (<em>bcs_2007_8_teaching_data_unrestricted.dta</em> ) using the function <code>read_dta()</code>, specifying the working directory with <code>here()</code>. Here I name it `BCS0708``.</p></li>
</ol>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="relationships-with-categorical-variables.html#cb361-1" aria-hidden="true" tabindex="-1"></a>BCS0708 <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="fu">here</span>(<span class="st">&quot;Datasets&quot;</span>, <span class="st">&quot;bcs_2007_8_teaching_data_unrestricted.dta&quot;</span>))</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li>Get to know the datasets with the <code>View()</code> function.</li>
</ol>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb362-1"><a href="relationships-with-categorical-variables.html#cb362-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(BCS0708)</span></code></pre></div>
<hr />
</div>
</div>
<div id="todays-3-4" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> Today’s 3</h2>
<p>We further our understanding of inferential statistics by learning more about variables and a couple of new statistical analyses that examine a relationship with factor variables. Our three topics today are: <strong>independent and dependent variables</strong>, the <strong>t-test</strong>, and the <strong>chi-square</strong>.</p>
<hr />
<div id="independent-and-dependent-variables" class="section level3" number="7.2.1">
<h3><span class="header-section-number">7.2.1</span> Independent and Dependent Variables</h3>
<p>In learning to set hypotheses last week, we primarily wanted to know whether there was a relationship between certain variables. Inadvertently, we also were arranging our variables in a way that indicated one was the explanation and the other was the outcome.</p>
<p>Using our previous example on gender and fear of crime we can arrange them so that sex is the <strong>independent variable</strong> (<span class="math inline">\(X\)</span>), which means that it is assumed to have an impact on the amount of fear of crime, the <strong>dependent variable</strong> (<span class="math inline">\(Y\)</span>), which is considered to be influenced by <span class="math inline">\(X\)</span>. We believe that gender (<span class="math inline">\(X\)</span>) has an influence on level of fear of crime (<span class="math inline">\(Y\)</span>), and hypothesise, based on previous research, that males will have lower levels of fear of crime than females. We then select a sample, collect our data from that sample, and finally conduct an appropriate statistical test to find out.</p>
<!-- Although independent and dependent variables are not terms usually used for today’s analyses, we will use them to indicate which variable plays the role of explanation and which plays the part of outcome. In addition, it is good to get into the mindset of arranging your variables as such. This helps to clarify how your variables will relate to each other.  -->
<p>An important point to remember is that although the independent variable (IV) is considered to impact on the dependent variable (DV), it <em>does not mean the IV causes the DV</em>. We can only arrange these variables in the direction we think is suitable and make statements about whether they are related to each other. Causal inference is a whole area of research, as establishing causal relationships is not an easy task. One approach we have covered/ made references to throughout your methodological educations is to use experimental research designs, such as randomised control trials. If you are interested in Causal Inference, I can strongly recommend Scott Cunningham’s <a href="https://www.scunning.com/mixtape.html">Causal Inference Mixtape</a>. But for the kinds of analysis we’ll be doing here, best keep in mind that correlation <em>does not mean</em> causation.</p>
<hr />
</div>
<div id="comparing-means-the-t-test" class="section level3" number="7.2.2">
<h3><span class="header-section-number">7.2.2</span> Comparing means: the t-test</h3>
<p>When assessing the relationship between a categorical variable with two possible values, and a numeric variable, we usually try to summarise the numeric variabble for each group, and compare these summaries. For example we may want to compare between the 5-number summary of one group and the other.</p>
<p>In our example, we are looking at drinking in young people, and how that varies between different genders. For this, we have two relevant variables in our data <code>bcs</code>. Let’s have a look:</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="relationships-with-categorical-variables.html#cb363-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(BCS0708<span class="sc">$</span>sex)</span></code></pre></div>
<pre><code>## $label
## [1] &quot;respondent sex&quot;
## 
## $format.stata
## [1] &quot;%8.0g&quot;
## 
## $class
## [1] &quot;haven_labelled&quot; &quot;vctrs_vctr&quot;     &quot;double&quot;        
## 
## $labels
##   male female 
##      1      2</code></pre>
<p>We can see that the first variable, <code>sex</code> takes the values of 1 or 2, 1 for Male and 2 for Female. Let’s recode like we learned in previous weeks:</p>
<div class="sourceCode" id="cb365"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb365-1"><a href="relationships-with-categorical-variables.html#cb365-1" aria-hidden="true" tabindex="-1"></a>BCS0708<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(BCS0708<span class="sc">$</span>sex)</span></code></pre></div>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="relationships-with-categorical-variables.html#cb366-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(BCS0708<span class="sc">$</span>tcviolent)</span></code></pre></div>
<pre><code>## $label
## [1] &quot;respondent level of worry about being a victim of personal crime (high score = h&quot;
## 
## $format.stata
## [1] &quot;%9.0g&quot;</code></pre>
<p>The <code>tcviolent</code> variable representing “respondent level of worry about being a victim of personal crime (high score = high worry)”. This is a numeric score and therefore a numeric variable. So how may this differ between the two groups?</p>
<p>One way to display a 5-number summary is to use box plots. Let’s do this now:</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="relationships-with-categorical-variables.html#cb368-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(BCS0708, <span class="fu">aes</span> (<span class="at">x =</span> tcviolent, <span class="at">group =</span> sex, <span class="at">fill =</span> sex)) <span class="sc">+</span> </span>
<span id="cb368-2"><a href="relationships-with-categorical-variables.html#cb368-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb368-3"><a href="relationships-with-categorical-variables.html#cb368-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb368-4"><a href="relationships-with-categorical-variables.html#cb368-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div>
<pre><code>## Warning: Removed 3242 rows containing non-finite values (stat_boxplot).</code></pre>
<p><img src="07-relationships-categorical-variable_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>We can immediately see that men seem to report lower worry scores. Let’s look at the mean, standard deviation, and variance:</p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="relationships-with-categorical-variables.html#cb370-1" aria-hidden="true" tabindex="-1"></a>BCS0708 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span> </span>
<span id="cb370-2"><a href="relationships-with-categorical-variables.html#cb370-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_worry =</span> <span class="fu">round</span>(<span class="fu">mean</span>(tcviolent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),<span class="dv">1</span>), </span>
<span id="cb370-3"><a href="relationships-with-categorical-variables.html#cb370-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd_worry =</span> <span class="fu">round</span>(<span class="fu">sd</span>(tcviolent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),<span class="dv">1</span>), </span>
<span id="cb370-4"><a href="relationships-with-categorical-variables.html#cb370-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">var_worry =</span> <span class="fu">round</span>(<span class="fu">var</span>(tcviolent, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),<span class="dv">1</span>))</span></code></pre></div>
<pre><code>## # A tibble: 2 x 4
##   sex    mean_worry sd_worry var_worry
## * &lt;fct&gt;       &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 male         -0.3      0.9       0.7
## 2 female        0.3      1         1.1</code></pre>
<p>You can see here the mean for females is higher than that of male respondents, and we have quite high measures of dispersion as well. But this is all about our sample, and it is about our population which we want to draw inferences. Our hypothesis is that, in the population, there is a difference in the mean number of times males experience being drunk versus the number of times females experience being drunk.</p>
<!-- What we want then is a **difference-in-means** estimator. That is, we want to estimate the difference in means between the two groups in our population, from our sample. For this, we can use two-sample tests, based on a difference in means estimator to investigate our null hypothesis that the means are equal between the two populations.  -->
<p>Let’s elaborate with our example. Our research question is whether women are more afraid of crime. We are going to test a non-directional hypothesis and use an alpha level of .05. The test we use in this case is the t-test, which relies in the t-Student distribution.</p>
<p>In our previous weeks we had been using <em>the standard deviation of our sample</em> to estimate the standard error. (Remember: you divide the sample standard deviation by the square root of the sample mean). We learned that this approach works reasonably well when applying the Normal probability model to large samples. But with small samples using the sample standard deviation as an estimate of the standard error (so that we can compute the confidence interval) is problematic. The sample standard deviation also varies from sample to sample and this extra variation in smaller samples will mess up the computation of the margin of errors. William Gosset’s suggested we needed to use a different probability distribution for this cases, the <strong>t Student distribution</strong>.</p>
<p>You can learn more about this distribution and the work of Gosset in the suggested reading (he’s got a fun history, I promise, for one, he was head brewer at Guinness!!). The t Student distribution and the normal distribution are almost indistinguishable for large samples. In essence that means you will still multiply by 1.96. But with smaller sample sizes that value will be different if you use a normal distribution (z-distribution) or a t student distribution. Refer to the recommended textbook reading for further clarification.</p>
<blockquote>
<p><em>In order to use the t Student distribution we need to assume the data were randomly sampled and that the population distribution is unimodal and symmetric.</em></p>
</blockquote>
<p>In fact, this is probably a good time to engage with our assumptions made by the t-test.</p>
<p>This t test makes a number of assumptions:</p>
<ol style="list-style-type: decimal">
<li><p><em>We are comparing means or proportions</em> (that is our original variable is either a quantitative variable OR we have a binary variable with a large sample) across two groups. We are indeed doing so.</p></li>
<li><p>Population distribution: <em>normal distribution is assumed in both populations</em> (but this assumption can be relaxed if both samples are large). We will check this shortly. Because the tests make assumptions about the shape of the distribution we say that the t test is a <strong>parametric test</strong>. Tests that do not make this sort of assumptions are called non-parametric.</p></li>
<li><p>Independence assumptions: To use the method <em>the two groups must be independent of each other</em>.This assumption would be violated if, for example, one group would consist of husbands and the other group their wives. The values for couples might be related. But this is not the case with the BCS data. Similarly if we compare an individual before and after a treatment, his/her observations would be related. For these situations we would need a different test (the dependent t test, which we won’t cover).</p></li>
<li><p>Sampling method: the data were obtained through <em>independent random sampling</em>. The BCS uses a complex survey design which would require the use of special procedures for hypothesis testing. However, those special procedures are well beyond the scope of this course and would typically be covered in more advanced courses. Therefore, for convenience we will proceed as if this assumption is met.</p></li>
</ol>
<p>You may also want to check for outliers by plotting the data, for in some cases this may distort your results, particularly with smaller samples. So we are ok with 1 and 2, and are going to proceed as if 4 is met. What about normality? With large samples you can relax this assumption. However, you may want to also check if your sample data are normally distributed.</p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="relationships-with-categorical-variables.html#cb372-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(BCS0708, <span class="fu">aes</span>(<span class="at">x =</span> tcviolent, <span class="at">fill =</span> sex)) <span class="sc">+</span></span>
<span id="cb372-2"><a href="relationships-with-categorical-variables.html#cb372-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb372-3"><a href="relationships-with-categorical-variables.html#cb372-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 3242 rows containing non-finite values (stat_density).</code></pre>
<p><img src="07-relationships-categorical-variable_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The plotted density provide a visual tool for assessing the unimodality and the symmetry of the distribution. Later we will discuss a more elaborate graphical tool for assessing the normal condition (e.g., the normal probability plot).</p>
<p>For now let’s assume this is good enough. Then we would be ready to compute the t test.</p>
<div id="independent-sample-t-test" class="section level4" number="7.2.2.1">
<h4><span class="header-section-number">7.2.2.1</span> Independent Sample T-test</h4>
<p>I mentioned in the lecture video that there are different types of t-tests. We don’t cover one-sample t-tests, but we do cover two types of t-tests, independent (or unpaired) and dependent (or paired) sample t-tests.</p>
<p>In our example, we would like to know whether there is a difference between the mean fear of crime score between males and females. In this example, we use the <strong>independent sample t-test</strong> or <em>unpaired t-test</em>. The independent samples t-test compares two groups which are independent of one another. This means that the values for the outcome variable in one sample are not dependent on the values for the outcome variable in the other value. In this case, it’s pretty clear that men and women’s fear of crime is not related to one another. Dependent sample t-tests usually refer to repeated measurements of the same people, for example before and after an intervention. We will show such a case in the next section.</p>
<p>This test requires that the IV be a binary factor while the DV be either a ratio or interval variable and be normally distributed – unless <strong>N</strong> (the number of the sample) is large. Both variables meet the assumptions. We are interested in knowing whether there is a significant difference between males and females in the mean number of times they reported being drunk in the past year. Our null and alternative hypotheses are as follows:</p>
<p><span class="math inline">\(H_0\)</span>: There is no significant difference in fear of crime between males and females.</p>
<p><span class="math inline">\(H_A\)</span>: There is a significant difference in fear of crime between males and females.</p>
<p>We use the data frame, <code>BCS0708</code>, to address our research question: Is there a difference in the amount of worry about crime between males and females?</p>
<div id="activity-2-exploratory-data-analysis" class="section level5" number="7.2.2.1.1">
<h5><span class="header-section-number">7.2.2.1.1</span> Activity 2: Exploratory data analysis</h5>
<p>Before conducting our t-test, let’s look again at our variables of interest. We use the function <code>summarise()</code> to examine the sex variable ( <code>sex</code> ) and use the function <code>n()</code> to obtain frequencies:</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="relationships-with-categorical-variables.html#cb374-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Examining distribution of sex variable</span></span>
<span id="cb374-2"><a href="relationships-with-categorical-variables.html#cb374-2" aria-hidden="true" tabindex="-1"></a>BCS0708 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div>
<pre><code>## # A tibble: 2 x 2
##   sex        n
## * &lt;fct&gt;  &lt;int&gt;
## 1 male    5307
## 2 female  6369</code></pre>
<p>According to the output, there are 5307 males and 6369 females.</p>
<p>Now we check out our dependent variable <code>tcviolent</code> using the <code>skim()</code> function from the <code>skimr</code> package familiar from lesson 4:</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="relationships-with-categorical-variables.html#cb376-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use skim() function from skimr package to examine drunk variable </span></span>
<span id="cb376-2"><a href="relationships-with-categorical-variables.html#cb376-2" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(BCS0708, tcviolent)</span></code></pre></div>
<table style="width:100%;">
<colgroup>
<col width="6%" />
<col width="9%" />
<col width="6%" />
<col width="9%" />
<col width="8%" />
<col width="7%" />
<col width="7%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_type</th>
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">numeric.mean</th>
<th align="right">numeric.sd</th>
<th align="right">numeric.p0</th>
<th align="right">numeric.p25</th>
<th align="right">numeric.p50</th>
<th align="right">numeric.p75</th>
<th align="right">numeric.p100</th>
<th align="left">numeric.hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">tcviolent</td>
<td align="right">3242</td>
<td align="right">0.7223364</td>
<td align="right">0.0455821</td>
<td align="right">1.00436</td>
<td align="right">-2.35029</td>
<td align="right">-0.6718318</td>
<td align="right">-0.116783</td>
<td align="right">0.53989</td>
<td align="right">3.805476</td>
<td align="left">▁▇▅▂▁</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb377"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb377-1"><a href="relationships-with-categorical-variables.html#cb377-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking out DV by variable ‘sex’</span></span>
<span id="cb377-2"><a href="relationships-with-categorical-variables.html#cb377-2" aria-hidden="true" tabindex="-1"></a>BCS0708 <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span> <span class="fu">skim</span>(tcviolent)</span></code></pre></div>
<table>
<colgroup>
<col width="6%" />
<col width="9%" />
<col width="4%" />
<col width="6%" />
<col width="9%" />
<col width="8%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_type</th>
<th align="left">skim_variable</th>
<th align="left">sex</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">numeric.mean</th>
<th align="right">numeric.sd</th>
<th align="right">numeric.p0</th>
<th align="right">numeric.p25</th>
<th align="right">numeric.p50</th>
<th align="right">numeric.p75</th>
<th align="right">numeric.p100</th>
<th align="left">numeric.hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">tcviolent</td>
<td align="left">male</td>
<td align="right">1348</td>
<td align="right">0.7459959</td>
<td align="right">-0.2738322</td>
<td align="right">0.8608103</td>
<td align="right">-2.35029</td>
<td align="right">-0.8935347</td>
<td align="right">-0.4361864</td>
<td align="right">0.1958046</td>
<td align="right">3.805476</td>
<td align="left">▂▇▃▁▁</td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">tcviolent</td>
<td align="left">female</td>
<td align="right">1894</td>
<td align="right">0.7026221</td>
<td align="right">0.3281656</td>
<td align="right">1.0371477</td>
<td align="right">-2.35029</td>
<td align="right">-0.4016314</td>
<td align="right">0.2326113</td>
<td align="right">0.9308914</td>
<td align="right">3.557671</td>
<td align="left">▁▇▇▃▁</td>
</tr>
</tbody>
</table>
<p>From the output, it seems that men have a lower average fear of crime scored than women do, specifically a difference of a score of 0.602. The difference between the medians is even larger. 0.669. So this is about our sample - but the true question is - Is this a statistically significant difference?</p>
<p>Our observation of a difference between means prompts us to test whether this difference is an actual difference, or if it is attributed to chance.</p>
</div>
<div id="activity-3-testing-for-equality-of-variance" class="section level5" number="7.2.2.1.2">
<h5><span class="header-section-number">7.2.2.1.2</span> Activity 3: Testing for equality of variance</h5>
<p>Before we conduct the test to tell us this, we conduct the <strong>test for equality of variance</strong>. This is an F-test that evaluates the null hypothesis that the variances of the two groups are equal. When we want to compare variances, we conduct this test as the variances may affect how we specify our t-test.</p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="relationships-with-categorical-variables.html#cb378-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DV comes first in code, then the IV</span></span>
<span id="cb378-2"><a href="relationships-with-categorical-variables.html#cb378-2" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(BCS0708<span class="sc">$</span>tcviolent <span class="sc">~</span> BCS0708<span class="sc">$</span>sex)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  BCS0708$tcviolent by BCS0708$sex
## F = 0.68886, num df = 3958, denom df = 4474, p-value &lt; 2.2e-16
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.6484653 0.7318632
## sample estimates:
## ratio of variances 
##          0.6888643</code></pre>
<p>The information to focus on in the output are the alternative hypothesis, the F-statistic, and associated p-value. The alternative hypothesis states that the variances are not equal to 1, meaning they are not equal to each other. The p-value is very small, so we reject the null hypothesis that the variances are equal to each other. Conducting the F-test is an important step before the t-test. As one of the assumptions for the t-test are violated, we must do something.</p>
<p>This might be familiar from the video lecture as well… So what can we do? Well there is a parameter in the <code>t.test()</code> function, where we can specify whether the equality of variance assumption is met or not. In this case, this assumption is violated, and so we must set <code>var.equal</code> to <code>FALSE</code> in the following independent sample t-test.</p>
</div>
<div id="activity-4-independent-sample-t-test" class="section level5" number="7.2.2.1.3">
<h5><span class="header-section-number">7.2.2.1.3</span> Activity 4: Independent sample t-test</h5>
<p>It is now time to carry out our t-test. For this we use the <code>t.test()</code> function which performs both the one and two sample t-tests on vectors of data. It can also perform paired and independent samples t-tests, by modifying the <code>paired=</code> parameter. This is default value set to <code>FALSE</code> so we don’t need to worry about that here. All we need is our dependent variable (numeric) and our independent variable (categorical) separated by a tilda (<code>~</code>), and the <code>var.equal</code> parameter set to <code>FALSE</code>, as discussed above!</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="relationships-with-categorical-variables.html#cb380-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run the t-test with var.equal option set to false </span></span>
<span id="cb380-2"><a href="relationships-with-categorical-variables.html#cb380-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(BCS0708<span class="sc">$</span>tcviolent <span class="sc">~</span> BCS0708<span class="sc">$</span>sex, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  BCS0708$tcviolent by BCS0708$sex
## t = -29.114, df = 8398.3, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.6425300 -0.5614656
## sample estimates:
##   mean in group male mean in group female 
##           -0.2738322            0.3281656</code></pre>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="relationships-with-categorical-variables.html#cb382-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can save your results in an object, too, to refer back to later:</span></span>
<span id="cb382-2"><a href="relationships-with-categorical-variables.html#cb382-2" aria-hidden="true" tabindex="-1"></a>t_test_results <span class="ot">&lt;-</span> <span class="fu">t.test</span>(BCS0708<span class="sc">$</span>tcviolent <span class="sc">~</span> BCS0708<span class="sc">$</span>sex, <span class="at">var.equal =</span> <span class="cn">FALSE</span>)</span>
<span id="cb382-3"><a href="relationships-with-categorical-variables.html#cb382-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb382-4"><a href="relationships-with-categorical-variables.html#cb382-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Print independent t-test results </span></span>
<span id="cb382-5"><a href="relationships-with-categorical-variables.html#cb382-5" aria-hidden="true" tabindex="-1"></a>t_test_results</span></code></pre></div>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  BCS0708$tcviolent by BCS0708$sex
## t = -29.114, df = 8398.3, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.6425300 -0.5614656
## sample estimates:
##   mean in group male mean in group female 
##           -0.2738322            0.3281656</code></pre>
<p>From the output, focus on the means, alternative hypothesis, the t-statistics, the p-value, and the 95% confidence interval (CI).</p>
<p>First, the means show that males score an average score of -0.2738322 on this fear of crime measure, while females score average of 0.3281656 - this is the same output we got from our descriptive statistics. Second, the alternative hypothesis (a true difference in means) is not equal to 0, which is what we expect if there is no difference between the two groups. Third, the t-statistic reports -29.1142624 with an associated p-value which is very small, much smaller than our <span class="math inline">\(\alpha\)</span> = 0.05, so we reject the null hypothesis.</p>
<p>In other words, the p value here is very close to 0 and therefore we can reject the null hypothesis that the difference in the population is 0. The observed difference in this sample would have been rather implausible if the null hypothesis were true. Therefore, here we would argue that our evidence suggests that we can reject the null hypothesis. We can say that there is a <strong>statistically significant</strong> difference between fear of violent crime for men and women in England and Wales.</p>
<p>It is important you remember this: <strong>the p value is not the probability that the null hypothesis is true</strong>. Imagine that our p value was 0.04. As tempting as it may be to say that a p value of 0.04 means there is a 4% chance that the null hypothesis is true, that just isn’t right. The only thing that we are in a position to state is: given the null hypothesis, there is a 4% chance of observing the difference that we have actually observed (or one more unlikely).</p>
<p>Fourth, the 95% CI allows us to make an estimate which tells us about the value of the difference in means in the population. So from our sample we estimate that the difference in fear of crime scores between men and women is somewhere between 0.56 and 0.64 points.</p>
<p>Is this large or small? Interpreting this in raw format, in the original scale, requires some subjective judgement. And I mean subjective in a positive way, it means you have to think about it. Unfortunately, the original scale here uses an artificial metric that is difficult to evaluate on its own.</p>
</div>
<div id="activity-5-standardised-effect-size-cohens-d" class="section level5" number="7.2.2.1.4">
<h5><span class="header-section-number">7.2.2.1.4</span> Activity 5: Standardised effect size: Cohen’s D</h5>
<p>We can always look at <strong>standardised measure of the effect size</strong>. You will find a number of standardised measures of effect size. They aim to give you a sense of how large these differences are by using a standardised metric. We are just going to use one of them, Cohen’s d, for this scenario. We can obtain this measure with the <code>cohen.d()</code> function from the <code>effsize</code> package, which you will have to install.</p>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="relationships-with-categorical-variables.html#cb384-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(effsize)</span>
<span id="cb384-2"><a href="relationships-with-categorical-variables.html#cb384-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cohen.d</span>(BCS0708<span class="sc">$</span>tcviolent <span class="sc">~</span> BCS0708<span class="sc">$</span>sex)</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: -0.6281126 (medium)
## 95 percent confidence interval:
##      lower      upper 
## -0.6719205 -0.5843047</code></pre>
<p>The output suggest that the Cohen’s d estimate is a medium effect size. Cohen proposed a set of rules of thumb to interpret the d statistic: an effect size (in absolute value) of 0.2 to 0.3 might be a “small” effect, around 0.5 a “medium” effect and 0.8 to infinity, a “large” effect. However, keep in mind these rules are not absolute. In some fields of research and in relation to some problems the rules of thumb may be slightly different. You need, in professional practice, to be alert to those nuances by being familiar to the rules that other researchers use in your particular area of work.</p>
<p>How do we write our results up? We could say the following (and in case you are wondering, we covered last week how to obtain the standard errors using the psych package):</p>
<blockquote>
<p>“On average, males have a lower score of fear of violent crime (M=-.27, SE=.01) than the female group (M=.33, SE=.02). Using an alpha level of 0.05, this difference was significant (t=-29.11, p=.000) and represented a medium-sized effect (Cohen’s d=-0.63).”</p>
</blockquote>
<p>This is what you would write in your “Findings” section. In your “Conclusions” you would need to discuss what the theoretical or practical implications of this finding are; connecting it to existing theoretical debates. If your test had been insignificant (a p value greater than 0.05) then you would have to say so: “the difference was insignificant, thus, we failed to reject the null hypothesis”.</p>
<p>One important thing to remember is that when doing hypothesis testing there is always the possibility of error. Our statements are probabilistic. We could be rejecting the null hypothesis when we shouldn’t (false positive or Type I error), if we are using an alpha level of .05 this may happen 5% of the time, or we may fail to reject the null hypothesis when we should (false negative or Type II error).</p>
<hr />
</div>
</div>
<div id="dependent-sample-t-test" class="section level4" number="7.2.2.2">
<h4><span class="header-section-number">7.2.2.2</span> Dependent Sample T-test</h4>
<p>When you are interested in comparing means of two groups that are related to each other, the <strong>dependent sample t-test</strong> or <em>paired sample t-test</em> is appropriate. What this means is that the responses are paired together because there is a prior connection between them. For example, I have two groups where the first group comprises test scores before an intervention and the second group comprises test scores after that intervention of the same people from the first group – a dependent sample t-test is called for.</p>
<p>In fact, let’s explore this example.</p>
<div id="activity-6-paired-sample-t-test" class="section level5" number="7.2.2.2.1">
<h5><span class="header-section-number">7.2.2.2.1</span> Activity 6: Paired sample t-test</h5>
<p>Let’s create a synthetic data set again of a hypothetical intervention for at-risk youth in Manchester. Let’s say we have identified 100 at risk young people, and we exposed them to an intervention designed to stop them from re-offending. Both before and after the intervention, we ask them to take a test aimed to measure their compliance with the law. Let’s create this data set now.</p>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="relationships-with-categorical-variables.html#cb386-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">subject_id =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>), </span>
<span id="cb386-2"><a href="relationships-with-categorical-variables.html#cb386-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">prepost =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">&quot;pre&quot;</span>, <span class="dv">100</span>), <span class="fu">rep</span>(<span class="st">&quot;post&quot;</span>, <span class="dv">100</span>)),</span>
<span id="cb386-3"><a href="relationships-with-categorical-variables.html#cb386-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">compliance_score =</span> <span class="fu">c</span>(<span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">30</span>, <span class="dv">10</span>), <span class="fu">rnorm</span>(<span class="dv">100</span>, <span class="dv">60</span>, <span class="dv">14</span>)))</span></code></pre></div>
<p>We now have our dataframe called <code>df</code> which contains 200 observations, it contains the scores of our young people on the compliance test in the start of our experiment, and then again after the intervention. You can consider this two waves of a survey. In this example, we compare the behaviours of youth from Wave 1 to Wave 2 to address the research question: <em>‘Do the comliance scores of the young people change after our intervention?’</em> Our non-directional null and alternative hypotheses are as follows:</p>
<p><span class="math inline">\(H_0\)</span>: There is no significant difference in the compliance scores between Wave 1 (pre intervention) and Wave 2 (post intervention).</p>
<p><span class="math inline">\(H_A\)</span>: There is a significant difference in the compliance scores between Wave 1 (pre intervention) and Wave 2 (post intervention).</p>
<p>As responses from both Waves 1 and 2 are required, cases without this pair of responses will be dropped automatically when our analysis is conducted. This t-test also requires the DV to be stored in two separate variables and the level of measurement to be ratio or interval. These assumptions are met. How about equality of variance?</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="relationships-with-categorical-variables.html#cb387-1" aria-hidden="true" tabindex="-1"></a><span class="co"># DV comes first in code, then the IV</span></span>
<span id="cb387-2"><a href="relationships-with-categorical-variables.html#cb387-2" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(df<span class="sc">$</span>compliance_score <span class="sc">~</span> df<span class="sc">$</span>prepost)</span></code></pre></div>
<pre><code>## 
##  F test to compare two variances
## 
## data:  df$compliance_score by df$prepost
## F = 2.215, num df = 99, denom df = 99, p-value = 9.771e-05
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  1.490329 3.291975
## sample estimates:
## ratio of variances 
##           2.214978</code></pre>
<p>Seems that we have unequal variance again, so we must specify this.</p>
<p>Now, for the dependent sample t-test whereby we use the variables <code>prepost</code> indicating whether the answer is from wave 1 (pre-intervention) or wave 2 (post-intervention) and <code>compliance_score</code>, the score the young person achieved on the compliance questionnaire.</p>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="relationships-with-categorical-variables.html#cb389-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us run the dependent samples t-test </span></span>
<span id="cb389-2"><a href="relationships-with-categorical-variables.html#cb389-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Specify TRUE for the paired option </span></span>
<span id="cb389-3"><a href="relationships-with-categorical-variables.html#cb389-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(compliance_score <span class="sc">~</span> prepost, <span class="at">data =</span> df, <span class="at">var.equal =</span> <span class="cn">FALSE</span>, <span class="at">paired=</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  compliance_score by prepost
## t = 17.756, df = 99, p-value &lt; 2.2e-16
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  29.50827 36.93290
## sample estimates:
## mean of the differences 
##                33.22059</code></pre>
<p>The results indicate that we can reject the null hypothesis as the p-value is above <span class="math inline">\(\alpha = 0.05\)</span>. We conclude that there is a significant difference in compliance score before and after our intervention between the paired Waves 1 and 2 responses. Looking good for our intervention. It seems that we can expect the compliance score to improve between 28.2 to 34.6 points! Is this a big number? Let’s use the Cohen’s d measure to find out. You might notice two things different from the unpaired test. First, we specify the parameter <code>paired= TRUE</code>. And second, we tell the formula what ID it can use to match our participants in the pre group and in the post group. This is done with the <code>Subject()</code> function appended with the <code>|</code> operator, and inside we put our subject_id variable (each young person’s unique identifier so we can find them in wave 1 and wave 2).</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="relationships-with-categorical-variables.html#cb391-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cohen.d</span>(compliance_score <span class="sc">~</span> prepost <span class="sc">|</span> <span class="fu">Subject</span>(subject_id), <span class="at">data =</span> df, <span class="at">paired=</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
## Cohen&#39;s d
## 
## d estimate: 2.484869 (large)
## 95 percent confidence interval:
##    lower    upper 
## 1.926939 3.042799</code></pre>
<p>Happy times, this is a statistically significant (so we can generalise) large effect (Cohen’s d estimate: 2.520966 (large)). Our intervention seems to be associated with an increased score in compliance in our follow-up questionnaire. But still, beware about inferring causation. There may have been other factors at play (for example, what if they all just aged out of crime, growing older and more compliant). A randomised control trial might help with alleviating these competing explanations…!</p>
<hr />
</div>
</div>
</div>
<div id="chi-square" class="section level3" number="7.2.3">
<h3><span class="header-section-number">7.2.3</span> Chi-square</h3>
<p>The <strong>chi-square statistic</strong> is a test of statistical significance for two categorical variables. It tells us how much the observed distribution differs from the one expected under the null hypothesis. To begin to even understand this definition, we start with cross tabulations or <strong>contingency tables</strong>. These appear as a table that shows the crossed frequency distributions of more than one variable simultaneously and are particularly helpful in exploring relationships between categorical variables that do not have too many categories. Specifically, cross-tabulations have the same meaning except they are applied only to relationships between two categorical variables.</p>
<p>In earlier sessions we have covered how to run frequency distributions using the <code>table()</code> function. Cross tabulations, also called <strong>contingency tables</strong>, are essentially crossed frequency distributions, where you plot the frequency distributions of more than one variable simultaneously. This semester we are only going to explore <strong>two-way cross tabulations</strong>, that is contingency tables where we plot the frequency distribution of two variables at the same time. Frequency distributions are a useful way of exploring categorical variables that do not have too many categories. By extension, cross tabulations are a useful way of exploring relationships between two categorical variables that do not have too many levels or categories.</p>
<p>As we learned during the first week we can get results from R in a variety of ways. You can produce basic tables with some of the core functions in R. However, in order to produce the sort of cross-tabs we will use, I suggest you install and load the package <code>gmodels</code>. This package allows you to produce cross tabulations in a format similar to the one used by commercial statistical packages SPSS and SAS. Since some of you may have some previous experience with SPSS we will use the SPSS format. Cross-tabs with this package are more useful for our purposes than the default you may get with the core R <code>table()</code> function.</p>
<div id="activity-7-crosstabs" class="section level5" number="7.2.3.0.1">
<h5><span class="header-section-number">7.2.3.0.1</span> Activity 7: Crosstabs</h5>
<p>Let’s explore some crosstabls by producing a cross tabulation of victimisation ( <code>bcsvictim</code> ) and whether rubbish is a problem in the area where the respondent lives (<code>rubbcomm</code>). According to <em>Broken Windows Theory</em>, proposed by James Q. Wilson and George Kelling, we should see a relationship between these two variables.</p>
<p>First, we check out our variables:</p>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="relationships-with-categorical-variables.html#cb393-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seeing what class these variables are</span></span>
<span id="cb393-2"><a href="relationships-with-categorical-variables.html#cb393-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(BCS0708<span class="sc">$</span>bcsvictim)</span></code></pre></div>
<pre><code>## [1] &quot;haven_labelled&quot; &quot;vctrs_vctr&quot;     &quot;double&quot;</code></pre>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="relationships-with-categorical-variables.html#cb395-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(BCS0708<span class="sc">$</span>rubbcomm)</span></code></pre></div>
<pre><code>## [1] &quot;haven_labelled&quot; &quot;vctrs_vctr&quot;     &quot;double&quot;</code></pre>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="relationships-with-categorical-variables.html#cb397-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 0-Not victim of crime; 1-Victim of crime</span></span>
<span id="cb397-2"><a href="relationships-with-categorical-variables.html#cb397-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(BCS0708<span class="sc">$</span>bcsvictim) </span></code></pre></div>
<pre><code>## $label
## [1] &quot;experience of any crime in the previous 12 months&quot;
## 
## $format.stata
## [1] &quot;%8.0g&quot;
## 
## $class
## [1] &quot;haven_labelled&quot; &quot;vctrs_vctr&quot;     &quot;double&quot;        
## 
## $labels
## not a victim of crime       victim of crime 
##                     0                     1</code></pre>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb399-1"><a href="relationships-with-categorical-variables.html#cb399-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 5-point Likert-scale ranging from 1 (very common) to 4 (not common) </span></span>
<span id="cb399-2"><a href="relationships-with-categorical-variables.html#cb399-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attributes</span>(BCS0708<span class="sc">$</span>rubbcomm)</span></code></pre></div>
<pre><code>## $label
## [1] &quot;in the immediate area how common is litter\\rubbish&quot;
## 
## $format.stata
## [1] &quot;%8.0g&quot;
## 
## $class
## [1] &quot;haven_labelled&quot; &quot;vctrs_vctr&quot;     &quot;double&quot;        
## 
## $labels
##       very common     fairly common   not very common not at all common 
##                 1                 2                 3                 4 
##         not coded 
##                 5</code></pre>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="relationships-with-categorical-variables.html#cb401-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(BCS0708<span class="sc">$</span>bcsvictim)</span></code></pre></div>
<pre><code>## 
##    0    1 
## 9318 2358</code></pre>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="relationships-with-categorical-variables.html#cb403-1" aria-hidden="true" tabindex="-1"></a><span class="co"># If you want the frequency distribution with labels, use ‘as_factor ()’</span></span>
<span id="cb403-2"><a href="relationships-with-categorical-variables.html#cb403-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">as_factor</span>(BCS0708<span class="sc">$</span>bcsvictim))</span></code></pre></div>
<pre><code>## 
## not a victim of crime       victim of crime 
##                  9318                  2358</code></pre>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="relationships-with-categorical-variables.html#cb405-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">as_factor</span>(BCS0708<span class="sc">$</span>rubbcomm))</span></code></pre></div>
<pre><code>## 
##       very common     fairly common   not very common not at all common 
##               204              1244              4154              5463 
##         not coded 
##                 0</code></pre>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="relationships-with-categorical-variables.html#cb407-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking for any missing values using ‘sum ()’ to count number of NA data</span></span>
<span id="cb407-2"><a href="relationships-with-categorical-variables.html#cb407-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(BCS0708<span class="sc">$</span>bcsvictim))</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="relationships-with-categorical-variables.html#cb409-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Value of 5 indicates missing</span></span>
<span id="cb409-2"><a href="relationships-with-categorical-variables.html#cb409-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(BCS0708<span class="sc">$</span>rubbcomm))</span></code></pre></div>
<pre><code>## [1] 611</code></pre>
<p>For the DV, we are missing 611 cases. For this course unit, keep in mind that all the statistical tests you will learn rely on <strong>full cases analysis</strong> whereby the tests exclude cases that have missing values. There are appropriate ways in dealing with missing data but this is beyond the scope of this class.</p>
<p>There are a couple of ways of producing cross tabulations in <code>R</code>:</p>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="relationships-with-categorical-variables.html#cb411-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Basic R</span></span>
<span id="cb411-2"><a href="relationships-with-categorical-variables.html#cb411-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">as_factor</span>(BCS0708<span class="sc">$</span>bcsvictim), </span>
<span id="cb411-3"><a href="relationships-with-categorical-variables.html#cb411-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">as_factor</span>(BCS0708<span class="sc">$</span>rubbcomm))</span></code></pre></div>
<pre><code>##                        
##                         very common fairly common not very common
##   not a victim of crime         141           876            3173
##   victim of crime                63           368             981
##                        
##                         not at all common not coded
##   not a victim of crime              4614         0
##   victim of crime                     849         0</code></pre>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="relationships-with-categorical-variables.html#cb413-1" aria-hidden="true" tabindex="-1"></a><span class="co"># dplyr</span></span>
<span id="cb413-2"><a href="relationships-with-categorical-variables.html#cb413-2" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> BCS0708 <span class="sc">%&gt;%</span> <span class="co"># ‘fct_explicit_na()’ function from the forcats package to get an explicit factor level from our # missing values</span></span>
<span id="cb413-3"><a href="relationships-with-categorical-variables.html#cb413-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="fu">fct_explicit_na</span>(<span class="fu">as_factor</span>(rubbcomm))) <span class="sc">%&gt;%</span> </span>
<span id="cb413-4"><a href="relationships-with-categorical-variables.html#cb413-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># We use the function ‘mean()’ as the variable is binary and because it is coded as 0 and 1.</span></span>
<span id="cb413-5"><a href="relationships-with-categorical-variables.html#cb413-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>( <span class="at">count =</span> <span class="fu">n</span>(), <span class="at">outcome_1 =</span> <span class="fu">mean</span>(bcsvictim))</span>
<span id="cb413-6"><a href="relationships-with-categorical-variables.html#cb413-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb413-7"><a href="relationships-with-categorical-variables.html#cb413-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Auto-print the results stored in the newly created object </span></span>
<span id="cb413-8"><a href="relationships-with-categorical-variables.html#cb413-8" aria-hidden="true" tabindex="-1"></a>results</span></code></pre></div>
<pre><code>## # A tibble: 5 x 3
##   `fct_explicit_na(as_factor(rubbcomm))` count outcome_1
## * &lt;fct&gt;                                  &lt;int&gt;     &lt;dbl&gt;
## 1 very common                              204     0.309
## 2 fairly common                           1244     0.296
## 3 not very common                         4154     0.236
## 4 not at all common                       5463     0.155
## 5 (Missing)                                611     0.159</code></pre>
<p>The <code>dplyr</code> coding seems more complicated than that of <code>basic R</code> but its output is clearer to read than the one produced by <code>R</code>, and it is more detailed. The proportion of victimised individuals are within each of the levels of the categorical, ordered measure of rubbish in the area. Victimisation appears higher (31%) in the areas where rubbish in the streets is a very common problem.</p>
<p>To further explore contingency tables, the best package for this is <code>gmodels</code>. It allows you to produce cross tabulations in a format similar to the one used by commercial statistical packages SPSS and SAS. We use the function <code>CrossTable ()</code> , then the <code>with()</code> function to identify the data frame at the outset instead of having to include it with each variable.</p>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb415-1"><a href="relationships-with-categorical-variables.html#cb415-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gmodels)</span>
<span id="cb415-2"><a href="relationships-with-categorical-variables.html#cb415-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb415-3"><a href="relationships-with-categorical-variables.html#cb415-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the rows in your table (rubbcomm) and then the variable that will define the columns # (bcsvictim)</span></span>
<span id="cb415-4"><a href="relationships-with-categorical-variables.html#cb415-4" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(BCS0708, <span class="fu">CrossTable</span>(<span class="fu">as_factor</span>(rubbcomm), </span>
<span id="cb415-5"><a href="relationships-with-categorical-variables.html#cb415-5" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">as_factor</span>(bcsvictim), </span>
<span id="cb415-6"><a href="relationships-with-categorical-variables.html#cb415-6" aria-hidden="true" tabindex="-1"></a><span class="at">prop.chisq =</span> <span class="cn">FALSE</span>, </span>
<span id="cb415-7"><a href="relationships-with-categorical-variables.html#cb415-7" aria-hidden="true" tabindex="-1"></a><span class="at">format =</span> <span class="fu">c</span>(<span class="st">&quot;SPSS&quot;</span>)))</span></code></pre></div>
<pre><code>## 
##    Cell Contents
## |-------------------------|
## |                   Count |
## |             Row Percent |
## |          Column Percent |
## |           Total Percent |
## |-------------------------|
## 
## Total Observations in Table:  11065 
## 
##                     | as_factor(bcsvictim) 
## as_factor(rubbcomm) | not a victim of crime  |       victim of crime  |             Row Total | 
## --------------------|-----------------------|-----------------------|-----------------------|
##         very common |                  141  |                   63  |                  204  | 
##                     |               69.118% |               30.882% |                1.844% | 
##                     |                1.602% |                2.786% |                       | 
##                     |                1.274% |                0.569% |                       | 
## --------------------|-----------------------|-----------------------|-----------------------|
##       fairly common |                  876  |                  368  |                 1244  | 
##                     |               70.418% |               29.582% |               11.243% | 
##                     |                9.950% |               16.276% |                       | 
##                     |                7.917% |                3.326% |                       | 
## --------------------|-----------------------|-----------------------|-----------------------|
##     not very common |                 3173  |                  981  |                 4154  | 
##                     |               76.384% |               23.616% |               37.542% | 
##                     |               36.040% |               43.388% |                       | 
##                     |               28.676% |                8.866% |                       | 
## --------------------|-----------------------|-----------------------|-----------------------|
##   not at all common |                 4614  |                  849  |                 5463  | 
##                     |               84.459% |               15.541% |               49.372% | 
##                     |               52.408% |               37.550% |                       | 
##                     |               41.699% |                7.673% |                       | 
## --------------------|-----------------------|-----------------------|-----------------------|
##        Column Total |                 8804  |                 2261  |                11065  | 
##                     |               79.566% |               20.434% |                       | 
## --------------------|-----------------------|-----------------------|-----------------------|
## 
## </code></pre>
<p>Cells for the central two columns are the total number of cases in each category, comprising the <em>row percentages</em>, the <em>column percentages</em>, and the <em>total percentages</em>.</p>
<p>The contingency table shows that 63 people in the category ‘rubbish is very common’ were victims of a crime; this represents 30.88% of all the people in the ‘rubbish is very common’ category (your row percent), 2.79% of all the people in the ‘victim of a crime’ category (your column percent), and 0.57% of all the people in the sample.</p>
<p>There is quite a lot of proportions that the contingency table will churn out, but you are only interested in the proportions or percentages that allow you to make meaningful comparisons. Again, this is where talk about independent and dependent variables come in. Although talking about variables like this is not common in these analyses as they would be, say, in regression, an analysis we learn later, it is good to get into the mindset of arranging our variables in this way.</p>
<p>If you believe in broken windows theory, you will think of victimisation as the outcome we want to explain (Y) and rubbish in the area as a possible explanation for the variation in victimisation (X). If so, you will need to request percentages that allow you to make comparisons across <code>rubbcomm</code> for the outcome, <code>bcsvictim</code>.</p>
<p>This is a very <strong>important</strong> point: often, cross tabulations are interpreted the wrong way because percentages were specified incorrectly. Two rules to help ensure you interpret cross-tabs (short for cross tabulations) correctly:</p>
<ol style="list-style-type: decimal">
<li><p>If your dependent variable is defining the rows, then you ask for the <em>column percentages</em></p></li>
<li><p>If your dependent variable is defining the columns, then you ask for the <em>row percentages</em></p></li>
</ol>
<p>Also, <em>you make the comparisons across the right percentages in the direction where they do not add up to a hundred percent</em>. For example, 30.88% of people who live in areas where rubbish is very common have been victimised, whereas only 15.54% of people who live in areas where rubbish is not at all common have been victimised in the previous year. To make it easier, we can ask <code>R</code> to only give us the percentages in which we are interested:</p>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb417-1"><a href="relationships-with-categorical-variables.html#cb417-1" aria-hidden="true" tabindex="-1"></a><span class="co"># prop.c is column and prop.t is total</span></span>
<span id="cb417-2"><a href="relationships-with-categorical-variables.html#cb417-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(BCS0708, <span class="fu">CrossTable</span>(<span class="fu">as_factor</span>(rubbcomm), </span>
<span id="cb417-3"><a href="relationships-with-categorical-variables.html#cb417-3" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">as_factor</span>(bcsvictim), </span>
<span id="cb417-4"><a href="relationships-with-categorical-variables.html#cb417-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">prop.chisq =</span> <span class="cn">FALSE</span>, <span class="at">prop.c =</span> <span class="cn">FALSE</span>, <span class="at">prop.t =</span> <span class="cn">FALSE</span>, <span class="at">format =</span></span>
<span id="cb417-5"><a href="relationships-with-categorical-variables.html#cb417-5" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">c</span>(<span class="st">&quot;SPSS&quot;</span>)))</span></code></pre></div>
<pre><code>## 
##    Cell Contents
## |-------------------------|
## |                   Count |
## |             Row Percent |
## |-------------------------|
## 
## Total Observations in Table:  11065 
## 
##                     | as_factor(bcsvictim) 
## as_factor(rubbcomm) | not a victim of crime  |       victim of crime  |             Row Total | 
## --------------------|-----------------------|-----------------------|-----------------------|
##         very common |                  141  |                   63  |                  204  | 
##                     |               69.118% |               30.882% |                1.844% | 
## --------------------|-----------------------|-----------------------|-----------------------|
##       fairly common |                  876  |                  368  |                 1244  | 
##                     |               70.418% |               29.582% |               11.243% | 
## --------------------|-----------------------|-----------------------|-----------------------|
##     not very common |                 3173  |                  981  |                 4154  | 
##                     |               76.384% |               23.616% |               37.542% | 
## --------------------|-----------------------|-----------------------|-----------------------|
##   not at all common |                 4614  |                  849  |                 5463  | 
##                     |               84.459% |               15.541% |               49.372% | 
## --------------------|-----------------------|-----------------------|-----------------------|
##        Column Total |                 8804  |                 2261  |                11065  | 
## --------------------|-----------------------|-----------------------|-----------------------|
## 
## </code></pre>
<p>Now with this output, we only see the row percentages. <strong>Marginal frequencies</strong> appear as the right column and bottom row. <em>Row marginals</em> show the total number of cases in each row. For example, 204 people perceive rubbish as very common in the area where they are living and 1,244 perceive rubbish as fairly common in their area. <em>Column marginals</em> show the total number of cases in each column: 8,804 non-victims and 2,261 victims.</p>
<p>In the central cells, these are the total number for each combination of categories. For example, for row percentages, 63 people who perceive rubbish as very common in their area and who are a victim of a crime represent 30.88% of all people who have reported that rubbish is common (63 out of 204). For column percentages (shown previously), 63 people who live in areas where rubbish is very common and are victims represent 2.79% of all people who were victims of crime (63 out of 2,261).</p>
</div>
<div id="acivity-8-comparing-categorican-variables-with-chi-square-test" class="section level5" number="7.2.3.0.2">
<h5><span class="header-section-number">7.2.3.0.2</span> Acivity 8: Comparing categorican variables with Chi-square test</h5>
<p>We now have an understanding of cross-tabs so that we can interpret the <strong>chi-square statistic</strong>. Our null and alternative hypotheses are as follows:</p>
<p><span class="math inline">\(H_0\)</span>: Victimisation and how common rubbish is in the area are not related to each other. (They are considered independent of each other.)</p>
<p><span class="math inline">\(H_A\)</span>: Victimisation and how common rubbish is in the area are significantly related to each other. (They are considered dependent on each other.)</p>
<p>The test does the following:
(1) compares these expected frequencies with the ones we actually observe in each of the cells, (2) then averages the differences across the cells, and (3) produces a standardised value, <em>χ</em><span class="math inline">\(^2\)</span> (the chi-square statistic).</p>
<p>We then look at a chi-square distribution to see how probable or improbable this value is. But, in practice, the p-value helps us ascertain this more quickly.</p>
<p><strong>Expected frequencies</strong> are the number of cases you would expect to see in each cell within a contingency table if there was no relationship between the two variables. <strong>Observed frequencies</strong> are the cases that we actually see in our sample. We use the <code>CrossTable ()</code> function again:</p>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="relationships-with-categorical-variables.html#cb419-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(BCS0708, <span class="fu">CrossTable</span>(<span class="fu">as_factor</span>(rubbcomm), </span>
<span id="cb419-2"><a href="relationships-with-categorical-variables.html#cb419-2" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">as_factor</span>(bcsvictim), </span>
<span id="cb419-3"><a href="relationships-with-categorical-variables.html#cb419-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">expected =</span> <span class="cn">TRUE</span>, <span class="at">prop.c =</span> <span class="cn">FALSE</span>, <span class="at">prop.t =</span> <span class="cn">FALSE</span>, <span class="at">format =</span></span>
<span id="cb419-4"><a href="relationships-with-categorical-variables.html#cb419-4" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">c</span>(<span class="st">&quot;SPSS&quot;</span>) ))</span></code></pre></div>
<pre><code>## 
##    Cell Contents
## |-------------------------|
## |                   Count |
## |         Expected Values |
## | Chi-square contribution |
## |             Row Percent |
## |-------------------------|
## 
## Total Observations in Table:  11065 
## 
##                     | as_factor(bcsvictim) 
## as_factor(rubbcomm) | not a victim of crime  |       victim of crime  |             Row Total | 
## --------------------|-----------------------|-----------------------|-----------------------|
##         very common |                  141  |                   63  |                  204  | 
##                     |              162.315  |               41.685  |                       | 
##                     |                2.799  |               10.899  |                       | 
##                     |               69.118% |               30.882% |                1.844% | 
## --------------------|-----------------------|-----------------------|-----------------------|
##       fairly common |                  876  |                  368  |                 1244  | 
##                     |              989.804  |              254.196  |                       | 
##                     |               13.085  |               50.950  |                       | 
##                     |               70.418% |               29.582% |               11.243% | 
## --------------------|-----------------------|-----------------------|-----------------------|
##     not very common |                 3173  |                  981  |                 4154  | 
##                     |             3305.180  |              848.820  |                       | 
##                     |                5.286  |               20.583  |                       | 
##                     |               76.384% |               23.616% |               37.542% | 
## --------------------|-----------------------|-----------------------|-----------------------|
##   not at all common |                 4614  |                  849  |                 5463  | 
##                     |             4346.701  |             1116.299  |                       | 
##                     |               16.437  |               64.005  |                       | 
##                     |               84.459% |               15.541% |               49.372% | 
## --------------------|-----------------------|-----------------------|-----------------------|
##        Column Total |                 8804  |                 2261  |                11065  | 
## --------------------|-----------------------|-----------------------|-----------------------|
## 
##  
## Statistics for All Table Factors
## 
## 
## Pearson&#39;s Chi-squared test 
## ------------------------------------------------------------
## Chi^2 =  184.0443     d.f. =  3     p =  1.180409e-39 
## 
## 
##  
##        Minimum expected frequency: 41.68495</code></pre>
<p>The output shows that, for example, 63 people lived in areas where rubbish was very common and experienced victimisation in the past year. Under the null hypothesis of no relationship, however, we should expect this value to be 41.69. Thus, more people are in this cell than we would expect under the null hypothesis.</p>
<p>The chi-square value is 184.04, with 3 degrees of freedom (df). The df is obtained by the number of rows minus one, then multiplied by the number of columns minus one: (4 − 1)*(2 − 1). The probability associated with this particular value is nearly zero (1.180e-39). This value is considerably lower than the standard alpha level of 0.05. We conclude that there is a significant relationship between victimisation and the presence of rubbish. We reject the null hypothesis.</p>
<p>If you do not want to use <code>CrossTable()</code>, you can use <code>chisq.test()</code> to give you the chi-square value:</p>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="relationships-with-categorical-variables.html#cb421-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(BCS0708<span class="sc">$</span>rubbcomm, BCS0708<span class="sc">$</span>bcsvictim)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  BCS0708$rubbcomm and BCS0708$bcsvictim
## X-squared = 184.04, df = 3, p-value &lt; 2.2e-16</code></pre>
<p>The chi-square statistic only tells us whether there is a relationship or not between two variables; it says nothing about strength of relationship or exactly what differences between observed and expected frequencies are driving the results.</p>
<p>For the chi-square to work though, it needs to have a sufficient number of cases in each cell. Notice that <code>R</code> was telling us that the minimum expected frequency is 41.68. One rule of thumb is that all expected cell counts should be above 5. If we have a small number in the cells, one alternative is to use <strong>Fisher’s exact test</strong>:</p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="relationships-with-categorical-variables.html#cb423-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(BCS0708<span class="sc">$</span>rubbcomm, BCS0708<span class="sc">$</span>bcsvictim)</span></code></pre></div>
<div class="sourceCode" id="cb424"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb424-1"><a href="relationships-with-categorical-variables.html#cb424-1" aria-hidden="true" tabindex="-1"></a><span class="co"># If you get an error message about increasing the size of your workspace, do so with this code:</span></span>
<span id="cb424-2"><a href="relationships-with-categorical-variables.html#cb424-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(BCS0708<span class="sc">$</span>rubbcomm, BCS0708<span class="sc">$</span>bcsvictim, <span class="at">workspace =</span> <span class="fl">2e+07</span>, <span class="at">hybrid =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Fisher&#39;s Exact Test for Count Data hybrid using asym.chisq. iff
##  (exp=5, perc=80, Emin=1)
## 
## data:  BCS0708$rubbcomm and BCS0708$bcsvictim
## p-value &lt; 2.2e-16
## alternative hypothesis: two.sided</code></pre>
<p>We did not need this test for our example, but we use it to illustrate how to use Fisher’s Exact Test when counts in cells are low. The p-value from Fisher’s exact test is still smaller than <span class="math inline">\(\alpha = 0.05\)</span>, so we reach the same conclusion that the relationship observed can be generalised to the population.</p>
</div>
<div id="effect-sizes" class="section level4" number="7.2.3.1">
<h4><span class="header-section-number">7.2.3.1</span> Effect sizes</h4>
<p>Now that we can generalise to the population, we want to return to the issue of - OK but what is the <em>strength</em> of the relationship? We will look at a few ways to talk about this.</p>
<div id="activity-9-residuals" class="section level6" number="7.2.3.1.0.1">
<h6><span class="header-section-number">7.2.3.1.0.1</span> Activity 9: Residuals</h6>
<p>Last, we had observed that there were differences between the observed and expected frequencies. This is called a <strong>residual</strong>. Some differences seem larger than others. For example, there were about 21 more people that lived in areas where rubbish was very common and they experienced victimisation than what were expected under the null hypothesis. When you see large differences, it is unsurprising to also expect that the cell in question may be playing a particularly strong role in driving the relationship between rubbish and victimisation.</p>
<p>We are not sure, however, of what is considered a large residual. A statistic that helps address this is the <strong>adjusted standardised residuals</strong>, which behaves like a z-score. Residuals indicate the difference between the expected and the observed counts on a standardised scale. When the null hypothesis is true, there is only about a 5% chance that any particular standardised residual exceeds 2 in absolute value.</p>
<p>Whenever you see differences that are greater than 2, the difference between expected and observed frequencies in that particular cell is significant and is driving the results of your chi-square test. Values above +3 or below −3 are considered convincing evidence of a true effect in that cell:</p>
<div class="sourceCode" id="cb426"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb426-1"><a href="relationships-with-categorical-variables.html#cb426-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Include argument ‘asresid= TRUE’ to include adjusted standardised residuals</span></span>
<span id="cb426-2"><a href="relationships-with-categorical-variables.html#cb426-2" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(BCS0708, <span class="fu">CrossTable</span>(<span class="fu">as_factor</span>(rubbcomm), <span class="fu">as_factor</span>(bcsvictim), <span class="at">expected =</span> <span class="cn">TRUE</span>,</span>
<span id="cb426-3"><a href="relationships-with-categorical-variables.html#cb426-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">prop.chisq =</span> <span class="cn">FALSE</span>, <span class="at">prop.c =</span> <span class="cn">FALSE</span>, <span class="at">prop.t =</span> <span class="cn">FALSE</span>, <span class="at">asresid =</span></span>
<span id="cb426-4"><a href="relationships-with-categorical-variables.html#cb426-4" aria-hidden="true" tabindex="-1"></a>                           <span class="cn">TRUE</span>, <span class="at">format =</span> <span class="fu">c</span>(<span class="st">&quot;SPSS&quot;</span>) ))</span></code></pre></div>
<pre><code>## 
##    Cell Contents
## |-------------------------|
## |                   Count |
## |         Expected Values |
## |             Row Percent |
## |           Adj Std Resid |
## |-------------------------|
## 
## Total Observations in Table:  11065 
## 
##                     | as_factor(bcsvictim) 
## as_factor(rubbcomm) | not a victim of crime  |       victim of crime  |             Row Total | 
## --------------------|-----------------------|-----------------------|-----------------------|
##         very common |                  141  |                   63  |                  204  | 
##                     |              162.315  |               41.685  |                       | 
##                     |               69.118% |               30.882% |                1.844% | 
##                     |               -3.736  |                3.736  |                       | 
## --------------------|-----------------------|-----------------------|-----------------------|
##       fairly common |                  876  |                  368  |                 1244  | 
##                     |              989.804  |              254.196  |                       | 
##                     |               70.418% |               29.582% |               11.243% | 
##                     |               -8.494  |                8.494  |                       | 
## --------------------|-----------------------|-----------------------|-----------------------|
##     not very common |                 3173  |                  981  |                 4154  | 
##                     |             3305.180  |              848.820  |                       | 
##                     |               76.384% |               23.616% |               37.542% | 
##                     |               -6.436  |                6.436  |                       | 
## --------------------|-----------------------|-----------------------|-----------------------|
##   not at all common |                 4614  |                  849  |                 5463  | 
##                     |             4346.701  |             1116.299  |                       | 
##                     |               84.459% |               15.541% |               49.372% | 
##                     |               12.605  |              -12.605  |                       | 
## --------------------|-----------------------|-----------------------|-----------------------|
##        Column Total |                 8804  |                 2261  |                11065  | 
## --------------------|-----------------------|-----------------------|-----------------------|
## 
##  
## Statistics for All Table Factors
## 
## 
## Pearson&#39;s Chi-squared test 
## ------------------------------------------------------------
## Chi^2 =  184.0443     d.f. =  3     p =  1.180409e-39 
## 
## 
##  
##        Minimum expected frequency: 41.68495</code></pre>
<p>The column representing the outcome of interest (victimisation present), shows the adjusted standardised residual is lower than −12 for the ‘not at all common’ category. That is the largest residual for the DV. The expected count under the null hypothesis in this cell is much higher than the observed count.</p>
</div>
<div id="activity-10-gamma" class="section level5" number="7.2.3.1.1">
<h5><span class="header-section-number">7.2.3.1.1</span> Activity 10: Gamma</h5>
<p>Okay but what about something that helps us answer overall - Is this relationship strong? The residuals seem to be suggesting it is not trivial indeed. Apart from looking at the residuals, one of the tests discussed in the required reading as a test for the strength of a relationship is gamma. Gamma is a measure of association that allow us to make a judgement about the strength of this relationship and that we can use with ordinal measures (or as in this case when one variable is ordinal and the other is nominal dichotomous).</p>
<blockquote>
<p>Gamma is appropriate for testing the relationship between two categorical ordered variables (ordinal-level variables) or between a categorical ordered variable and a categorical unordered variables with only two levels (a dichotomous variable, such as “victimisation”: that only has two levels, you have or you haven’t experienced a victimisation).</p>
</blockquote>
<p>How can you obtain gamma with R?</p>
<p>We will use the package <code>vcdExtra</code> for it (which you may need to install and load) to compute gamma. We use the following code.</p>
<p>We first create a new object in tabular form because the function we use to compute Goodman and Kruskal’s Gamma needs an object of that nature.</p>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="relationships-with-categorical-variables.html#cb428-1" aria-hidden="true" tabindex="-1"></a>mytable<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">table</span>(BCS0708<span class="sc">$</span>bcsvictim, BCS0708<span class="sc">$</span>rubbcomm) </span></code></pre></div>
<p>You can print the content of this object and you will see that it is simply the crosstab with just the counts.</p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="relationships-with-categorical-variables.html#cb429-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mytable<span class="fl">.2</span>) </span></code></pre></div>
<pre><code>##    
##        1    2    3    4
##   0  141  876 3173 4614
##   1   63  368  981  849</code></pre>
<p>Then load the vcdExtra package (assuming it is already installed) and use the <code>GKgamma()</code> function from the vcdExtra package to compute the Gamma measure of association, between parenthesis you need to identify the object that contains your data.</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="relationships-with-categorical-variables.html#cb431-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcdExtra) </span>
<span id="cb431-2"><a href="relationships-with-categorical-variables.html#cb431-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb431-3"><a href="relationships-with-categorical-variables.html#cb431-3" aria-hidden="true" tabindex="-1"></a><span class="fu">GKgamma</span>(mytable<span class="fl">.2</span>) </span></code></pre></div>
<pre><code>## gamma        : -0.266 
## std. error   : 0.019 
## CI           : -0.302 -0.229</code></pre>
<p>Gamma falls between -1 and +1. The sign indicates whether the association is positive or negative. In this case it is positive: this suggests that the higher order of the categories in the ordinal measure (rubbish) is associated with higher values in the second variable (victimisation). Higher in this context mean the order in which they appear in your table. So the highest in your ordinal measure (how common rubbish is) refers to the last row (very common). And highest in the dichotomous measure refers to the last column (victim of a crime). Keep this in mind when interpreting gamma.</p>
<p>The larger the absolute value of gamma, the stronger the association. There are not clear rules of thumb in how to interpret Gamma. This value is larger than 0, although closer to 0 than to 1. De Vaus (2002) provides the following rules of thumb: up to .10 (trivial association), .10 to .29 (low to moderate), .30 to .49 (moderate to substantial), .50 to .69 (substantial to very strong), .70 to .89 (very strong), .9 and above (near perfect). On those bases, I would say this particular Gamma estimated at .226 indicates an association of modest size. Notice that the confidence interval is provided. So the estimated gamma with an alpha level of 0.05 is estimated to be anywhere between 0.302 and 0.229. If this confidence interval overlapped with 0 we could not reject the null hypothesis.</p>
<p>Gamma, however, assumes a “linear” relationship, more in one of the variables, more in the other (for positive relationships), less in one, more in the other (for negative relationships). Here we can see that the percentage of people that experience victimisation is almost the same for those who live in areas where rubbish is fairly common but also for those who live in areas where it is very common. That is, once we reach a certain level of rubbish the risk of victimisation does not go much higher. In situations like this gamma is likely underestimating the strength of the relationship.</p>
</div>
<div id="activity-11-odds-and-odd-ratios" class="section level5" number="7.2.3.1.2">
<h5><span class="header-section-number">7.2.3.1.2</span> Activity 11: Odds and odd ratios</h5>
<p>When you have two dichotomous nominal level variables, that is, two nominal level variables that can take only two possible levels, one of the more commonly used measures to indicate the strength of an association are odd ratios. Odd ratios and relative risk are very commonly used in public health and in criminological research. If you have knowledge of betting, you may already know a thing or two about odds.</p>
<p>They are the statistical equivalent of a tongue twister, so don’t worry too much if you need to keep looking at this handout every time you want to interpret them. We are going to look at the relationship between victimisation and living in a rural/urban setting:</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="relationships-with-categorical-variables.html#cb433-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(BCS0708, <span class="fu">CrossTable</span>(rural2, bcsvictim, <span class="at">prop.c =</span> <span class="cn">FALSE</span>, <span class="at">prop.t =</span> <span class="cn">FALSE</span>, <span class="at">expected =</span> <span class="cn">TRUE</span>, <span class="at">format =</span> <span class="fu">c</span>(<span class="st">&quot;SPSS&quot;</span>)))</span></code></pre></div>
<pre><code>## 
##    Cell Contents
## |-------------------------|
## |                   Count |
## |         Expected Values |
## | Chi-square contribution |
## |             Row Percent |
## |-------------------------|
## 
## Total Observations in Table:  11676 
## 
##              | bcsvictim 
##       rural2 |        0  |        1  | Row Total | 
## -------------|-----------|-----------|-----------|
##            1 |     6757  |     1945  |     8702  | 
##              | 6944.607  | 1757.393  |           | 
##              |    5.068  |   20.028  |           | 
##              |   77.649% |   22.351% |   74.529% | 
## -------------|-----------|-----------|-----------|
##            2 |     2561  |      413  |     2974  | 
##              | 2373.393  |  600.607  |           | 
##              |   14.830  |   58.602  |           | 
##              |   86.113% |   13.887% |   25.471% | 
## -------------|-----------|-----------|-----------|
## Column Total |     9318  |     2358  |    11676  | 
## -------------|-----------|-----------|-----------|
## 
##  
## Statistics for All Table Factors
## 
## 
## Pearson&#39;s Chi-squared test 
## ------------------------------------------------------------
## Chi^2 =  98.52709     d.f. =  1     p =  3.206093e-23 
## 
## Pearson&#39;s Chi-squared test with Yates&#39; continuity correction 
## ------------------------------------------------------------
## Chi^2 =  98.00261     d.f. =  1     p =  4.178318e-23 
## 
##  
##        Minimum expected frequency: 600.6074</code></pre>
<p>So we can see that 22% of urban dwellers by comparison to 14% of those living in rural areas have experienced a victimisation in the previous past year. It looks as if living in an urban environment constitutes a risk factor or is associated with victimisation. The Chi Square we obtain has a low p value suggesting that this association is statistically significant. That is, we can possibly infer that there is an association in the population from which the sample was drawn. But how large is this relationship?</p>
<p>This is where odd ratios are handy. Before we get to them I will discuss a simple tip in layout. Risk ratios and odd ratios are very commonly used in the public health tradition. In this tradition researchers place the disease/condition defining the columns and the treatment or risk factor defining the rows and they do so in such a way that the first cell correspond to the intersection of the outcome and the risk factor. And the software that computes odd ratios tends to assume this is how your table is set up. So, whenever you are after the relative risks or odd ratios (that is, whenever you work with a 2X2 table) you should laid the table like this as well. It will help interpretation:</p>
<table style="width:83%;">
<colgroup>
<col width="27%" />
<col width="30%" />
<col width="25%" />
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td>Outcome: Yes</td>
<td>Outcome: No</td>
</tr>
<tr class="even">
<td>Risk factor: Yes</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Risk factor: No</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>Our table was set up in such a way that the rows are defined by our “risk factor” and the columns by our outcome. But the first cell represents the intersection of the presence of the risk factor and the absence of the outcome. The easiest way to sort this out is to change the order of the levels in our factor variable identifying the outcome (“bcsvictim”). If we ask R to print the levels of the bcsvictim variable we will see that they are as follow:</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="relationships-with-categorical-variables.html#cb435-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">levels</span>(BCS0708<span class="sc">$</span>bcsvictim))</span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="relationships-with-categorical-variables.html#cb437-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">levels</span>(BCS0708<span class="sc">$</span>rural2))</span></code></pre></div>
<pre><code>## NULL</code></pre>
<p>We want to reverse this. So that “victim of crime” becomes the first level (appears first in the print out) and “urban” becomes the first level as well. There are various ways of doing that with add-on packages, this is an easy way using base R:</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="relationships-with-categorical-variables.html#cb439-1" aria-hidden="true" tabindex="-1"></a>BCS0708<span class="sc">$</span>bcsvictimR <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(BCS0708<span class="sc">$</span>bcsvictim)</span>
<span id="cb439-2"><a href="relationships-with-categorical-variables.html#cb439-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">levels</span>(BCS0708<span class="sc">$</span>bcsvictimR))</span></code></pre></div>
<pre><code>## [1] &quot;not a victim of crime&quot; &quot;victim of crime&quot;</code></pre>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="relationships-with-categorical-variables.html#cb441-1" aria-hidden="true" tabindex="-1"></a>BCS0708<span class="sc">$</span>urban <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(BCS0708<span class="sc">$</span>rural2)</span>
<span id="cb441-2"><a href="relationships-with-categorical-variables.html#cb441-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">levels</span>(BCS0708<span class="sc">$</span>urban))</span></code></pre></div>
<pre><code>## [1] &quot;urban&quot; &quot;rural&quot;</code></pre>
<p>We can now rerun the previous cross tabulation (with the newly created reordered factors) and the table will look as below:</p>
<div class="sourceCode" id="cb443"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb443-1"><a href="relationships-with-categorical-variables.html#cb443-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(BCS0708, <span class="fu">CrossTable</span>(urban, bcsvictimR, <span class="at">prop.c =</span> <span class="cn">FALSE</span>, <span class="at">prop.t =</span> <span class="cn">FALSE</span>, <span class="at">expected =</span> <span class="cn">TRUE</span>, <span class="at">format =</span> <span class="fu">c</span>(<span class="st">&quot;SPSS&quot;</span>)))</span></code></pre></div>
<pre><code>## 
##    Cell Contents
## |-------------------------|
## |                   Count |
## |         Expected Values |
## | Chi-square contribution |
## |             Row Percent |
## |-------------------------|
## 
## Total Observations in Table:  11676 
## 
##              | bcsvictimR 
##        urban | not a victim of crime  |       victim of crime  |             Row Total | 
## -------------|-----------------------|-----------------------|-----------------------|
##        urban |                 6757  |                 1945  |                 8702  | 
##              |             6944.607  |             1757.393  |                       | 
##              |                5.068  |               20.028  |                       | 
##              |               77.649% |               22.351% |               74.529% | 
## -------------|-----------------------|-----------------------|-----------------------|
##        rural |                 2561  |                  413  |                 2974  | 
##              |             2373.393  |              600.607  |                       | 
##              |               14.830  |               58.602  |                       | 
##              |               86.113% |               13.887% |               25.471% | 
## -------------|-----------------------|-----------------------|-----------------------|
## Column Total |                 9318  |                 2358  |                11676  | 
## -------------|-----------------------|-----------------------|-----------------------|
## 
##  
## Statistics for All Table Factors
## 
## 
## Pearson&#39;s Chi-squared test 
## ------------------------------------------------------------
## Chi^2 =  98.52709     d.f. =  1     p =  3.206093e-23 
## 
## Pearson&#39;s Chi-squared test with Yates&#39; continuity correction 
## ------------------------------------------------------------
## Chi^2 =  98.00261     d.f. =  1     p =  4.178318e-23 
## 
##  
##        Minimum expected frequency: 600.6074</code></pre>
<p>In order to understand odd ratios and relative risk is important to understand risks and odds first. The <strong>risk</strong> is simply the probability of the “outcome” we are concerned about (i.e., victimisation). So the risk of victimisation for urban dwellers is simply the number of victimised urban dwellers (1945) divided by the total number of urban dwellers (8702). This is .2235. Similarly we can look at the risk of victimisation for people living in rural areas: the number of victimised countryside residents (413) divided by the total number of residents in rural areas (2974). This is .1388. The <strong>relative risk</strong> is simply the ratio of these two risks. In this case this yields 1.60. This suggests that urban dwellers are 1.60 times more likely to be victimised than people who live in rural areas.</p>
<p>The <strong>odds</strong> on the other hand contrast the number of individuals with the outcome with those without the outcome for each of the rows. Notice the difference with the risk. So the odds of victimisation for urban dwellers equal the number of victimised urban dwellers (1945) by the number of non-victimised urban dwellers (6757). This is .2878. There are .2878 victimised urban dwellers for every non-victimised urban dweller. And the odds of victimisation for residents of rural areas equal the number of victimised rural residents (413) by the number of non-victimised rural residents (2561). This is .1612. There are .1612 victimised rural residents for every non-victimised rural resident.</p>
<p>The <strong>odds ratio</strong> is the ratio of these two odds. So the odds ratio of victimisation for urban dwellers to rural residents is the odds of victimisation for urban dwellers (.2878) divided by the odds of victimisation for rural residents (.1612). This yields 1.78. This means that the odds of victimisation are almost 1.78 times higher for urban dwellers than for residents in rural areas.</p>
<p>You can use R to obtain the odd ratios directly. We can use the <code>vcd</code> package we mentioned earlier. As before we first create an object with the table and then ask for the ordinary odds ratio using the following code:</p>
<div class="sourceCode" id="cb445"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb445-1"><a href="relationships-with-categorical-variables.html#cb445-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd)</span>
<span id="cb445-2"><a href="relationships-with-categorical-variables.html#cb445-2" aria-hidden="true" tabindex="-1"></a>mytable<span class="fl">.3</span><span class="ot">&lt;-</span><span class="fu">table</span>(BCS0708<span class="sc">$</span>urban, BCS0708<span class="sc">$</span>bcsvictimR)</span>
<span id="cb445-3"><a href="relationships-with-categorical-variables.html#cb445-3" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio</span>(mytable<span class="fl">.3</span>, <span class="at">stratum =</span> <span class="cn">NULL</span>, <span class="at">log =</span> <span class="cn">FALSE</span>) </span></code></pre></div>
<pre><code>##  odds ratios for  and  
## 
## [1] 0.5602409</code></pre>
<p>The <code>oddsratio</code> function here is asking for the oddsratio for the table data in the object called <em>mytable.3</em>. The <code>log=FALSE</code> requests an ordinary odds ratio and the <code>stratum</code> option clarifies your data are not stratified.</p>
<p>What would happen if rather than using the recoded variable (“bcsvictimR”) we use the original one?</p>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="relationships-with-categorical-variables.html#cb447-1" aria-hidden="true" tabindex="-1"></a>mytable<span class="fl">.4</span><span class="ot">&lt;-</span><span class="fu">table</span>(BCS0708<span class="sc">$</span>urban, BCS0708<span class="sc">$</span>bcsvictim)</span>
<span id="cb447-2"><a href="relationships-with-categorical-variables.html#cb447-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mytable<span class="fl">.4</span>)</span></code></pre></div>
<pre><code>##        
##            0    1
##   urban 6757 1945
##   rural 2561  413</code></pre>
<div class="sourceCode" id="cb449"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb449-1"><a href="relationships-with-categorical-variables.html#cb449-1" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio</span>(mytable<span class="fl">.4</span>, <span class="at">stratum =</span> <span class="cn">NULL</span>, <span class="at">log =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>##  odds ratios for  and  
## 
## [1] 0.5602409</code></pre>
<p>What’s going on? Why do we have a different value here? If you look at the cross tab you should be able to understand. R is now computing the odd ratio for “not being a victim of a crime” (since this is what defines the first column). When an odds ratio is below 1 is indicating that the odds in the first row (“urban”) are lower than in the second row (“rural”). Living in urban areas (as contrasted with living in rural areas) reduces the likelihood of non-victimisation.</p>
<p>How to interpret odd ratios? Something that is important to keep in mind is that odd ratios (and relative risk) are non-negative values, that is: they cannot take negative values (i.e., -1, -3, etc.). They can go from 1 to infinite but only from 1 to zero. If the value is greater than 1 that means that, as in this case, living in an urban area increases the chances of the event, being a victim in this example. If the value were to be between 0 and 1 that would mean that the factor in question reduces the chances of the event you are trying to predict. Finally, a value of 1 means that there is no relationship between the two variables: it would mean that the odds or the risks are the same for the two groups.</p>
<p>Whenever the odd ratio is between 0 and 1 that means that the odds of whatever it is defining the first column (in the more recent table we printed not being a victim) is lower for the first row (in this case living in an urban area) than in the second row (in this case living in a rural area). To read an odd ratio that is between 0 and 1 you first need to take its inverse, so in this case 1/0.5602 will give you 1.78. What this is telling you is that the odds of not being a victim of victim are 1.78 times less for men than for women, which is the same as to say that the odds of being a victim of assault are 1.78 more for men than for women. That is, odd ratios are reciprocal.</p>
<p>You may be confused by now. Have a look at <a href="https://www.youtube.com/watch?v=nFHL54yOniI">this video</a>, it may help to see an oral presentation of these ideas with a different example. Repeated practice will make it easier to understand. The fact that the interpretation of these quantities is contingent in the way we have laid out our table makes it particularly advisable to hand calculate them as explained above in relation to the outcome you are interested until you are comfortable with them. This may help you to see more clearly what you are getting and how to interpret it. When looking at the R results for odd ratios just always keep in mind that you are aware of what are the reference categories (what defines the first column and the first row) when reading and interpreting odd ratios. The R function we introduced will always give you the odds ratio for the event defined in the first column and will contrast the odds for the group defined by the first row with the odds defined by the second row. If the odds ratio is between 0 and 1 that would mean the odds are lower for the first row, if the odds is greater than 1 that would mean the odds are higher for the second row.</p>
<p>It is also very important you do not confuse the relative risk (a ratio of probabilities) with the odds ratio (a ratio of odds). Be very careful with the language you use when interpreting these quantities.</p>
<p>Odd ratios are ratios of odds, not probability ratios. You cannot say that urban dwellers are 1.78 more likely to be victimised. All you can say with an odd ratio is that the odds of being victimised are 1.78 times higher for urban dwellers than for residents in rural areas. Odds and probabilities are different things.</p>
<p>It is also very important that you interpret these quantities carefully. You will often see media reports announcing things such as that chocolate consumption will double your risk of some terrible disease. What that means is that the percentage of cases of individuals that take chocolate and present the condition is twice as large as those that do not take chocolate and present the condition. But you also need to know what those percentages are to put it in the right context. If those probabilities are very low to start with, well, does it really matter?</p>
<div class="figure">
<img src="Images/increased_risk.png" alt="" />
<p class="caption"><strong>Figure 7.1</strong> increased risk</p>
</div>
<hr />
</div>
</div>
</div>
</div>
<div id="summary-6" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> SUMMARY</h2>
<p>We learned a few inferential statistical analyses to examine relationships with categorical variables, known as <strong>factors</strong> in <code>R</code>. These variables, in today’s analyses, were arranged as <strong>independent variables</strong> or <strong>dependent variables</strong>. When analysing a relationship between a categorical and a numeric variable, the t-test was used. We learned to conduct <strong>independent sample</strong> and <strong>dependent sample</strong> t-tests.</p>
<p>Before we performed the former t-test, we conducted the <strong>test for equality of variance</strong>. We also learned about effect size with <strong>Cohen’s d</strong>. In the latter section, we learned to conduct a chi-square test, a test of statistical significance between two categorical variables. This involved <strong>contingency tables</strong>, whereby we examined specifically <strong>cross tabulations</strong>.</p>
<p>The chi-square statistic contrasts <strong>expected</strong> and <strong>observed</strong> frequencies in the cross-tab. When counts in any one cell is lower than five, <strong>Fisher’s Exact Test</strong> is used instead. We also check the <strong>adjusted standardised residuals</strong> to identify which contrast of frequencies are driving the observed results. We also learned about effect size here too with <strong>Gamma</strong> and <strong>Odds Ratios</strong>.</p>
<p>Homework time!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="hypotheses.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="strength-of-relationships.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/07-relationships-categorical-variable.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Modelling-Crime-Data-2021.pdf", "Modelling-Crime-Data-2021.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
